// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: merchant.proto

package merchantclient

import (
	"context"

	"github.com/gloopai/pay/merchant/merchant"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetMerchantReq     = merchant.GetMerchantReq
	GetMerchantResp    = merchant.GetMerchantResp
	GetAuthInfoReq     = merchant.GetAuthInfoReq
	GetAuthInfoResp    = merchant.GetAuthInfoResp
	ListMerchantsReq   = merchant.ListMerchantsReq
	ListMerchantsResp  = merchant.ListMerchantsResp
	CreateMerchantReq  = merchant.CreateMerchantReq
	UpdateMerchantReq  = merchant.UpdateMerchantReq
	UpsertMerchantResp = merchant.UpsertMerchantResp
	MerchantInfo       = merchant.MerchantInfo

	Merchant interface {
		GetMerchant(ctx context.Context, in *GetMerchantReq, opts ...grpc.CallOption) (*GetMerchantResp, error)
		GetAuthInfo(ctx context.Context, in *GetAuthInfoReq, opts ...grpc.CallOption) (*GetAuthInfoResp, error)
		ListMerchants(ctx context.Context, in *ListMerchantsReq, opts ...grpc.CallOption) (*ListMerchantsResp, error)
		CreateMerchant(ctx context.Context, in *CreateMerchantReq, opts ...grpc.CallOption) (*UpsertMerchantResp, error)
		UpdateMerchant(ctx context.Context, in *UpdateMerchantReq, opts ...grpc.CallOption) (*UpsertMerchantResp, error)
	}

	defaultMerchant struct {
		cli zrpc.Client
	}
)

func NewMerchant(cli zrpc.Client) Merchant {
	return &defaultMerchant{
		cli: cli,
	}
}

func (m *defaultMerchant) GetMerchant(ctx context.Context, in *GetMerchantReq, opts ...grpc.CallOption) (*GetMerchantResp, error) {
	client := merchant.NewMerchantClient(m.cli.Conn())
	return client.GetMerchant(ctx, in, opts...)
}

func (m *defaultMerchant) GetAuthInfo(ctx context.Context, in *GetAuthInfoReq, opts ...grpc.CallOption) (*GetAuthInfoResp, error) {
	client := merchant.NewMerchantClient(m.cli.Conn())
	return client.GetAuthInfo(ctx, in, opts...)
}

func (m *defaultMerchant) ListMerchants(ctx context.Context, in *ListMerchantsReq, opts ...grpc.CallOption) (*ListMerchantsResp, error) {
	client := merchant.NewMerchantClient(m.cli.Conn())
	return client.ListMerchants(ctx, in, opts...)
}

func (m *defaultMerchant) CreateMerchant(ctx context.Context, in *CreateMerchantReq, opts ...grpc.CallOption) (*UpsertMerchantResp, error) {
	client := merchant.NewMerchantClient(m.cli.Conn())
	return client.CreateMerchant(ctx, in, opts...)
}

func (m *defaultMerchant) UpdateMerchant(ctx context.Context, in *UpdateMerchantReq, opts ...grpc.CallOption) (*UpsertMerchantResp, error) {
	client := merchant.NewMerchantClient(m.cli.Conn())
	return client.UpdateMerchant(ctx, in, opts...)
}
