// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package orderclient

import (
	"context"

	"github.com/gloopai/pay/common/pb/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOrderReq   = order.CreateOrderReq
	CreateOrderResp  = order.CreateOrderResp
	GetOrderReq      = order.GetOrderReq
	GetOrderResp     = order.GetOrderResp
	MarkPaidReq      = order.MarkPaidReq
	MarkPaidResp     = order.MarkPaidResp
	ListOrdersReq    = order.ListOrdersReq
	ListOrdersResp   = order.ListOrdersResp
	TodaySummaryReq  = order.TodaySummaryReq
	TodaySummaryResp = order.TodaySummaryResp
	OrderInfo        = order.OrderInfo

	Order interface {
		CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
		GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error)
		MarkPaid(ctx context.Context, in *MarkPaidReq, opts ...grpc.CallOption) (*MarkPaidResp, error)
		ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error)
		TodaySummary(ctx context.Context, in *TodaySummaryReq, opts ...grpc.CallOption) (*TodaySummaryResp, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrder) GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

func (m *defaultOrder) MarkPaid(ctx context.Context, in *MarkPaidReq, opts ...grpc.CallOption) (*MarkPaidResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.MarkPaid(ctx, in, opts...)
}

func (m *defaultOrder) ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.ListOrders(ctx, in, opts...)
}

func (m *defaultOrder) TodaySummary(ctx context.Context, in *TodaySummaryReq, opts ...grpc.CallOption) (*TodaySummaryResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.TodaySummary(ctx, in, opts...)
}
