// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: channel.proto

package server

import (
	"context"

	"github.com/gloopai/pay/channel/channel/channel"
	"github.com/gloopai/pay/channel/internal/logic"
	"github.com/gloopai/pay/channel/internal/svc"
)

type ChannelServer struct {
	svcCtx *svc.ServiceContext
	channel.UnimplementedChannelServer
}

func NewChannelServer(svcCtx *svc.ServiceContext) *ChannelServer {
	return &ChannelServer{
		svcCtx: svcCtx,
	}
}

func (s *ChannelServer) Route(ctx context.Context, in *channel.RouteReq) (*channel.RouteResp, error) {
	l := logic.NewRouteLogic(ctx, s.svcCtx)
	return l.Route(in)
}
