// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: settle.proto

package settle

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Settle_Credit_FullMethodName                = "/settle.Settle/Credit"
	Settle_DebitPayout_FullMethodName           = "/settle.Settle/DebitPayout"
	Settle_TransferPayinToPayout_FullMethodName = "/settle.Settle/TransferPayinToPayout"
	Settle_ListFundLogs_FullMethodName          = "/settle.Settle/ListFundLogs"
)

// SettleClient is the client API for Settle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettleClient interface {
	Credit(ctx context.Context, in *CreditReq, opts ...grpc.CallOption) (*CreditResp, error)
	DebitPayout(ctx context.Context, in *DebitPayoutReq, opts ...grpc.CallOption) (*DebitPayoutResp, error)
	TransferPayinToPayout(ctx context.Context, in *TransferPayinToPayoutReq, opts ...grpc.CallOption) (*TransferPayinToPayoutResp, error)
	ListFundLogs(ctx context.Context, in *ListFundLogsReq, opts ...grpc.CallOption) (*ListFundLogsResp, error)
}

type settleClient struct {
	cc grpc.ClientConnInterface
}

func NewSettleClient(cc grpc.ClientConnInterface) SettleClient {
	return &settleClient{cc}
}

func (c *settleClient) Credit(ctx context.Context, in *CreditReq, opts ...grpc.CallOption) (*CreditResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditResp)
	err := c.cc.Invoke(ctx, Settle_Credit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleClient) DebitPayout(ctx context.Context, in *DebitPayoutReq, opts ...grpc.CallOption) (*DebitPayoutResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DebitPayoutResp)
	err := c.cc.Invoke(ctx, Settle_DebitPayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleClient) TransferPayinToPayout(ctx context.Context, in *TransferPayinToPayoutReq, opts ...grpc.CallOption) (*TransferPayinToPayoutResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferPayinToPayoutResp)
	err := c.cc.Invoke(ctx, Settle_TransferPayinToPayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleClient) ListFundLogs(ctx context.Context, in *ListFundLogsReq, opts ...grpc.CallOption) (*ListFundLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFundLogsResp)
	err := c.cc.Invoke(ctx, Settle_ListFundLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettleServer is the server API for Settle service.
// All implementations must embed UnimplementedSettleServer
// for forward compatibility.
type SettleServer interface {
	Credit(context.Context, *CreditReq) (*CreditResp, error)
	DebitPayout(context.Context, *DebitPayoutReq) (*DebitPayoutResp, error)
	TransferPayinToPayout(context.Context, *TransferPayinToPayoutReq) (*TransferPayinToPayoutResp, error)
	ListFundLogs(context.Context, *ListFundLogsReq) (*ListFundLogsResp, error)
	mustEmbedUnimplementedSettleServer()
}

// UnimplementedSettleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettleServer struct{}

func (UnimplementedSettleServer) Credit(context.Context, *CreditReq) (*CreditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Credit not implemented")
}
func (UnimplementedSettleServer) DebitPayout(context.Context, *DebitPayoutReq) (*DebitPayoutResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DebitPayout not implemented")
}
func (UnimplementedSettleServer) TransferPayinToPayout(context.Context, *TransferPayinToPayoutReq) (*TransferPayinToPayoutResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferPayinToPayout not implemented")
}
func (UnimplementedSettleServer) ListFundLogs(context.Context, *ListFundLogsReq) (*ListFundLogsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFundLogs not implemented")
}
func (UnimplementedSettleServer) mustEmbedUnimplementedSettleServer() {}
func (UnimplementedSettleServer) testEmbeddedByValue()                {}

// UnsafeSettleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettleServer will
// result in compilation errors.
type UnsafeSettleServer interface {
	mustEmbedUnimplementedSettleServer()
}

func RegisterSettleServer(s grpc.ServiceRegistrar, srv SettleServer) {
	// If the following call pancis, it indicates UnimplementedSettleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Settle_ServiceDesc, srv)
}

func _Settle_Credit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).Credit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settle_Credit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).Credit(ctx, req.(*CreditReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settle_DebitPayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebitPayoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).DebitPayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settle_DebitPayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).DebitPayout(ctx, req.(*DebitPayoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settle_TransferPayinToPayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferPayinToPayoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).TransferPayinToPayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settle_TransferPayinToPayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).TransferPayinToPayout(ctx, req.(*TransferPayinToPayoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settle_ListFundLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFundLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).ListFundLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settle_ListFundLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).ListFundLogs(ctx, req.(*ListFundLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Settle_ServiceDesc is the grpc.ServiceDesc for Settle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Settle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "settle.Settle",
	HandlerType: (*SettleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Credit",
			Handler:    _Settle_Credit_Handler,
		},
		{
			MethodName: "DebitPayout",
			Handler:    _Settle_DebitPayout_Handler,
		},
		{
			MethodName: "TransferPayinToPayout",
			Handler:    _Settle_TransferPayinToPayout_Handler,
		},
		{
			MethodName: "ListFundLogs",
			Handler:    _Settle_ListFundLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "settle.proto",
}
