// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: settle.proto

package settleclient

import (
	"context"

	"github.com/gloopai/pay/common/pb/settle"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreditReq  = settle.CreditReq
	CreditResp = settle.CreditResp

	Settle interface {
		Credit(ctx context.Context, in *CreditReq, opts ...grpc.CallOption) (*CreditResp, error)
	}

	defaultSettle struct {
		cli zrpc.Client
	}
)

func NewSettle(cli zrpc.Client) Settle {
	return &defaultSettle{
		cli: cli,
	}
}

func (m *defaultSettle) Credit(ctx context.Context, in *CreditReq, opts ...grpc.CallOption) (*CreditResp, error) {
	client := settle.NewSettleClient(m.cli.Conn())
	return client.Credit(ctx, in, opts...)
}
