// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: channel.proto

package channel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	PayType       string                 `protobuf:"bytes,2,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteReq) Reset() {
	*x = RouteReq{}
	mi := &file_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteReq) ProtoMessage() {}

func (x *RouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteReq.ProtoReflect.Descriptor instead.
func (*RouteReq) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{0}
}

func (x *RouteReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RouteReq) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

type RouteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int64                  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResp) Reset() {
	*x = RouteResp{}
	mi := &file_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResp) ProtoMessage() {}

func (x *RouteResp) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResp.ProtoReflect.Descriptor instead.
func (*RouteResp) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{1}
}

func (x *RouteResp) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

var File_channel_proto protoreflect.FileDescriptor

const file_channel_proto_rawDesc = "" +
	"\n" +
	"\rchannel.proto\x12\achannel\"=\n" +
	"\bRouteReq\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x19\n" +
	"\bpay_type\x18\x02 \x01(\tR\apayType\"*\n" +
	"\tRouteResp\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x03R\tchannelId29\n" +
	"\aChannel\x12.\n" +
	"\x05Route\x12\x11.channel.RouteReq\x1a\x12.channel.RouteRespB\vZ\t./channelb\x06proto3"

var (
	file_channel_proto_rawDescOnce sync.Once
	file_channel_proto_rawDescData []byte
)

func file_channel_proto_rawDescGZIP() []byte {
	file_channel_proto_rawDescOnce.Do(func() {
		file_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_channel_proto_rawDesc), len(file_channel_proto_rawDesc)))
	})
	return file_channel_proto_rawDescData
}

var file_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_channel_proto_goTypes = []any{
	(*RouteReq)(nil),  // 0: channel.RouteReq
	(*RouteResp)(nil), // 1: channel.RouteResp
}
var file_channel_proto_depIdxs = []int32{
	0, // 0: channel.Channel.Route:input_type -> channel.RouteReq
	1, // 1: channel.Channel.Route:output_type -> channel.RouteResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_channel_proto_init() }
func file_channel_proto_init() {
	if File_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_channel_proto_rawDesc), len(file_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_channel_proto_goTypes,
		DependencyIndexes: file_channel_proto_depIdxs,
		MessageInfos:      file_channel_proto_msgTypes,
	}.Build()
	File_channel_proto = out.File
	file_channel_proto_goTypes = nil
	file_channel_proto_depIdxs = nil
}
