// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: merchant.proto

package merchant

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Merchant_GetMerchant_FullMethodName                   = "/merchant.Merchant/GetMerchant"
	Merchant_GetAuthInfo_FullMethodName                   = "/merchant.Merchant/GetAuthInfo"
	Merchant_ListMerchants_FullMethodName                 = "/merchant.Merchant/ListMerchants"
	Merchant_CreateMerchant_FullMethodName                = "/merchant.Merchant/CreateMerchant"
	Merchant_UpdateMerchant_FullMethodName                = "/merchant.Merchant/UpdateMerchant"
	Merchant_ReplaceMerchantPayProducts_FullMethodName    = "/merchant.Merchant/ReplaceMerchantPayProducts"
	Merchant_ReplaceMerchantPayoutProducts_FullMethodName = "/merchant.Merchant/ReplaceMerchantPayoutProducts"
	Merchant_ListMerchantPayProductIds_FullMethodName     = "/merchant.Merchant/ListMerchantPayProductIds"
	Merchant_ListMerchantPayoutProductIds_FullMethodName  = "/merchant.Merchant/ListMerchantPayoutProductIds"
)

// MerchantClient is the client API for Merchant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MerchantClient interface {
	GetMerchant(ctx context.Context, in *GetMerchantReq, opts ...grpc.CallOption) (*GetMerchantResp, error)
	GetAuthInfo(ctx context.Context, in *GetAuthInfoReq, opts ...grpc.CallOption) (*GetAuthInfoResp, error)
	ListMerchants(ctx context.Context, in *ListMerchantsReq, opts ...grpc.CallOption) (*ListMerchantsResp, error)
	CreateMerchant(ctx context.Context, in *CreateMerchantReq, opts ...grpc.CallOption) (*UpsertMerchantResp, error)
	UpdateMerchant(ctx context.Context, in *UpdateMerchantReq, opts ...grpc.CallOption) (*UpsertMerchantResp, error)
	ReplaceMerchantPayProducts(ctx context.Context, in *ReplaceMerchantPayProductsReq, opts ...grpc.CallOption) (*ReplaceMerchantPayProductsResp, error)
	ReplaceMerchantPayoutProducts(ctx context.Context, in *ReplaceMerchantPayoutProductsReq, opts ...grpc.CallOption) (*ReplaceMerchantPayoutProductsResp, error)
	ListMerchantPayProductIds(ctx context.Context, in *ListMerchantPayProductIdsReq, opts ...grpc.CallOption) (*ListMerchantPayProductIdsResp, error)
	ListMerchantPayoutProductIds(ctx context.Context, in *ListMerchantPayoutProductIdsReq, opts ...grpc.CallOption) (*ListMerchantPayoutProductIdsResp, error)
}

type merchantClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantClient(cc grpc.ClientConnInterface) MerchantClient {
	return &merchantClient{cc}
}

func (c *merchantClient) GetMerchant(ctx context.Context, in *GetMerchantReq, opts ...grpc.CallOption) (*GetMerchantResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMerchantResp)
	err := c.cc.Invoke(ctx, Merchant_GetMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantClient) GetAuthInfo(ctx context.Context, in *GetAuthInfoReq, opts ...grpc.CallOption) (*GetAuthInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthInfoResp)
	err := c.cc.Invoke(ctx, Merchant_GetAuthInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantClient) ListMerchants(ctx context.Context, in *ListMerchantsReq, opts ...grpc.CallOption) (*ListMerchantsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMerchantsResp)
	err := c.cc.Invoke(ctx, Merchant_ListMerchants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantClient) CreateMerchant(ctx context.Context, in *CreateMerchantReq, opts ...grpc.CallOption) (*UpsertMerchantResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertMerchantResp)
	err := c.cc.Invoke(ctx, Merchant_CreateMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantClient) UpdateMerchant(ctx context.Context, in *UpdateMerchantReq, opts ...grpc.CallOption) (*UpsertMerchantResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertMerchantResp)
	err := c.cc.Invoke(ctx, Merchant_UpdateMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantClient) ReplaceMerchantPayProducts(ctx context.Context, in *ReplaceMerchantPayProductsReq, opts ...grpc.CallOption) (*ReplaceMerchantPayProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplaceMerchantPayProductsResp)
	err := c.cc.Invoke(ctx, Merchant_ReplaceMerchantPayProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantClient) ReplaceMerchantPayoutProducts(ctx context.Context, in *ReplaceMerchantPayoutProductsReq, opts ...grpc.CallOption) (*ReplaceMerchantPayoutProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplaceMerchantPayoutProductsResp)
	err := c.cc.Invoke(ctx, Merchant_ReplaceMerchantPayoutProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantClient) ListMerchantPayProductIds(ctx context.Context, in *ListMerchantPayProductIdsReq, opts ...grpc.CallOption) (*ListMerchantPayProductIdsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMerchantPayProductIdsResp)
	err := c.cc.Invoke(ctx, Merchant_ListMerchantPayProductIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantClient) ListMerchantPayoutProductIds(ctx context.Context, in *ListMerchantPayoutProductIdsReq, opts ...grpc.CallOption) (*ListMerchantPayoutProductIdsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMerchantPayoutProductIdsResp)
	err := c.cc.Invoke(ctx, Merchant_ListMerchantPayoutProductIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantServer is the server API for Merchant service.
// All implementations must embed UnimplementedMerchantServer
// for forward compatibility.
type MerchantServer interface {
	GetMerchant(context.Context, *GetMerchantReq) (*GetMerchantResp, error)
	GetAuthInfo(context.Context, *GetAuthInfoReq) (*GetAuthInfoResp, error)
	ListMerchants(context.Context, *ListMerchantsReq) (*ListMerchantsResp, error)
	CreateMerchant(context.Context, *CreateMerchantReq) (*UpsertMerchantResp, error)
	UpdateMerchant(context.Context, *UpdateMerchantReq) (*UpsertMerchantResp, error)
	ReplaceMerchantPayProducts(context.Context, *ReplaceMerchantPayProductsReq) (*ReplaceMerchantPayProductsResp, error)
	ReplaceMerchantPayoutProducts(context.Context, *ReplaceMerchantPayoutProductsReq) (*ReplaceMerchantPayoutProductsResp, error)
	ListMerchantPayProductIds(context.Context, *ListMerchantPayProductIdsReq) (*ListMerchantPayProductIdsResp, error)
	ListMerchantPayoutProductIds(context.Context, *ListMerchantPayoutProductIdsReq) (*ListMerchantPayoutProductIdsResp, error)
	mustEmbedUnimplementedMerchantServer()
}

// UnimplementedMerchantServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantServer struct{}

func (UnimplementedMerchantServer) GetMerchant(context.Context, *GetMerchantReq) (*GetMerchantResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerchant not implemented")
}
func (UnimplementedMerchantServer) GetAuthInfo(context.Context, *GetAuthInfoReq) (*GetAuthInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthInfo not implemented")
}
func (UnimplementedMerchantServer) ListMerchants(context.Context, *ListMerchantsReq) (*ListMerchantsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMerchants not implemented")
}
func (UnimplementedMerchantServer) CreateMerchant(context.Context, *CreateMerchantReq) (*UpsertMerchantResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMerchant not implemented")
}
func (UnimplementedMerchantServer) UpdateMerchant(context.Context, *UpdateMerchantReq) (*UpsertMerchantResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMerchant not implemented")
}
func (UnimplementedMerchantServer) ReplaceMerchantPayProducts(context.Context, *ReplaceMerchantPayProductsReq) (*ReplaceMerchantPayProductsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceMerchantPayProducts not implemented")
}
func (UnimplementedMerchantServer) ReplaceMerchantPayoutProducts(context.Context, *ReplaceMerchantPayoutProductsReq) (*ReplaceMerchantPayoutProductsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceMerchantPayoutProducts not implemented")
}
func (UnimplementedMerchantServer) ListMerchantPayProductIds(context.Context, *ListMerchantPayProductIdsReq) (*ListMerchantPayProductIdsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMerchantPayProductIds not implemented")
}
func (UnimplementedMerchantServer) ListMerchantPayoutProductIds(context.Context, *ListMerchantPayoutProductIdsReq) (*ListMerchantPayoutProductIdsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMerchantPayoutProductIds not implemented")
}
func (UnimplementedMerchantServer) mustEmbedUnimplementedMerchantServer() {}
func (UnimplementedMerchantServer) testEmbeddedByValue()                  {}

// UnsafeMerchantServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantServer will
// result in compilation errors.
type UnsafeMerchantServer interface {
	mustEmbedUnimplementedMerchantServer()
}

func RegisterMerchantServer(s grpc.ServiceRegistrar, srv MerchantServer) {
	// If the following call pancis, it indicates UnimplementedMerchantServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Merchant_ServiceDesc, srv)
}

func _Merchant_GetMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).GetMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Merchant_GetMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).GetMerchant(ctx, req.(*GetMerchantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchant_GetAuthInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).GetAuthInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Merchant_GetAuthInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).GetAuthInfo(ctx, req.(*GetAuthInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchant_ListMerchants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMerchantsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).ListMerchants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Merchant_ListMerchants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).ListMerchants(ctx, req.(*ListMerchantsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchant_CreateMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMerchantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).CreateMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Merchant_CreateMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).CreateMerchant(ctx, req.(*CreateMerchantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchant_UpdateMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMerchantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).UpdateMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Merchant_UpdateMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).UpdateMerchant(ctx, req.(*UpdateMerchantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchant_ReplaceMerchantPayProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceMerchantPayProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).ReplaceMerchantPayProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Merchant_ReplaceMerchantPayProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).ReplaceMerchantPayProducts(ctx, req.(*ReplaceMerchantPayProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchant_ReplaceMerchantPayoutProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceMerchantPayoutProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).ReplaceMerchantPayoutProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Merchant_ReplaceMerchantPayoutProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).ReplaceMerchantPayoutProducts(ctx, req.(*ReplaceMerchantPayoutProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchant_ListMerchantPayProductIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMerchantPayProductIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).ListMerchantPayProductIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Merchant_ListMerchantPayProductIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).ListMerchantPayProductIds(ctx, req.(*ListMerchantPayProductIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchant_ListMerchantPayoutProductIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMerchantPayoutProductIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).ListMerchantPayoutProductIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Merchant_ListMerchantPayoutProductIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).ListMerchantPayoutProductIds(ctx, req.(*ListMerchantPayoutProductIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Merchant_ServiceDesc is the grpc.ServiceDesc for Merchant service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Merchant_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "merchant.Merchant",
	HandlerType: (*MerchantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMerchant",
			Handler:    _Merchant_GetMerchant_Handler,
		},
		{
			MethodName: "GetAuthInfo",
			Handler:    _Merchant_GetAuthInfo_Handler,
		},
		{
			MethodName: "ListMerchants",
			Handler:    _Merchant_ListMerchants_Handler,
		},
		{
			MethodName: "CreateMerchant",
			Handler:    _Merchant_CreateMerchant_Handler,
		},
		{
			MethodName: "UpdateMerchant",
			Handler:    _Merchant_UpdateMerchant_Handler,
		},
		{
			MethodName: "ReplaceMerchantPayProducts",
			Handler:    _Merchant_ReplaceMerchantPayProducts_Handler,
		},
		{
			MethodName: "ReplaceMerchantPayoutProducts",
			Handler:    _Merchant_ReplaceMerchantPayoutProducts_Handler,
		},
		{
			MethodName: "ListMerchantPayProductIds",
			Handler:    _Merchant_ListMerchantPayProductIds_Handler,
		},
		{
			MethodName: "ListMerchantPayoutProductIds",
			Handler:    _Merchant_ListMerchantPayoutProductIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant.proto",
}
