// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: merchant.proto

package merchant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantCollectGrant struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PayProductId    int64                  `protobuf:"varint,1,opt,name=pay_product_id,json=payProductId,proto3" json:"pay_product_id,omitempty"`
	MerchantRateBps *int64                 `protobuf:"varint,2,opt,name=merchant_rate_bps,json=merchantRateBps,proto3,oneof" json:"merchant_rate_bps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MerchantCollectGrant) Reset() {
	*x = MerchantCollectGrant{}
	mi := &file_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantCollectGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantCollectGrant) ProtoMessage() {}

func (x *MerchantCollectGrant) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantCollectGrant.ProtoReflect.Descriptor instead.
func (*MerchantCollectGrant) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantCollectGrant) GetPayProductId() int64 {
	if x != nil {
		return x.PayProductId
	}
	return 0
}

func (x *MerchantCollectGrant) GetMerchantRateBps() int64 {
	if x != nil && x.MerchantRateBps != nil {
		return *x.MerchantRateBps
	}
	return 0
}

type MerchantPayoutGrant struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PayoutProductId int64                  `protobuf:"varint,1,opt,name=payout_product_id,json=payoutProductId,proto3" json:"payout_product_id,omitempty"`
	MerchantRateBps *int64                 `protobuf:"varint,2,opt,name=merchant_rate_bps,json=merchantRateBps,proto3,oneof" json:"merchant_rate_bps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MerchantPayoutGrant) Reset() {
	*x = MerchantPayoutGrant{}
	mi := &file_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantPayoutGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantPayoutGrant) ProtoMessage() {}

func (x *MerchantPayoutGrant) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantPayoutGrant.ProtoReflect.Descriptor instead.
func (*MerchantPayoutGrant) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *MerchantPayoutGrant) GetPayoutProductId() int64 {
	if x != nil {
		return x.PayoutProductId
	}
	return 0
}

func (x *MerchantPayoutGrant) GetMerchantRateBps() int64 {
	if x != nil && x.MerchantRateBps != nil {
		return *x.MerchantRateBps
	}
	return 0
}

type MerchantInfo struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	MerchantId            string                  `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	ApiSecret             string                  `protobuf:"bytes,2,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	Status                int64                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	DefaultCollectRateBps int64                   `protobuf:"varint,4,opt,name=default_collect_rate_bps,json=defaultCollectRateBps,proto3" json:"default_collect_rate_bps,omitempty"`
	DefaultPayoutRateBps  int64                   `protobuf:"varint,5,opt,name=default_payout_rate_bps,json=defaultPayoutRateBps,proto3" json:"default_payout_rate_bps,omitempty"`
	IpWhitelist           string                  `protobuf:"bytes,6,opt,name=ip_whitelist,json=ipWhitelist,proto3" json:"ip_whitelist,omitempty"`
	Balance               int64                   `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	FrozenBalance         int64                   `protobuf:"varint,8,opt,name=frozen_balance,json=frozenBalance,proto3" json:"frozen_balance,omitempty"`
	WithdrawnAmount       int64                   `protobuf:"varint,9,opt,name=withdrawn_amount,json=withdrawnAmount,proto3" json:"withdrawn_amount,omitempty"`
	NotifyUrl             string                  `protobuf:"bytes,10,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	ReturnUrl             string                  `protobuf:"bytes,11,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	PayProductIds         []int64                 `protobuf:"varint,12,rep,packed,name=pay_product_ids,json=payProductIds,proto3" json:"pay_product_ids,omitempty"`
	PayoutProductIds      []int64                 `protobuf:"varint,13,rep,packed,name=payout_product_ids,json=payoutProductIds,proto3" json:"payout_product_ids,omitempty"`
	CollectGrants         []*MerchantCollectGrant `protobuf:"bytes,14,rep,name=collect_grants,json=collectGrants,proto3" json:"collect_grants,omitempty"`
	PayoutGrants          []*MerchantPayoutGrant  `protobuf:"bytes,15,rep,name=payout_grants,json=payoutGrants,proto3" json:"payout_grants,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MerchantInfo) Reset() {
	*x = MerchantInfo{}
	mi := &file_merchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantInfo) ProtoMessage() {}

func (x *MerchantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantInfo.ProtoReflect.Descriptor instead.
func (*MerchantInfo) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{2}
}

func (x *MerchantInfo) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *MerchantInfo) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

func (x *MerchantInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MerchantInfo) GetDefaultCollectRateBps() int64 {
	if x != nil {
		return x.DefaultCollectRateBps
	}
	return 0
}

func (x *MerchantInfo) GetDefaultPayoutRateBps() int64 {
	if x != nil {
		return x.DefaultPayoutRateBps
	}
	return 0
}

func (x *MerchantInfo) GetIpWhitelist() string {
	if x != nil {
		return x.IpWhitelist
	}
	return ""
}

func (x *MerchantInfo) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *MerchantInfo) GetFrozenBalance() int64 {
	if x != nil {
		return x.FrozenBalance
	}
	return 0
}

func (x *MerchantInfo) GetWithdrawnAmount() int64 {
	if x != nil {
		return x.WithdrawnAmount
	}
	return 0
}

func (x *MerchantInfo) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *MerchantInfo) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *MerchantInfo) GetPayProductIds() []int64 {
	if x != nil {
		return x.PayProductIds
	}
	return nil
}

func (x *MerchantInfo) GetPayoutProductIds() []int64 {
	if x != nil {
		return x.PayoutProductIds
	}
	return nil
}

func (x *MerchantInfo) GetCollectGrants() []*MerchantCollectGrant {
	if x != nil {
		return x.CollectGrants
	}
	return nil
}

func (x *MerchantInfo) GetPayoutGrants() []*MerchantPayoutGrant {
	if x != nil {
		return x.PayoutGrants
	}
	return nil
}

type GetMerchantReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantReq) Reset() {
	*x = GetMerchantReq{}
	mi := &file_merchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantReq) ProtoMessage() {}

func (x *GetMerchantReq) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantReq.ProtoReflect.Descriptor instead.
func (*GetMerchantReq) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{3}
}

func (x *GetMerchantReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetMerchantResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *MerchantInfo          `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantResp) Reset() {
	*x = GetMerchantResp{}
	mi := &file_merchant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantResp) ProtoMessage() {}

func (x *GetMerchantResp) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantResp.ProtoReflect.Descriptor instead.
func (*GetMerchantResp) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{4}
}

func (x *GetMerchantResp) GetMerchant() *MerchantInfo {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type GetAuthInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthInfoReq) Reset() {
	*x = GetAuthInfoReq{}
	mi := &file_merchant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthInfoReq) ProtoMessage() {}

func (x *GetAuthInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthInfoReq.ProtoReflect.Descriptor instead.
func (*GetAuthInfoReq) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuthInfoReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetAuthInfoResp struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ApiSecret             string                 `protobuf:"bytes,1,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	Status                int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	IpWhitelist           string                 `protobuf:"bytes,3,opt,name=ip_whitelist,json=ipWhitelist,proto3" json:"ip_whitelist,omitempty"`
	NotifyUrl             string                 `protobuf:"bytes,4,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	ReturnUrl             string                 `protobuf:"bytes,5,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	Balance               int64                  `protobuf:"varint,6,opt,name=balance,proto3" json:"balance,omitempty"`
	DefaultCollectRateBps int64                  `protobuf:"varint,7,opt,name=default_collect_rate_bps,json=defaultCollectRateBps,proto3" json:"default_collect_rate_bps,omitempty"`
	DefaultPayoutRateBps  int64                  `protobuf:"varint,8,opt,name=default_payout_rate_bps,json=defaultPayoutRateBps,proto3" json:"default_payout_rate_bps,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetAuthInfoResp) Reset() {
	*x = GetAuthInfoResp{}
	mi := &file_merchant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthInfoResp) ProtoMessage() {}

func (x *GetAuthInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthInfoResp.ProtoReflect.Descriptor instead.
func (*GetAuthInfoResp) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuthInfoResp) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

func (x *GetAuthInfoResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetAuthInfoResp) GetIpWhitelist() string {
	if x != nil {
		return x.IpWhitelist
	}
	return ""
}

func (x *GetAuthInfoResp) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *GetAuthInfoResp) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *GetAuthInfoResp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetAuthInfoResp) GetDefaultCollectRateBps() int64 {
	if x != nil {
		return x.DefaultCollectRateBps
	}
	return 0
}

func (x *GetAuthInfoResp) GetDefaultPayoutRateBps() int64 {
	if x != nil {
		return x.DefaultPayoutRateBps
	}
	return 0
}

type ListMerchantsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsReq) Reset() {
	*x = ListMerchantsReq{}
	mi := &file_merchant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsReq) ProtoMessage() {}

func (x *ListMerchantsReq) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsReq.ProtoReflect.Descriptor instead.
func (*ListMerchantsReq) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{7}
}

func (x *ListMerchantsReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMerchantsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchants     []*MerchantInfo        `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsResp) Reset() {
	*x = ListMerchantsResp{}
	mi := &file_merchant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsResp) ProtoMessage() {}

func (x *ListMerchantsResp) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsResp.ProtoReflect.Descriptor instead.
func (*ListMerchantsResp) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{8}
}

func (x *ListMerchantsResp) GetMerchants() []*MerchantInfo {
	if x != nil {
		return x.Merchants
	}
	return nil
}

type CreateMerchantReq struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MerchantId            string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	ApiSecret             string                 `protobuf:"bytes,2,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	Status                int64                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	DefaultCollectRateBps int64                  `protobuf:"varint,4,opt,name=default_collect_rate_bps,json=defaultCollectRateBps,proto3" json:"default_collect_rate_bps,omitempty"`
	DefaultPayoutRateBps  int64                  `protobuf:"varint,5,opt,name=default_payout_rate_bps,json=defaultPayoutRateBps,proto3" json:"default_payout_rate_bps,omitempty"`
	NotifyUrl             string                 `protobuf:"bytes,6,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	ReturnUrl             string                 `protobuf:"bytes,7,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	IpWhitelist           string                 `protobuf:"bytes,8,opt,name=ip_whitelist,json=ipWhitelist,proto3" json:"ip_whitelist,omitempty"`
	PayProductIds         []int64                `protobuf:"varint,9,rep,packed,name=pay_product_ids,json=payProductIds,proto3" json:"pay_product_ids,omitempty"`
	PayoutProductIds      []int64                `protobuf:"varint,10,rep,packed,name=payout_product_ids,json=payoutProductIds,proto3" json:"payout_product_ids,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateMerchantReq) Reset() {
	*x = CreateMerchantReq{}
	mi := &file_merchant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantReq) ProtoMessage() {}

func (x *CreateMerchantReq) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantReq.ProtoReflect.Descriptor instead.
func (*CreateMerchantReq) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{9}
}

func (x *CreateMerchantReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateMerchantReq) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

func (x *CreateMerchantReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateMerchantReq) GetDefaultCollectRateBps() int64 {
	if x != nil {
		return x.DefaultCollectRateBps
	}
	return 0
}

func (x *CreateMerchantReq) GetDefaultPayoutRateBps() int64 {
	if x != nil {
		return x.DefaultPayoutRateBps
	}
	return 0
}

func (x *CreateMerchantReq) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *CreateMerchantReq) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *CreateMerchantReq) GetIpWhitelist() string {
	if x != nil {
		return x.IpWhitelist
	}
	return ""
}

func (x *CreateMerchantReq) GetPayProductIds() []int64 {
	if x != nil {
		return x.PayProductIds
	}
	return nil
}

func (x *CreateMerchantReq) GetPayoutProductIds() []int64 {
	if x != nil {
		return x.PayoutProductIds
	}
	return nil
}

type UpdateMerchantReq struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MerchantId            string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	ApiSecret             string                 `protobuf:"bytes,2,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	Status                int64                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	DefaultCollectRateBps int64                  `protobuf:"varint,4,opt,name=default_collect_rate_bps,json=defaultCollectRateBps,proto3" json:"default_collect_rate_bps,omitempty"`
	DefaultPayoutRateBps  int64                  `protobuf:"varint,5,opt,name=default_payout_rate_bps,json=defaultPayoutRateBps,proto3" json:"default_payout_rate_bps,omitempty"`
	NotifyUrl             string                 `protobuf:"bytes,6,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	ReturnUrl             string                 `protobuf:"bytes,7,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	IpWhitelist           string                 `protobuf:"bytes,8,opt,name=ip_whitelist,json=ipWhitelist,proto3" json:"ip_whitelist,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateMerchantReq) Reset() {
	*x = UpdateMerchantReq{}
	mi := &file_merchant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantReq) ProtoMessage() {}

func (x *UpdateMerchantReq) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantReq.ProtoReflect.Descriptor instead.
func (*UpdateMerchantReq) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMerchantReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdateMerchantReq) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

func (x *UpdateMerchantReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateMerchantReq) GetDefaultCollectRateBps() int64 {
	if x != nil {
		return x.DefaultCollectRateBps
	}
	return 0
}

func (x *UpdateMerchantReq) GetDefaultPayoutRateBps() int64 {
	if x != nil {
		return x.DefaultPayoutRateBps
	}
	return 0
}

func (x *UpdateMerchantReq) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *UpdateMerchantReq) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *UpdateMerchantReq) GetIpWhitelist() string {
	if x != nil {
		return x.IpWhitelist
	}
	return ""
}

type UpsertMerchantResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *MerchantInfo          `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertMerchantResp) Reset() {
	*x = UpsertMerchantResp{}
	mi := &file_merchant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertMerchantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMerchantResp) ProtoMessage() {}

func (x *UpsertMerchantResp) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMerchantResp.ProtoReflect.Descriptor instead.
func (*UpsertMerchantResp) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{11}
}

func (x *UpsertMerchantResp) GetMerchant() *MerchantInfo {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type ReplaceMerchantPayProductsReq struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	MerchantId    string                  `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Grants        []*MerchantCollectGrant `protobuf:"bytes,2,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceMerchantPayProductsReq) Reset() {
	*x = ReplaceMerchantPayProductsReq{}
	mi := &file_merchant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceMerchantPayProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceMerchantPayProductsReq) ProtoMessage() {}

func (x *ReplaceMerchantPayProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceMerchantPayProductsReq.ProtoReflect.Descriptor instead.
func (*ReplaceMerchantPayProductsReq) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{12}
}

func (x *ReplaceMerchantPayProductsReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ReplaceMerchantPayProductsReq) GetGrants() []*MerchantCollectGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

type ReplaceMerchantPayProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceMerchantPayProductsResp) Reset() {
	*x = ReplaceMerchantPayProductsResp{}
	mi := &file_merchant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceMerchantPayProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceMerchantPayProductsResp) ProtoMessage() {}

func (x *ReplaceMerchantPayProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceMerchantPayProductsResp.ProtoReflect.Descriptor instead.
func (*ReplaceMerchantPayProductsResp) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{13}
}

func (x *ReplaceMerchantPayProductsResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ReplaceMerchantPayoutProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Grants        []*MerchantPayoutGrant `protobuf:"bytes,2,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceMerchantPayoutProductsReq) Reset() {
	*x = ReplaceMerchantPayoutProductsReq{}
	mi := &file_merchant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceMerchantPayoutProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceMerchantPayoutProductsReq) ProtoMessage() {}

func (x *ReplaceMerchantPayoutProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceMerchantPayoutProductsReq.ProtoReflect.Descriptor instead.
func (*ReplaceMerchantPayoutProductsReq) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{14}
}

func (x *ReplaceMerchantPayoutProductsReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ReplaceMerchantPayoutProductsReq) GetGrants() []*MerchantPayoutGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

type ReplaceMerchantPayoutProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceMerchantPayoutProductsResp) Reset() {
	*x = ReplaceMerchantPayoutProductsResp{}
	mi := &file_merchant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceMerchantPayoutProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceMerchantPayoutProductsResp) ProtoMessage() {}

func (x *ReplaceMerchantPayoutProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceMerchantPayoutProductsResp.ProtoReflect.Descriptor instead.
func (*ReplaceMerchantPayoutProductsResp) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{15}
}

func (x *ReplaceMerchantPayoutProductsResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListMerchantPayProductIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantPayProductIdsReq) Reset() {
	*x = ListMerchantPayProductIdsReq{}
	mi := &file_merchant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantPayProductIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantPayProductIdsReq) ProtoMessage() {}

func (x *ListMerchantPayProductIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantPayProductIdsReq.ProtoReflect.Descriptor instead.
func (*ListMerchantPayProductIdsReq) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{16}
}

func (x *ListMerchantPayProductIdsReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type ListMerchantPayProductIdsResp struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Grants        []*MerchantCollectGrant `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantPayProductIdsResp) Reset() {
	*x = ListMerchantPayProductIdsResp{}
	mi := &file_merchant_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantPayProductIdsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantPayProductIdsResp) ProtoMessage() {}

func (x *ListMerchantPayProductIdsResp) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantPayProductIdsResp.ProtoReflect.Descriptor instead.
func (*ListMerchantPayProductIdsResp) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{17}
}

func (x *ListMerchantPayProductIdsResp) GetGrants() []*MerchantCollectGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

type ListMerchantPayoutProductIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantPayoutProductIdsReq) Reset() {
	*x = ListMerchantPayoutProductIdsReq{}
	mi := &file_merchant_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantPayoutProductIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantPayoutProductIdsReq) ProtoMessage() {}

func (x *ListMerchantPayoutProductIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantPayoutProductIdsReq.ProtoReflect.Descriptor instead.
func (*ListMerchantPayoutProductIdsReq) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{18}
}

func (x *ListMerchantPayoutProductIdsReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type ListMerchantPayoutProductIdsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grants        []*MerchantPayoutGrant `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantPayoutProductIdsResp) Reset() {
	*x = ListMerchantPayoutProductIdsResp{}
	mi := &file_merchant_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantPayoutProductIdsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantPayoutProductIdsResp) ProtoMessage() {}

func (x *ListMerchantPayoutProductIdsResp) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantPayoutProductIdsResp.ProtoReflect.Descriptor instead.
func (*ListMerchantPayoutProductIdsResp) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{19}
}

func (x *ListMerchantPayoutProductIdsResp) GetGrants() []*MerchantPayoutGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

var File_merchant_proto protoreflect.FileDescriptor

const file_merchant_proto_rawDesc = "" +
	"\n" +
	"\x0emerchant.proto\x12\bmerchant\"\x83\x01\n" +
	"\x14MerchantCollectGrant\x12$\n" +
	"\x0epay_product_id\x18\x01 \x01(\x03R\fpayProductId\x12/\n" +
	"\x11merchant_rate_bps\x18\x02 \x01(\x03H\x00R\x0fmerchantRateBps\x88\x01\x01B\x14\n" +
	"\x12_merchant_rate_bps\"\x88\x01\n" +
	"\x13MerchantPayoutGrant\x12*\n" +
	"\x11payout_product_id\x18\x01 \x01(\x03R\x0fpayoutProductId\x12/\n" +
	"\x11merchant_rate_bps\x18\x02 \x01(\x03H\x00R\x0fmerchantRateBps\x88\x01\x01B\x14\n" +
	"\x12_merchant_rate_bps\"\x84\x05\n" +
	"\fMerchantInfo\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x02 \x01(\tR\tapiSecret\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\x127\n" +
	"\x18default_collect_rate_bps\x18\x04 \x01(\x03R\x15defaultCollectRateBps\x125\n" +
	"\x17default_payout_rate_bps\x18\x05 \x01(\x03R\x14defaultPayoutRateBps\x12!\n" +
	"\fip_whitelist\x18\x06 \x01(\tR\vipWhitelist\x12\x18\n" +
	"\abalance\x18\a \x01(\x03R\abalance\x12%\n" +
	"\x0efrozen_balance\x18\b \x01(\x03R\rfrozenBalance\x12)\n" +
	"\x10withdrawn_amount\x18\t \x01(\x03R\x0fwithdrawnAmount\x12\x1d\n" +
	"\n" +
	"notify_url\x18\n" +
	" \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"return_url\x18\v \x01(\tR\treturnUrl\x12&\n" +
	"\x0fpay_product_ids\x18\f \x03(\x03R\rpayProductIds\x12,\n" +
	"\x12payout_product_ids\x18\r \x03(\x03R\x10payoutProductIds\x12E\n" +
	"\x0ecollect_grants\x18\x0e \x03(\v2\x1e.merchant.MerchantCollectGrantR\rcollectGrants\x12B\n" +
	"\rpayout_grants\x18\x0f \x03(\v2\x1d.merchant.MerchantPayoutGrantR\fpayoutGrants\"1\n" +
	"\x0eGetMerchantReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"E\n" +
	"\x0fGetMerchantResp\x122\n" +
	"\bmerchant\x18\x01 \x01(\v2\x16.merchant.MerchantInfoR\bmerchant\"1\n" +
	"\x0eGetAuthInfoReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"\xb3\x02\n" +
	"\x0fGetAuthInfoResp\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x01 \x01(\tR\tapiSecret\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12!\n" +
	"\fip_whitelist\x18\x03 \x01(\tR\vipWhitelist\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x04 \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"return_url\x18\x05 \x01(\tR\treturnUrl\x12\x18\n" +
	"\abalance\x18\x06 \x01(\x03R\abalance\x127\n" +
	"\x18default_collect_rate_bps\x18\a \x01(\x03R\x15defaultCollectRateBps\x125\n" +
	"\x17default_payout_rate_bps\x18\b \x01(\x03R\x14defaultPayoutRateBps\"(\n" +
	"\x10ListMerchantsReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\"I\n" +
	"\x11ListMerchantsResp\x124\n" +
	"\tmerchants\x18\x01 \x03(\v2\x16.merchant.MerchantInfoR\tmerchants\"\x92\x03\n" +
	"\x11CreateMerchantReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x02 \x01(\tR\tapiSecret\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\x127\n" +
	"\x18default_collect_rate_bps\x18\x04 \x01(\x03R\x15defaultCollectRateBps\x125\n" +
	"\x17default_payout_rate_bps\x18\x05 \x01(\x03R\x14defaultPayoutRateBps\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x06 \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"return_url\x18\a \x01(\tR\treturnUrl\x12!\n" +
	"\fip_whitelist\x18\b \x01(\tR\vipWhitelist\x12&\n" +
	"\x0fpay_product_ids\x18\t \x03(\x03R\rpayProductIds\x12,\n" +
	"\x12payout_product_ids\x18\n" +
	" \x03(\x03R\x10payoutProductIds\"\xbc\x02\n" +
	"\x11UpdateMerchantReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x02 \x01(\tR\tapiSecret\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\x127\n" +
	"\x18default_collect_rate_bps\x18\x04 \x01(\x03R\x15defaultCollectRateBps\x125\n" +
	"\x17default_payout_rate_bps\x18\x05 \x01(\x03R\x14defaultPayoutRateBps\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x06 \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"return_url\x18\a \x01(\tR\treturnUrl\x12!\n" +
	"\fip_whitelist\x18\b \x01(\tR\vipWhitelist\"H\n" +
	"\x12UpsertMerchantResp\x122\n" +
	"\bmerchant\x18\x01 \x01(\v2\x16.merchant.MerchantInfoR\bmerchant\"x\n" +
	"\x1dReplaceMerchantPayProductsReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x126\n" +
	"\x06grants\x18\x02 \x03(\v2\x1e.merchant.MerchantCollectGrantR\x06grants\"0\n" +
	"\x1eReplaceMerchantPayProductsResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"z\n" +
	" ReplaceMerchantPayoutProductsReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x125\n" +
	"\x06grants\x18\x02 \x03(\v2\x1d.merchant.MerchantPayoutGrantR\x06grants\"3\n" +
	"!ReplaceMerchantPayoutProductsResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"?\n" +
	"\x1cListMerchantPayProductIdsReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"W\n" +
	"\x1dListMerchantPayProductIdsResp\x126\n" +
	"\x06grants\x18\x01 \x03(\v2\x1e.merchant.MerchantCollectGrantR\x06grants\"B\n" +
	"\x1fListMerchantPayoutProductIdsReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"Y\n" +
	" ListMerchantPayoutProductIdsResp\x125\n" +
	"\x06grants\x18\x01 \x03(\v2\x1d.merchant.MerchantPayoutGrantR\x06grants2\xc6\x06\n" +
	"\bMerchant\x12B\n" +
	"\vGetMerchant\x12\x18.merchant.GetMerchantReq\x1a\x19.merchant.GetMerchantResp\x12B\n" +
	"\vGetAuthInfo\x12\x18.merchant.GetAuthInfoReq\x1a\x19.merchant.GetAuthInfoResp\x12H\n" +
	"\rListMerchants\x12\x1a.merchant.ListMerchantsReq\x1a\x1b.merchant.ListMerchantsResp\x12K\n" +
	"\x0eCreateMerchant\x12\x1b.merchant.CreateMerchantReq\x1a\x1c.merchant.UpsertMerchantResp\x12K\n" +
	"\x0eUpdateMerchant\x12\x1b.merchant.UpdateMerchantReq\x1a\x1c.merchant.UpsertMerchantResp\x12o\n" +
	"\x1aReplaceMerchantPayProducts\x12'.merchant.ReplaceMerchantPayProductsReq\x1a(.merchant.ReplaceMerchantPayProductsResp\x12x\n" +
	"\x1dReplaceMerchantPayoutProducts\x12*.merchant.ReplaceMerchantPayoutProductsReq\x1a+.merchant.ReplaceMerchantPayoutProductsResp\x12l\n" +
	"\x19ListMerchantPayProductIds\x12&.merchant.ListMerchantPayProductIdsReq\x1a'.merchant.ListMerchantPayProductIdsResp\x12u\n" +
	"\x1cListMerchantPayoutProductIds\x12).merchant.ListMerchantPayoutProductIdsReq\x1a*.merchant.ListMerchantPayoutProductIdsRespB4Z2github.com/gloopai/pay/common/pb/merchant;merchantb\x06proto3"

var (
	file_merchant_proto_rawDescOnce sync.Once
	file_merchant_proto_rawDescData []byte
)

func file_merchant_proto_rawDescGZIP() []byte {
	file_merchant_proto_rawDescOnce.Do(func() {
		file_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_proto_rawDesc), len(file_merchant_proto_rawDesc)))
	})
	return file_merchant_proto_rawDescData
}

var file_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_merchant_proto_goTypes = []any{
	(*MerchantCollectGrant)(nil),              // 0: merchant.MerchantCollectGrant
	(*MerchantPayoutGrant)(nil),               // 1: merchant.MerchantPayoutGrant
	(*MerchantInfo)(nil),                      // 2: merchant.MerchantInfo
	(*GetMerchantReq)(nil),                    // 3: merchant.GetMerchantReq
	(*GetMerchantResp)(nil),                   // 4: merchant.GetMerchantResp
	(*GetAuthInfoReq)(nil),                    // 5: merchant.GetAuthInfoReq
	(*GetAuthInfoResp)(nil),                   // 6: merchant.GetAuthInfoResp
	(*ListMerchantsReq)(nil),                  // 7: merchant.ListMerchantsReq
	(*ListMerchantsResp)(nil),                 // 8: merchant.ListMerchantsResp
	(*CreateMerchantReq)(nil),                 // 9: merchant.CreateMerchantReq
	(*UpdateMerchantReq)(nil),                 // 10: merchant.UpdateMerchantReq
	(*UpsertMerchantResp)(nil),                // 11: merchant.UpsertMerchantResp
	(*ReplaceMerchantPayProductsReq)(nil),     // 12: merchant.ReplaceMerchantPayProductsReq
	(*ReplaceMerchantPayProductsResp)(nil),    // 13: merchant.ReplaceMerchantPayProductsResp
	(*ReplaceMerchantPayoutProductsReq)(nil),  // 14: merchant.ReplaceMerchantPayoutProductsReq
	(*ReplaceMerchantPayoutProductsResp)(nil), // 15: merchant.ReplaceMerchantPayoutProductsResp
	(*ListMerchantPayProductIdsReq)(nil),      // 16: merchant.ListMerchantPayProductIdsReq
	(*ListMerchantPayProductIdsResp)(nil),     // 17: merchant.ListMerchantPayProductIdsResp
	(*ListMerchantPayoutProductIdsReq)(nil),   // 18: merchant.ListMerchantPayoutProductIdsReq
	(*ListMerchantPayoutProductIdsResp)(nil),  // 19: merchant.ListMerchantPayoutProductIdsResp
}
var file_merchant_proto_depIdxs = []int32{
	0,  // 0: merchant.MerchantInfo.collect_grants:type_name -> merchant.MerchantCollectGrant
	1,  // 1: merchant.MerchantInfo.payout_grants:type_name -> merchant.MerchantPayoutGrant
	2,  // 2: merchant.GetMerchantResp.merchant:type_name -> merchant.MerchantInfo
	2,  // 3: merchant.ListMerchantsResp.merchants:type_name -> merchant.MerchantInfo
	2,  // 4: merchant.UpsertMerchantResp.merchant:type_name -> merchant.MerchantInfo
	0,  // 5: merchant.ReplaceMerchantPayProductsReq.grants:type_name -> merchant.MerchantCollectGrant
	1,  // 6: merchant.ReplaceMerchantPayoutProductsReq.grants:type_name -> merchant.MerchantPayoutGrant
	0,  // 7: merchant.ListMerchantPayProductIdsResp.grants:type_name -> merchant.MerchantCollectGrant
	1,  // 8: merchant.ListMerchantPayoutProductIdsResp.grants:type_name -> merchant.MerchantPayoutGrant
	3,  // 9: merchant.Merchant.GetMerchant:input_type -> merchant.GetMerchantReq
	5,  // 10: merchant.Merchant.GetAuthInfo:input_type -> merchant.GetAuthInfoReq
	7,  // 11: merchant.Merchant.ListMerchants:input_type -> merchant.ListMerchantsReq
	9,  // 12: merchant.Merchant.CreateMerchant:input_type -> merchant.CreateMerchantReq
	10, // 13: merchant.Merchant.UpdateMerchant:input_type -> merchant.UpdateMerchantReq
	12, // 14: merchant.Merchant.ReplaceMerchantPayProducts:input_type -> merchant.ReplaceMerchantPayProductsReq
	14, // 15: merchant.Merchant.ReplaceMerchantPayoutProducts:input_type -> merchant.ReplaceMerchantPayoutProductsReq
	16, // 16: merchant.Merchant.ListMerchantPayProductIds:input_type -> merchant.ListMerchantPayProductIdsReq
	18, // 17: merchant.Merchant.ListMerchantPayoutProductIds:input_type -> merchant.ListMerchantPayoutProductIdsReq
	4,  // 18: merchant.Merchant.GetMerchant:output_type -> merchant.GetMerchantResp
	6,  // 19: merchant.Merchant.GetAuthInfo:output_type -> merchant.GetAuthInfoResp
	8,  // 20: merchant.Merchant.ListMerchants:output_type -> merchant.ListMerchantsResp
	11, // 21: merchant.Merchant.CreateMerchant:output_type -> merchant.UpsertMerchantResp
	11, // 22: merchant.Merchant.UpdateMerchant:output_type -> merchant.UpsertMerchantResp
	13, // 23: merchant.Merchant.ReplaceMerchantPayProducts:output_type -> merchant.ReplaceMerchantPayProductsResp
	15, // 24: merchant.Merchant.ReplaceMerchantPayoutProducts:output_type -> merchant.ReplaceMerchantPayoutProductsResp
	17, // 25: merchant.Merchant.ListMerchantPayProductIds:output_type -> merchant.ListMerchantPayProductIdsResp
	19, // 26: merchant.Merchant.ListMerchantPayoutProductIds:output_type -> merchant.ListMerchantPayoutProductIdsResp
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_merchant_proto_init() }
func file_merchant_proto_init() {
	if File_merchant_proto != nil {
		return
	}
	file_merchant_proto_msgTypes[0].OneofWrappers = []any{}
	file_merchant_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_proto_rawDesc), len(file_merchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_proto_goTypes,
		DependencyIndexes: file_merchant_proto_depIdxs,
		MessageInfos:      file_merchant_proto_msgTypes,
	}.Build()
	File_merchant_proto = out.File
	file_merchant_proto_goTypes = nil
	file_merchant_proto_depIdxs = nil
}
