// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateOrderReq struct {
	MerchantId      string `json:"merchant_id"`
	MerchantOrderNo string `json:"merchant_order_no"`
	Amount          int64  `json:"amount"`
	Currency        string `json:"currency,optional"`
	Subject         string `json:"subject,optional"`
	ReturnUrl       string `json:"return_url,optional"`
	NotifyUrl       string `json:"notify_url,optional"`
	PayType         string `json:"pay_type,optional"`
	ChannelId       int64  `json:"channel_id,optional"`
	Timestamp       int64  `json:"timestamp,optional"`
	Nonce           string `json:"nonce,optional"`
	Sign            string `json:"sign"`
}

type CreateOrderResp struct {
	OrderNo          string `json:"order_no"`
	Status           int32  `json:"status"`
	ChannelId        int64  `json:"channel_id"`
	PayProductId     int64  `json:"pay_product_id"`
	PayProductCode   string `json:"pay_product_code"`
	CheckoutUrl      string `json:"checkout_url"`
}

type OrderInfo struct {
	OrderNo          string `json:"order_no"`
	MerchantId       string `json:"merchant_id"`
	MerchantOrderNo  string `json:"merchant_order_no"`
	Amount           int64  `json:"amount"`
	Currency         string `json:"currency"`
	Status           int32  `json:"status"`
	ChannelId        int64  `json:"channel_id"`
	PayProductId     int64  `json:"pay_product_id"`
	PayProductCode   string `json:"pay_product_code"`
	ReturnUrl        string `json:"return_url"`
	NotifyUrl        string `json:"notify_url"`
	UpstreamTradeNo  string `json:"upstream_trade_no"`
}

type PayProductItem struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type QueryOrderReq struct {
	MerchantId      string `form:"merchant_id"`
	OrderNo         string `form:"order_no,optional"`
	MerchantOrderNo string `form:"merchant_order_no,optional"`
	Timestamp       int64  `form:"timestamp,optional"`
	Nonce           string `form:"nonce,optional"`
	Sign            string `form:"sign"`
}

type QueryOrderResp struct {
	Order OrderInfo `json:"order"`
}

type TerminalOrderReq struct {
	OrderNo string `form:"order_no"`
}

type TerminalOrderResp struct {
	Order        OrderInfo        `json:"order"`
	PayProducts  []PayProductItem `json:"pay_products"`
}

type UpstreamNotifyReq struct {
	OrderNo         string `json:"order_no"`
	PaidAmount      int64  `json:"paid_amount"`
	UpstreamTradeNo string `json:"upstream_trade_no"`
	ChannelId       int64  `json:"channel_id"`
	Sign            string `json:"sign"`
}

type UpstreamNotifyResp struct {
	Ok bool `json:"ok"`
}

type AdminChannelInfo struct {
	Id                 int64  `json:"id"`
	Name               string `json:"name"`
	PayType            string `json:"pay_type"`
	GatewayUrl         string `json:"gateway_url"`
	UpstreamMerchantNo string `json:"upstream_merchant_no"`
	RsaPrivateKey      string `json:"rsa_private_key"`
	SignSecret         string `json:"sign_secret"`
	Weight             int64  `json:"weight"`
	MinAmount          int64  `json:"min_amount"`
	MaxAmount          int64  `json:"max_amount"`
	Enabled            bool   `json:"enabled"`
	FuseEnabled        bool   `json:"fuse_enabled"`
}

type AdminListChannelsResp struct {
	Channels []AdminChannelInfo `json:"channels"`
}

type AdminUpsertChannelReq struct {
	Id                 int64  `path:"id,optional"`
	Name               string `json:"name"`
	PayType            string `json:"pay_type,optional"`
	GatewayUrl         string `json:"gateway_url,optional"`
	UpstreamMerchantNo string `json:"upstream_merchant_no,optional"`
	RsaPrivateKey      string `json:"rsa_private_key,optional"`
	SignSecret         string `json:"sign_secret,optional"`
	Weight             int64  `json:"weight"`
	MinAmount          int64  `json:"min_amount,optional"`
	MaxAmount          int64  `json:"max_amount,optional"`
	Enabled            bool   `json:"enabled,optional"`
	FuseEnabled        bool   `json:"fuse_enabled,optional"`
}

type AdminUpsertChannelResp struct {
	Channel AdminChannelInfo `json:"channel"`
}

type MerchantSummaryReq struct {
}

type MerchantSummaryResp struct {
	TodayAmount int64   `json:"today_amount"`
	TodayCount  int64   `json:"today_count"`
	SuccessRate float64 `json:"success_rate"`
	Balance     int64   `json:"balance"`
	MerchantId  string  `json:"merchant_id"`
	NotifyUrl   string  `json:"notify_url"`
	IpWhitelist string  `json:"ip_whitelist"`
}

type MerchantOrdersReq struct {
	OrderNo string `form:"order_no,optional"`
	Status  string `form:"status,optional"`
	Limit   int64  `form:"limit,optional"`
}

type MerchantOrderItem struct {
	OrderNo          string `json:"order_no"`
	MerchantOrderNo  string `json:"merchant_order_no"`
	Amount           int64  `json:"amount"`
	Currency         string `json:"currency"`
	Status           int32  `json:"status"`
	ChannelId        int64  `json:"channel_id"`
	PayProductCode   string `json:"pay_product_code"`
	PaidAmount       int64  `json:"paid_amount"`
	UpstreamTradeNo  string `json:"upstream_trade_no"`
	CreatedAt        int64  `json:"created_at"`
}

type MerchantOrdersResp struct {
	Orders []MerchantOrderItem `json:"orders"`
}

type MerchantFundLogsReq struct {
	Limit int64 `form:"limit,optional"`
}

type MerchantFundLogItem struct {
	Id            int64  `json:"id"`
	OrderNo       string `json:"order_no"`
	ChangeType    string `json:"change_type"`
	Amount        int64  `json:"amount"`
	BalanceBefore int64  `json:"balance_before"`
	BalanceAfter  int64  `json:"balance_after"`
	Reason        string `json:"reason"`
	CreatedAt     int64  `json:"created_at"`
}

type MerchantFundLogsResp struct {
	Logs []MerchantFundLogItem `json:"logs"`
}

type MerchantOrderDetailReq struct {
	OrderNo string `form:"order_no"`
}

type MerchantNotifyLogItem struct {
	Id           int64  `json:"id"`
	NotifyUrl    string `json:"notify_url"`
	Attempt      int64  `json:"attempt"`
	HttpStatus   int64  `json:"http_status"`
	ResponseBody string `json:"response_body"`
	ErrorMsg     string `json:"error_msg"`
	CreatedAt    int64  `json:"created_at"`
}

type MerchantOrderDetailResp struct {
	Order OrderInfo               `json:"order"`
	Logs  []MerchantNotifyLogItem `json:"logs"`
}

type MerchantRetryNotifyReq struct {
	OrderNo string `json:"order_no"`
}

type MerchantRetryNotifyResp struct {
	Ok bool `json:"ok"`
}

type AdminLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AdminLoginResp struct {
	Token     string `json:"token"`
	ExpiresAt int64  `json:"expires_at"`
}

type AdminLogoutResp struct {
	Ok bool `json:"ok"`
}

type MerchantLoginReq struct {
	MerchantId string `json:"merchant_id"`
	ApiSecret  string `json:"api_secret"`
}

type MerchantLoginResp struct {
	Token      string `json:"token"`
	ExpiresAt  int64  `json:"expires_at"`
	MerchantId string `json:"merchant_id"`
}

type MerchantLogoutResp struct {
	Ok bool `json:"ok"`
}

type AdminMerchantInfo struct {
	MerchantId  string `json:"merchant_id"`
	ApiSecret   string `json:"api_secret"`
	Status      int64  `json:"status"`
	RateBps     int64  `json:"rate_bps"`
	NotifyUrl   string `json:"notify_url"`
	ReturnUrl   string `json:"return_url"`
	IpWhitelist string `json:"ip_whitelist"`
	Balance     int64  `json:"balance"`
}

type AdminListMerchantsResp struct {
	Merchants []AdminMerchantInfo `json:"merchants"`
}

type AdminCreateMerchantReq struct {
	MerchantId  string `json:"merchant_id"`
	ApiSecret   string `json:"api_secret,optional"`
	RateBps     int64  `json:"rate_bps,optional"`
	NotifyUrl   string `json:"notify_url,optional"`
	ReturnUrl   string `json:"return_url,optional"`
	IpWhitelist string `json:"ip_whitelist,optional"`
}

type AdminUpdateMerchantReq struct {
	MerchantId  string `path:"merchant_id"`
	Status      int64  `json:"status,optional"`
	RateBps     int64  `json:"rate_bps,optional"`
	NotifyUrl   string `json:"notify_url,optional"`
	ReturnUrl   string `json:"return_url,optional"`
	IpWhitelist string `json:"ip_whitelist,optional"`
	ResetSecret bool   `json:"reset_secret,optional"`
}

type AdminUpsertMerchantResp struct {
	Merchant AdminMerchantInfo `json:"merchant"`
}

// --- 支付产品（对外 code）与上游通道绑定 ---

type AdminPayProductInfo struct {
	Id        int64  `json:"id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
	Enabled   bool   `json:"enabled"`
}

type AdminListPayProductsResp struct {
	Products []AdminPayProductInfo `json:"products"`
}

type AdminCreatePayProductReq struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order,optional"`
	Enabled   bool   `json:"enabled,optional"`
}

type AdminUpsertPayProductResp struct {
	Product AdminPayProductInfo `json:"product"`
}

type AdminUpdatePayProductReq struct {
	Id        int64  `path:"id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order,optional"`
	Enabled   bool   `json:"enabled,optional"`
}

type AdminPayProductBindingInfo struct {
	Id            int64  `json:"id"`
	PayProductId  int64  `json:"pay_product_id"`
	ChannelId     int64  `json:"channel_id"`
	ChannelName   string `json:"channel_name"`
	Weight        int64  `json:"weight"`
	Enabled       bool   `json:"enabled"`
}

type AdminListPayProductBindingsReq struct {
	Id int64 `path:"id"`
}

type AdminListPayProductBindingsResp struct {
	Bindings []AdminPayProductBindingInfo `json:"bindings"`
}

type AdminUpsertPayProductBindingReq struct {
	PayProductId int64 `path:"id"`
	ChannelId    int64 `json:"channel_id"`
	Weight       int64 `json:"weight"`
	Enabled      bool  `json:"enabled,optional"`
}

type AdminUpsertPayProductBindingResp struct {
	Binding AdminPayProductBindingInfo `json:"binding"`
}

type AdminUpdatePayProductBindingReq struct {
	Id      int64 `path:"id"`
	Weight  int64 `json:"weight"`
	Enabled bool  `json:"enabled,optional"`
}

type AdminUpdatePayProductBindingResp struct {
	Binding AdminPayProductBindingInfo `json:"binding"`
}

type AdminDeletePayProductBindingReq struct {
	Id int64 `path:"id"`
}

type AdminDeletePayProductBindingResp struct {
	Ok bool `json:"ok"`
}
