// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateOrderReq struct {
	MerchantId      string `json:"merchant_id"`
	MerchantOrderNo string `json:"merchant_order_no"`
	Amount          int64  `json:"amount"`
	Currency        string `json:"currency,optional"`
	Subject         string `json:"subject,optional"`
	ReturnUrl       string `json:"return_url,optional"`
	NotifyUrl       string `json:"notify_url,optional"`
	PayType         string `json:"pay_type,optional"`
	ChannelId       int64  `json:"channel_id,optional"`
	Timestamp       int64  `json:"timestamp,optional"`
	Nonce           string `json:"nonce,optional"`
	Sign            string `json:"sign"`
}

type CreateOrderResp struct {
	OrderNo          string `json:"order_no"`
	Status           int32  `json:"status"`
	ChannelId        int64  `json:"channel_id"`
	PayProductId     int64  `json:"pay_product_id"`
	PayProductCode   string `json:"pay_product_code"`
	CheckoutUrl      string `json:"checkout_url"`
	ChannelLocked    int32  `json:"channel_locked"`
}

type OrderInfo struct {
	OrderNo          string `json:"order_no"`
	MerchantId       string `json:"merchant_id"`
	MerchantOrderNo  string `json:"merchant_order_no"`
	Amount           int64  `json:"amount"`
	Currency         string `json:"currency"`
	Status           int32  `json:"status"`
	ChannelId        int64  `json:"channel_id"`
	PayProductId     int64  `json:"pay_product_id"`
	PayProductCode   string `json:"pay_product_code"`
	PayProductName   string `json:"pay_product_name"`
	ChannelLocked    int32  `json:"channel_locked"`
	PaidAmount       int64  `json:"paid_amount"`
	ReturnUrl        string `json:"return_url"`
	NotifyUrl        string `json:"notify_url"`
	UpstreamTradeNo  string `json:"upstream_trade_no"`
}

type PayProductItem struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type QueryOrderReq struct {
	MerchantId      string `form:"merchant_id"`
	OrderNo         string `form:"order_no,optional"`
	MerchantOrderNo string `form:"merchant_order_no,optional"`
	Timestamp       int64  `form:"timestamp,optional"`
	Nonce           string `form:"nonce,optional"`
	Sign            string `form:"sign"`
}

type QueryOrderResp struct {
	Order OrderInfo `json:"order"`
}

type TerminalOrderReq struct {
	OrderNo string `form:"order_no"`
}

type TerminalOrderResp struct {
	Order        OrderInfo        `json:"order"`
	PayProducts  []PayProductItem `json:"pay_products"`
}

type TerminalPayReq struct {
	OrderNo         string `json:"order_no"`
	PayProductCode  string `json:"pay_product_code,optional"`
}

type TerminalPayResp struct {
	ChannelId      int64  `json:"channel_id"`
	PayProductId   int64  `json:"pay_product_id"`
	PayProductCode string `json:"pay_product_code"`
	PayUrl         string `json:"pay_url"`
	QrPayload      string `json:"qr_payload"`
	PayMode        string `json:"pay_mode"`
}

type UpstreamNotifyReq struct {
	OrderNo         string `json:"order_no"`
	PaidAmount      int64  `json:"paid_amount"`
	UpstreamTradeNo string `json:"upstream_trade_no"`
	ChannelId       int64  `json:"channel_id"`
	Sign            string `json:"sign"`
}

type UpstreamNotifyResp struct {
	Ok bool `json:"ok"`
}

type AdminChannelInfo struct {
	Id                     int64  `json:"id"`
	Name                   string `json:"name"`
	PayType                string `json:"pay_type"`
	GatewayUrl             string `json:"gateway_url"`
	UpstreamMerchantNo     string `json:"upstream_merchant_no"`
	RsaPrivateKey          string `json:"rsa_private_key"`
	SignSecret             string `json:"sign_secret"`
	Weight                 int64  `json:"weight"`
	MinAmount              int64  `json:"min_amount"`
	MaxAmount              int64  `json:"max_amount"`
	SupportsCollect        bool   `json:"supports_collect"`
	SupportsPayout         bool   `json:"supports_payout"`
	UpstreamCollectRateBps int64  `json:"upstream_collect_rate_bps"`
	UpstreamPayoutRateBps  int64  `json:"upstream_payout_rate_bps"`
	Enabled                bool   `json:"enabled"`
	FuseEnabled            bool   `json:"fuse_enabled"`
}

type AdminListChannelsResp struct {
	Channels []AdminChannelInfo `json:"channels"`
}

type AdminUpsertChannelReq struct {
	Id                     int64  `path:"id,optional"`
	Name                   string `json:"name"`
	PayType                string `json:"pay_type,optional"`
	GatewayUrl             string `json:"gateway_url,optional"`
	UpstreamMerchantNo     string `json:"upstream_merchant_no,optional"`
	RsaPrivateKey          string `json:"rsa_private_key,optional"`
	SignSecret             string `json:"sign_secret,optional"`
	Weight                 int64  `json:"weight"`
	MinAmount              int64  `json:"min_amount,optional"`
	MaxAmount              int64  `json:"max_amount,optional"`
	SupportsCollect        bool   `json:"supports_collect,optional"`
	SupportsPayout         bool   `json:"supports_payout,optional"`
	UpstreamCollectRateBps int64  `json:"upstream_collect_rate_bps,optional"`
	UpstreamPayoutRateBps  int64  `json:"upstream_payout_rate_bps,optional"`
	Enabled                bool   `json:"enabled,optional"`
	FuseEnabled            bool   `json:"fuse_enabled,optional"`
}

type AdminUpsertChannelResp struct {
	Channel AdminChannelInfo `json:"channel"`
}

type MerchantSummaryReq struct {
}

type MerchantSummaryResp struct {
	TodayAmount int64   `json:"today_amount"`
	TodayCount  int64   `json:"today_count"`
	SuccessRate float64 `json:"success_rate"`
	Balance     int64   `json:"balance"`
	MerchantId  string  `json:"merchant_id"`
	NotifyUrl   string  `json:"notify_url"`
	IpWhitelist string  `json:"ip_whitelist"`
}

type MerchantOrdersReq struct {
	OrderNo string `form:"order_no,optional"`
	Status  string `form:"status,optional"`
	Limit   int64  `form:"limit,optional"`
}

type MerchantOrderItem struct {
	OrderNo          string `json:"order_no"`
	MerchantOrderNo  string `json:"merchant_order_no"`
	Amount           int64  `json:"amount"`
	Currency         string `json:"currency"`
	Status           int32  `json:"status"`
	ChannelId        int64  `json:"channel_id"`
	PayProductCode   string `json:"pay_product_code"`
	PayProductName   string `json:"pay_product_name"`
	PaidAmount       int64  `json:"paid_amount"`
	UpstreamTradeNo  string `json:"upstream_trade_no"`
	CreatedAt        int64  `json:"created_at"`
}

type MerchantOrdersResp struct {
	Orders []MerchantOrderItem `json:"orders"`
}

type MerchantFundLogsReq struct {
	Limit int64 `form:"limit,optional"`
}

type MerchantFundLogItem struct {
	Id            int64  `json:"id"`
	OrderNo       string `json:"order_no"`
	ChangeType    string `json:"change_type"`
	Amount        int64  `json:"amount"`
	BalanceBefore int64  `json:"balance_before"`
	BalanceAfter  int64  `json:"balance_after"`
	Reason        string `json:"reason"`
	CreatedAt     int64  `json:"created_at"`
}

type MerchantFundLogsResp struct {
	Logs []MerchantFundLogItem `json:"logs"`
}

type MerchantOrderDetailReq struct {
	OrderNo string `form:"order_no"`
}

type MerchantNotifyLogItem struct {
	Id           int64  `json:"id"`
	NotifyUrl    string `json:"notify_url"`
	Attempt      int64  `json:"attempt"`
	HttpStatus   int64  `json:"http_status"`
	ResponseBody string `json:"response_body"`
	ErrorMsg     string `json:"error_msg"`
	CreatedAt    int64  `json:"created_at"`
}

type MerchantOrderDetailResp struct {
	Order OrderInfo               `json:"order"`
	Logs  []MerchantNotifyLogItem `json:"logs"`
}

type MerchantRetryNotifyReq struct {
	OrderNo string `json:"order_no"`
}

type MerchantRetryNotifyResp struct {
	Ok bool `json:"ok"`
}

type AdminLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AdminLoginResp struct {
	Token     string `json:"token"`
	ExpiresAt int64  `json:"expires_at"`
}

type AdminLogoutResp struct {
	Ok bool `json:"ok"`
}

type MerchantLoginReq struct {
	MerchantId string `json:"merchant_id"`
	ApiSecret  string `json:"api_secret"`
}

type MerchantLoginResp struct {
	Token      string `json:"token"`
	ExpiresAt  int64  `json:"expires_at"`
	MerchantId string `json:"merchant_id"`
}

type MerchantLogoutResp struct {
	Ok bool `json:"ok"`
}

type MerchantCollectGrant struct {
	PayProductId    int64  `json:"pay_product_id"`
	MerchantRateBps *int64 `json:"merchant_rate_bps,omitempty"`
}

type MerchantPayoutGrant struct {
	PayoutProductId int64  `json:"payout_product_id"`
	MerchantRateBps *int64 `json:"merchant_rate_bps,omitempty"`
}

type AdminMerchantInfo struct {
	MerchantId            string                 `json:"merchant_id"`
	ApiSecret             string                 `json:"api_secret"`
	Status                int64                  `json:"status"`
	DefaultCollectRateBps int64                  `json:"default_collect_rate_bps"`
	DefaultPayoutRateBps  int64                  `json:"default_payout_rate_bps"`
	NotifyUrl             string                 `json:"notify_url"`
	ReturnUrl             string                 `json:"return_url"`
	IpWhitelist           string                 `json:"ip_whitelist"`
	Balance               int64                  `json:"balance"`
	PayProductIds         []int64                `json:"pay_product_ids"`
	PayoutProductIds      []int64                `json:"payout_product_ids"`
	CollectGrants         []MerchantCollectGrant `json:"collect_grants"`
	PayoutGrants          []MerchantPayoutGrant  `json:"payout_grants"`
}

type AdminListMerchantsResp struct {
	Merchants []AdminMerchantInfo `json:"merchants"`
}

type AdminCreateMerchantReq struct {
	MerchantId            string  `json:"merchant_id"`
	ApiSecret             string  `json:"api_secret,optional"`
	DefaultCollectRateBps int64   `json:"default_collect_rate_bps,optional"`
	DefaultPayoutRateBps  int64   `json:"default_payout_rate_bps,optional"`
	NotifyUrl             string  `json:"notify_url,optional"`
	ReturnUrl             string  `json:"return_url,optional"`
	IpWhitelist           string  `json:"ip_whitelist,optional"`
	PayProductIds         []int64 `json:"pay_product_ids,optional"`
	PayoutProductIds      []int64 `json:"payout_product_ids,optional"`
}

type AdminUpdateMerchantReq struct {
	MerchantId            string                 `path:"merchant_id"`
	Status                int64                  `json:"status,optional"`
	DefaultCollectRateBps int64                  `json:"default_collect_rate_bps,optional"`
	DefaultPayoutRateBps  int64                  `json:"default_payout_rate_bps,optional"`
	NotifyUrl             string                 `json:"notify_url,optional"`
	ReturnUrl             string                 `json:"return_url,optional"`
	IpWhitelist           string                 `json:"ip_whitelist,optional"`
	ResetSecret           bool                   `json:"reset_secret,optional"`
	PayProductIds         []int64                `json:"pay_product_ids,optional"`
	PayoutProductIds      []int64                `json:"payout_product_ids,optional"`
	CollectGrants         []MerchantCollectGrant `json:"collect_grants,optional"` // 若提供则覆盖代收白名单（含空数组）
	PayoutGrants          []MerchantPayoutGrant  `json:"payout_grants,optional"` // 若提供则覆盖代付白名单
}

type AdminUpsertMerchantResp struct {
	Merchant AdminMerchantInfo `json:"merchant"`
}

// --- 支付产品（对外 code）与上游通道绑定 ---

type AdminPayProductInfo struct {
	Id        int64  `json:"id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
	Enabled   bool   `json:"enabled"`
}

type AdminListPayProductsResp struct {
	Products []AdminPayProductInfo `json:"products"`
}

type AdminCreatePayProductReq struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order,optional"`
	Enabled   bool   `json:"enabled,optional"`
}

type AdminUpsertPayProductResp struct {
	Product AdminPayProductInfo `json:"product"`
}

type AdminUpdatePayProductReq struct {
	Id        int64  `path:"id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order,optional"`
	Enabled   bool   `json:"enabled,optional"`
}

type AdminPayProductBindingInfo struct {
	Id           int64  `json:"id"`
	PayProductId int64  `json:"pay_product_id"`
	ChannelId    int64  `json:"channel_id"`
	ChannelName  string `json:"channel_name"`
	Weight       int64  `json:"weight"`
	Enabled      bool   `json:"enabled"`
}

type AdminListPayProductBindingsReq struct {
	Id int64 `path:"id"`
}

type AdminListPayProductBindingsResp struct {
	Bindings []AdminPayProductBindingInfo `json:"bindings"`
}

type AdminUpsertPayProductBindingReq struct {
	PayProductId int64 `path:"id"`
	ChannelId    int64 `json:"channel_id"`
	Weight       int64 `json:"weight"`
	Enabled      bool  `json:"enabled,optional"`
}

type AdminUpsertPayProductBindingResp struct {
	Binding AdminPayProductBindingInfo `json:"binding"`
}

type AdminUpdatePayProductBindingReq struct {
	Id      int64 `path:"id"`
	Weight  int64 `json:"weight"`
	Enabled bool  `json:"enabled,optional"`
}

type AdminUpdatePayProductBindingResp struct {
	Binding AdminPayProductBindingInfo `json:"binding"`
}

type AdminDeletePayProductBindingReq struct {
	Id int64 `path:"id"`
}

type AdminDeletePayProductBindingResp struct {
	Ok bool `json:"ok"`
}

// --- 代付产品（对外 code）与上游通道绑定 ---

type AdminPayoutProductInfo struct {
	Id        int64  `json:"id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
	Enabled   bool   `json:"enabled"`
}

type AdminListPayoutProductsResp struct {
	Products []AdminPayoutProductInfo `json:"products"`
}

type AdminCreatePayoutProductReq struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order,optional"`
	Enabled   bool   `json:"enabled,optional"`
}

type AdminUpsertPayoutProductResp struct {
	Product AdminPayoutProductInfo `json:"product"`
}

type AdminUpdatePayoutProductReq struct {
	Id        int64  `path:"id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order,optional"`
	Enabled   bool   `json:"enabled,optional"`
}

type AdminPayoutProductBindingInfo struct {
	Id              int64  `json:"id"`
	PayoutProductId int64  `json:"payout_product_id"`
	ChannelId       int64  `json:"channel_id"`
	ChannelName     string `json:"channel_name"`
	Weight          int64  `json:"weight"`
	Enabled         bool   `json:"enabled"`
}

type AdminListPayoutProductBindingsReq struct {
	Id int64 `path:"id"`
}

type AdminListPayoutProductBindingsResp struct {
	Bindings []AdminPayoutProductBindingInfo `json:"bindings"`
}

type AdminUpsertPayoutProductBindingReq struct {
	PayoutProductId int64 `path:"id"`
	ChannelId       int64 `json:"channel_id"`
	Weight          int64 `json:"weight"`
	Enabled         bool  `json:"enabled,optional"`
}

type AdminUpsertPayoutProductBindingResp struct {
	Binding AdminPayoutProductBindingInfo `json:"binding"`
}

type AdminUpdatePayoutProductBindingReq struct {
	Id      int64 `path:"id"`
	Weight  int64 `json:"weight"`
	Enabled bool  `json:"enabled,optional"`
}

type AdminUpdatePayoutProductBindingResp struct {
	Binding AdminPayoutProductBindingInfo `json:"binding"`
}

type AdminDeletePayoutProductBindingReq struct {
	Id int64 `path:"id"`
}

type AdminDeletePayoutProductBindingResp struct {
	Ok bool `json:"ok"`
}

// --- 路由策略（概览，配置分散在「支付产品与通道」「商户」「通道」） ---

type AdminRoutingSummaryResp struct {
	AlgorithmKey                  string `json:"algorithm_key"`
	AlgorithmLabel                string `json:"algorithm_label"`
	EnabledPayProducts            int64  `json:"enabled_pay_products"`
	EnabledPayoutProducts         int64  `json:"enabled_payout_products"`
	EnabledChannels               int64  `json:"enabled_channels"`
	ActiveBindings                int64  `json:"active_bindings"`
	ActivePayoutBindings          int64  `json:"active_payout_bindings"`
	MerchantsWithCollectWhitelist int64  `json:"merchants_with_collect_whitelist"`
	MerchantsWithPayoutWhitelist  int64  `json:"merchants_with_payout_whitelist"`
	FusedChannels                 int64  `json:"fused_channels"`
}

// --- 管理台统计（C5：监控看板简版） ---

type AdminStatsTotals struct {
	OrderCount               int64   `json:"order_count"`
	PaidAmount               int64   `json:"paid_amount"`
	PaidCount                int64   `json:"paid_count"`
	FailedCount              int64   `json:"failed_count"`
	PendingCount             int64   `json:"pending_count"`
	ClosedCount              int64   `json:"closed_count"`
	ConversionRatePct        float64 `json:"conversion_rate_pct"`
	TerminalSuccessRatePct   float64 `json:"terminal_success_rate_pct"`
}

type AdminStatsProductRow struct {
	ProductCode              string  `json:"product_code"`
	ProductName              string  `json:"product_name"`
	OrderCount               int64   `json:"order_count"`
	PaidAmount               int64   `json:"paid_amount"`
	PaidCount                int64   `json:"paid_count"`
	FailedCount              int64   `json:"failed_count"`
	ConversionRatePct        float64 `json:"conversion_rate_pct"`
	TerminalSuccessRatePct   float64 `json:"terminal_success_rate_pct"`
}

type AdminStatsChannelRow struct {
	ChannelId                int64   `json:"channel_id"`
	ChannelName              string  `json:"channel_name"`
	OrderCount               int64   `json:"order_count"`
	PaidAmount               int64   `json:"paid_amount"`
	PaidCount                int64   `json:"paid_count"`
	FailedCount              int64   `json:"failed_count"`
	ConversionRatePct        float64 `json:"conversion_rate_pct"`
	TerminalSuccessRatePct   float64 `json:"terminal_success_rate_pct"`
}

type AdminStatsOverviewResp struct {
	Range             string                 `json:"range"`
	Totals            AdminStatsTotals       `json:"totals"`
	ByPayProduct      []AdminStatsProductRow `json:"by_pay_product"`
	ByChannel         []AdminStatsChannelRow `json:"by_channel"`
	EnabledChannels   int64                  `json:"enabled_channels"`
	FusedChannels     int64                  `json:"fused_channels"`
}

type AdminOrdersReq struct {
	MerchantId string `form:"merchant_id,optional"`
	Keyword    string `form:"keyword,optional"`
	Status     string `form:"status,optional"`
	Limit      int64  `form:"limit,optional"`
}

type AdminOrderRow struct {
	OrderNo         string `json:"order_no"`
	MerchantId      string `json:"merchant_id"`
	MerchantOrderNo string `json:"merchant_order_no"`
	Amount          int64  `json:"amount"`
	Currency        string `json:"currency"`
	Status          int32  `json:"status"`
	ChannelId       int64  `json:"channel_id"`
	PayProductId    int64  `json:"pay_product_id"`
	PayProductCode  string `json:"pay_product_code"`
	PaidAmount      int64  `json:"paid_amount"`
	UpstreamTradeNo string `json:"upstream_trade_no"`
	CreatedAt       int64  `json:"created_at"`
}

type AdminOrdersResp struct {
	Orders []AdminOrderRow `json:"orders"`
}

// --- 对账：按日平台账快照（与系统概览同源聚合，可选历史日） ---

type AdminDayOverviewReq struct {
	Date string `form:"date"`
}

type AdminDayOverviewResp struct {
	Date         string                 `json:"date"`
	Totals       AdminStatsTotals       `json:"totals"`
	ByPayProduct []AdminStatsProductRow `json:"by_pay_product"`
	ByChannel    []AdminStatsChannelRow `json:"by_channel"`
}
