// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: channel.proto

package channelclient

import (
	"context"

	"github.com/gloopai/pay/common/pb/channel"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RouteReq          = channel.RouteReq
	RouteResp         = channel.RouteResp
	GetSignSecretReq  = channel.GetSignSecretReq
	GetSignSecretResp = channel.GetSignSecretResp

	Channel interface {
		Route(ctx context.Context, in *RouteReq, opts ...grpc.CallOption) (*RouteResp, error)
		GetSignSecret(ctx context.Context, in *GetSignSecretReq, opts ...grpc.CallOption) (*GetSignSecretResp, error)
	}

	defaultChannel struct {
		cli zrpc.Client
	}
)

func NewChannel(cli zrpc.Client) Channel {
	return &defaultChannel{
		cli: cli,
	}
}

func (m *defaultChannel) Route(ctx context.Context, in *RouteReq, opts ...grpc.CallOption) (*RouteResp, error) {
	client := channel.NewChannelClient(m.cli.Conn())
	return client.Route(ctx, in, opts...)
}

func (m *defaultChannel) GetSignSecret(ctx context.Context, in *GetSignSecretReq, opts ...grpc.CallOption) (*GetSignSecretResp, error) {
	client := channel.NewChannelClient(m.cli.Conn())
	return client.GetSignSecret(ctx, in, opts...)
}
