// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: channel.proto

package channel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Channel_Route_FullMethodName                           = "/channel.Channel/Route"
	Channel_GetSignSecret_FullMethodName                   = "/channel.Channel/GetSignSecret"
	Channel_GetChannel_FullMethodName                      = "/channel.Channel/GetChannel"
	Channel_ListChannels_FullMethodName                    = "/channel.Channel/ListChannels"
	Channel_CreateChannel_FullMethodName                   = "/channel.Channel/CreateChannel"
	Channel_UpdateChannel_FullMethodName                   = "/channel.Channel/UpdateChannel"
	Channel_GetRoutingSummary_FullMethodName               = "/channel.Channel/GetRoutingSummary"
	Channel_ListTerminalPayinProducts_FullMethodName       = "/channel.Channel/ListTerminalPayinProducts"
	Channel_MerchantHasPayinProductCode_FullMethodName     = "/channel.Channel/MerchantHasPayinProductCode"
	Channel_ResolveLockedChannelForMerchant_FullMethodName = "/channel.Channel/ResolveLockedChannelForMerchant"
	Channel_GetPayinProductDisplayName_FullMethodName      = "/channel.Channel/GetPayinProductDisplayName"
	Channel_AdminListPayinProducts_FullMethodName          = "/channel.Channel/AdminListPayinProducts"
	Channel_AdminCreatePayinProduct_FullMethodName         = "/channel.Channel/AdminCreatePayinProduct"
	Channel_AdminUpdatePayinProduct_FullMethodName         = "/channel.Channel/AdminUpdatePayinProduct"
	Channel_AdminListPayinProductBindings_FullMethodName   = "/channel.Channel/AdminListPayinProductBindings"
	Channel_AdminUpsertPayinProductBinding_FullMethodName  = "/channel.Channel/AdminUpsertPayinProductBinding"
	Channel_AdminUpdatePayinProductBinding_FullMethodName  = "/channel.Channel/AdminUpdatePayinProductBinding"
	Channel_AdminDeletePayinProductBinding_FullMethodName  = "/channel.Channel/AdminDeletePayinProductBinding"
	Channel_AdminListPayoutProducts_FullMethodName         = "/channel.Channel/AdminListPayoutProducts"
	Channel_AdminCreatePayoutProduct_FullMethodName        = "/channel.Channel/AdminCreatePayoutProduct"
	Channel_AdminUpdatePayoutProduct_FullMethodName        = "/channel.Channel/AdminUpdatePayoutProduct"
	Channel_AdminListPayoutProductBindings_FullMethodName  = "/channel.Channel/AdminListPayoutProductBindings"
	Channel_AdminUpsertPayoutProductBinding_FullMethodName = "/channel.Channel/AdminUpsertPayoutProductBinding"
	Channel_AdminUpdatePayoutProductBinding_FullMethodName = "/channel.Channel/AdminUpdatePayoutProductBinding"
	Channel_AdminDeletePayoutProductBinding_FullMethodName = "/channel.Channel/AdminDeletePayoutProductBinding"
)

// ChannelClient is the client API for Channel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChannelClient interface {
	Route(ctx context.Context, in *RouteReq, opts ...grpc.CallOption) (*RouteResp, error)
	GetSignSecret(ctx context.Context, in *GetSignSecretReq, opts ...grpc.CallOption) (*GetSignSecretResp, error)
	// 按主键取单条通道（供上游回调等按 channel_id 热路径，避免 ListChannels 全表扫描）
	GetChannel(ctx context.Context, in *GetChannelReq, opts ...grpc.CallOption) (*GetChannelResp, error)
	ListChannels(ctx context.Context, in *ListChannelsReq, opts ...grpc.CallOption) (*ListChannelsResp, error)
	CreateChannel(ctx context.Context, in *UpsertChannelReq, opts ...grpc.CallOption) (*UpsertChannelResp, error)
	UpdateChannel(ctx context.Context, in *UpsertChannelReq, opts ...grpc.CallOption) (*UpsertChannelResp, error)
	GetRoutingSummary(ctx context.Context, in *GetRoutingSummaryReq, opts ...grpc.CallOption) (*GetRoutingSummaryResp, error)
	ListTerminalPayinProducts(ctx context.Context, in *ListTerminalPayinProductsReq, opts ...grpc.CallOption) (*ListTerminalPayinProductsResp, error)
	MerchantHasPayinProductCode(ctx context.Context, in *MerchantHasPayinProductCodeReq, opts ...grpc.CallOption) (*MerchantHasPayinProductCodeResp, error)
	ResolveLockedChannelForMerchant(ctx context.Context, in *ResolveLockedChannelForMerchantReq, opts ...grpc.CallOption) (*ResolveLockedChannelForMerchantResp, error)
	GetPayinProductDisplayName(ctx context.Context, in *GetPayinProductDisplayNameReq, opts ...grpc.CallOption) (*GetPayinProductDisplayNameResp, error)
	AdminListPayinProducts(ctx context.Context, in *AdminListPayinProductsReq, opts ...grpc.CallOption) (*AdminListPayinProductsResp, error)
	AdminCreatePayinProduct(ctx context.Context, in *AdminCreatePayinProductReq, opts ...grpc.CallOption) (*AdminUpsertPayinProductResp, error)
	AdminUpdatePayinProduct(ctx context.Context, in *AdminUpdatePayinProductReq, opts ...grpc.CallOption) (*AdminUpsertPayinProductResp, error)
	AdminListPayinProductBindings(ctx context.Context, in *AdminListPayinProductBindingsReq, opts ...grpc.CallOption) (*AdminListPayinProductBindingsResp, error)
	AdminUpsertPayinProductBinding(ctx context.Context, in *AdminUpsertPayinProductBindingReq, opts ...grpc.CallOption) (*AdminUpsertPayinProductBindingResp, error)
	AdminUpdatePayinProductBinding(ctx context.Context, in *AdminUpdatePayinProductBindingReq, opts ...grpc.CallOption) (*AdminUpdatePayinProductBindingResp, error)
	AdminDeletePayinProductBinding(ctx context.Context, in *AdminDeletePayinProductBindingReq, opts ...grpc.CallOption) (*AdminDeletePayinProductBindingResp, error)
	AdminListPayoutProducts(ctx context.Context, in *AdminListPayoutProductsReq, opts ...grpc.CallOption) (*AdminListPayoutProductsResp, error)
	AdminCreatePayoutProduct(ctx context.Context, in *AdminCreatePayoutProductReq, opts ...grpc.CallOption) (*AdminUpsertPayoutProductResp, error)
	AdminUpdatePayoutProduct(ctx context.Context, in *AdminUpdatePayoutProductReq, opts ...grpc.CallOption) (*AdminUpsertPayoutProductResp, error)
	AdminListPayoutProductBindings(ctx context.Context, in *AdminListPayoutProductBindingsReq, opts ...grpc.CallOption) (*AdminListPayoutProductBindingsResp, error)
	AdminUpsertPayoutProductBinding(ctx context.Context, in *AdminUpsertPayoutProductBindingReq, opts ...grpc.CallOption) (*AdminUpsertPayoutProductBindingResp, error)
	AdminUpdatePayoutProductBinding(ctx context.Context, in *AdminUpdatePayoutProductBindingReq, opts ...grpc.CallOption) (*AdminUpdatePayoutProductBindingResp, error)
	AdminDeletePayoutProductBinding(ctx context.Context, in *AdminDeletePayoutProductBindingReq, opts ...grpc.CallOption) (*AdminDeletePayoutProductBindingResp, error)
}

type channelClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelClient(cc grpc.ClientConnInterface) ChannelClient {
	return &channelClient{cc}
}

func (c *channelClient) Route(ctx context.Context, in *RouteReq, opts ...grpc.CallOption) (*RouteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteResp)
	err := c.cc.Invoke(ctx, Channel_Route_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) GetSignSecret(ctx context.Context, in *GetSignSecretReq, opts ...grpc.CallOption) (*GetSignSecretResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSignSecretResp)
	err := c.cc.Invoke(ctx, Channel_GetSignSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) GetChannel(ctx context.Context, in *GetChannelReq, opts ...grpc.CallOption) (*GetChannelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChannelResp)
	err := c.cc.Invoke(ctx, Channel_GetChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) ListChannels(ctx context.Context, in *ListChannelsReq, opts ...grpc.CallOption) (*ListChannelsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChannelsResp)
	err := c.cc.Invoke(ctx, Channel_ListChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) CreateChannel(ctx context.Context, in *UpsertChannelReq, opts ...grpc.CallOption) (*UpsertChannelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertChannelResp)
	err := c.cc.Invoke(ctx, Channel_CreateChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) UpdateChannel(ctx context.Context, in *UpsertChannelReq, opts ...grpc.CallOption) (*UpsertChannelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertChannelResp)
	err := c.cc.Invoke(ctx, Channel_UpdateChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) GetRoutingSummary(ctx context.Context, in *GetRoutingSummaryReq, opts ...grpc.CallOption) (*GetRoutingSummaryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingSummaryResp)
	err := c.cc.Invoke(ctx, Channel_GetRoutingSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) ListTerminalPayinProducts(ctx context.Context, in *ListTerminalPayinProductsReq, opts ...grpc.CallOption) (*ListTerminalPayinProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTerminalPayinProductsResp)
	err := c.cc.Invoke(ctx, Channel_ListTerminalPayinProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) MerchantHasPayinProductCode(ctx context.Context, in *MerchantHasPayinProductCodeReq, opts ...grpc.CallOption) (*MerchantHasPayinProductCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerchantHasPayinProductCodeResp)
	err := c.cc.Invoke(ctx, Channel_MerchantHasPayinProductCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) ResolveLockedChannelForMerchant(ctx context.Context, in *ResolveLockedChannelForMerchantReq, opts ...grpc.CallOption) (*ResolveLockedChannelForMerchantResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveLockedChannelForMerchantResp)
	err := c.cc.Invoke(ctx, Channel_ResolveLockedChannelForMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) GetPayinProductDisplayName(ctx context.Context, in *GetPayinProductDisplayNameReq, opts ...grpc.CallOption) (*GetPayinProductDisplayNameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayinProductDisplayNameResp)
	err := c.cc.Invoke(ctx, Channel_GetPayinProductDisplayName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) AdminListPayinProducts(ctx context.Context, in *AdminListPayinProductsReq, opts ...grpc.CallOption) (*AdminListPayinProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListPayinProductsResp)
	err := c.cc.Invoke(ctx, Channel_AdminListPayinProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) AdminCreatePayinProduct(ctx context.Context, in *AdminCreatePayinProductReq, opts ...grpc.CallOption) (*AdminUpsertPayinProductResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpsertPayinProductResp)
	err := c.cc.Invoke(ctx, Channel_AdminCreatePayinProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) AdminUpdatePayinProduct(ctx context.Context, in *AdminUpdatePayinProductReq, opts ...grpc.CallOption) (*AdminUpsertPayinProductResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpsertPayinProductResp)
	err := c.cc.Invoke(ctx, Channel_AdminUpdatePayinProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) AdminListPayinProductBindings(ctx context.Context, in *AdminListPayinProductBindingsReq, opts ...grpc.CallOption) (*AdminListPayinProductBindingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListPayinProductBindingsResp)
	err := c.cc.Invoke(ctx, Channel_AdminListPayinProductBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) AdminUpsertPayinProductBinding(ctx context.Context, in *AdminUpsertPayinProductBindingReq, opts ...grpc.CallOption) (*AdminUpsertPayinProductBindingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpsertPayinProductBindingResp)
	err := c.cc.Invoke(ctx, Channel_AdminUpsertPayinProductBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) AdminUpdatePayinProductBinding(ctx context.Context, in *AdminUpdatePayinProductBindingReq, opts ...grpc.CallOption) (*AdminUpdatePayinProductBindingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpdatePayinProductBindingResp)
	err := c.cc.Invoke(ctx, Channel_AdminUpdatePayinProductBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) AdminDeletePayinProductBinding(ctx context.Context, in *AdminDeletePayinProductBindingReq, opts ...grpc.CallOption) (*AdminDeletePayinProductBindingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeletePayinProductBindingResp)
	err := c.cc.Invoke(ctx, Channel_AdminDeletePayinProductBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) AdminListPayoutProducts(ctx context.Context, in *AdminListPayoutProductsReq, opts ...grpc.CallOption) (*AdminListPayoutProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListPayoutProductsResp)
	err := c.cc.Invoke(ctx, Channel_AdminListPayoutProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) AdminCreatePayoutProduct(ctx context.Context, in *AdminCreatePayoutProductReq, opts ...grpc.CallOption) (*AdminUpsertPayoutProductResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpsertPayoutProductResp)
	err := c.cc.Invoke(ctx, Channel_AdminCreatePayoutProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) AdminUpdatePayoutProduct(ctx context.Context, in *AdminUpdatePayoutProductReq, opts ...grpc.CallOption) (*AdminUpsertPayoutProductResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpsertPayoutProductResp)
	err := c.cc.Invoke(ctx, Channel_AdminUpdatePayoutProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) AdminListPayoutProductBindings(ctx context.Context, in *AdminListPayoutProductBindingsReq, opts ...grpc.CallOption) (*AdminListPayoutProductBindingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListPayoutProductBindingsResp)
	err := c.cc.Invoke(ctx, Channel_AdminListPayoutProductBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) AdminUpsertPayoutProductBinding(ctx context.Context, in *AdminUpsertPayoutProductBindingReq, opts ...grpc.CallOption) (*AdminUpsertPayoutProductBindingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpsertPayoutProductBindingResp)
	err := c.cc.Invoke(ctx, Channel_AdminUpsertPayoutProductBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) AdminUpdatePayoutProductBinding(ctx context.Context, in *AdminUpdatePayoutProductBindingReq, opts ...grpc.CallOption) (*AdminUpdatePayoutProductBindingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpdatePayoutProductBindingResp)
	err := c.cc.Invoke(ctx, Channel_AdminUpdatePayoutProductBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) AdminDeletePayoutProductBinding(ctx context.Context, in *AdminDeletePayoutProductBindingReq, opts ...grpc.CallOption) (*AdminDeletePayoutProductBindingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeletePayoutProductBindingResp)
	err := c.cc.Invoke(ctx, Channel_AdminDeletePayoutProductBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelServer is the server API for Channel service.
// All implementations must embed UnimplementedChannelServer
// for forward compatibility.
type ChannelServer interface {
	Route(context.Context, *RouteReq) (*RouteResp, error)
	GetSignSecret(context.Context, *GetSignSecretReq) (*GetSignSecretResp, error)
	// 按主键取单条通道（供上游回调等按 channel_id 热路径，避免 ListChannels 全表扫描）
	GetChannel(context.Context, *GetChannelReq) (*GetChannelResp, error)
	ListChannels(context.Context, *ListChannelsReq) (*ListChannelsResp, error)
	CreateChannel(context.Context, *UpsertChannelReq) (*UpsertChannelResp, error)
	UpdateChannel(context.Context, *UpsertChannelReq) (*UpsertChannelResp, error)
	GetRoutingSummary(context.Context, *GetRoutingSummaryReq) (*GetRoutingSummaryResp, error)
	ListTerminalPayinProducts(context.Context, *ListTerminalPayinProductsReq) (*ListTerminalPayinProductsResp, error)
	MerchantHasPayinProductCode(context.Context, *MerchantHasPayinProductCodeReq) (*MerchantHasPayinProductCodeResp, error)
	ResolveLockedChannelForMerchant(context.Context, *ResolveLockedChannelForMerchantReq) (*ResolveLockedChannelForMerchantResp, error)
	GetPayinProductDisplayName(context.Context, *GetPayinProductDisplayNameReq) (*GetPayinProductDisplayNameResp, error)
	AdminListPayinProducts(context.Context, *AdminListPayinProductsReq) (*AdminListPayinProductsResp, error)
	AdminCreatePayinProduct(context.Context, *AdminCreatePayinProductReq) (*AdminUpsertPayinProductResp, error)
	AdminUpdatePayinProduct(context.Context, *AdminUpdatePayinProductReq) (*AdminUpsertPayinProductResp, error)
	AdminListPayinProductBindings(context.Context, *AdminListPayinProductBindingsReq) (*AdminListPayinProductBindingsResp, error)
	AdminUpsertPayinProductBinding(context.Context, *AdminUpsertPayinProductBindingReq) (*AdminUpsertPayinProductBindingResp, error)
	AdminUpdatePayinProductBinding(context.Context, *AdminUpdatePayinProductBindingReq) (*AdminUpdatePayinProductBindingResp, error)
	AdminDeletePayinProductBinding(context.Context, *AdminDeletePayinProductBindingReq) (*AdminDeletePayinProductBindingResp, error)
	AdminListPayoutProducts(context.Context, *AdminListPayoutProductsReq) (*AdminListPayoutProductsResp, error)
	AdminCreatePayoutProduct(context.Context, *AdminCreatePayoutProductReq) (*AdminUpsertPayoutProductResp, error)
	AdminUpdatePayoutProduct(context.Context, *AdminUpdatePayoutProductReq) (*AdminUpsertPayoutProductResp, error)
	AdminListPayoutProductBindings(context.Context, *AdminListPayoutProductBindingsReq) (*AdminListPayoutProductBindingsResp, error)
	AdminUpsertPayoutProductBinding(context.Context, *AdminUpsertPayoutProductBindingReq) (*AdminUpsertPayoutProductBindingResp, error)
	AdminUpdatePayoutProductBinding(context.Context, *AdminUpdatePayoutProductBindingReq) (*AdminUpdatePayoutProductBindingResp, error)
	AdminDeletePayoutProductBinding(context.Context, *AdminDeletePayoutProductBindingReq) (*AdminDeletePayoutProductBindingResp, error)
	mustEmbedUnimplementedChannelServer()
}

// UnimplementedChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelServer struct{}

func (UnimplementedChannelServer) Route(context.Context, *RouteReq) (*RouteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Route not implemented")
}
func (UnimplementedChannelServer) GetSignSecret(context.Context, *GetSignSecretReq) (*GetSignSecretResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSignSecret not implemented")
}
func (UnimplementedChannelServer) GetChannel(context.Context, *GetChannelReq) (*GetChannelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannel not implemented")
}
func (UnimplementedChannelServer) ListChannels(context.Context, *ListChannelsReq) (*ListChannelsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChannels not implemented")
}
func (UnimplementedChannelServer) CreateChannel(context.Context, *UpsertChannelReq) (*UpsertChannelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChannel not implemented")
}
func (UnimplementedChannelServer) UpdateChannel(context.Context, *UpsertChannelReq) (*UpsertChannelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChannel not implemented")
}
func (UnimplementedChannelServer) GetRoutingSummary(context.Context, *GetRoutingSummaryReq) (*GetRoutingSummaryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingSummary not implemented")
}
func (UnimplementedChannelServer) ListTerminalPayinProducts(context.Context, *ListTerminalPayinProductsReq) (*ListTerminalPayinProductsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTerminalPayinProducts not implemented")
}
func (UnimplementedChannelServer) MerchantHasPayinProductCode(context.Context, *MerchantHasPayinProductCodeReq) (*MerchantHasPayinProductCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantHasPayinProductCode not implemented")
}
func (UnimplementedChannelServer) ResolveLockedChannelForMerchant(context.Context, *ResolveLockedChannelForMerchantReq) (*ResolveLockedChannelForMerchantResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveLockedChannelForMerchant not implemented")
}
func (UnimplementedChannelServer) GetPayinProductDisplayName(context.Context, *GetPayinProductDisplayNameReq) (*GetPayinProductDisplayNameResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayinProductDisplayName not implemented")
}
func (UnimplementedChannelServer) AdminListPayinProducts(context.Context, *AdminListPayinProductsReq) (*AdminListPayinProductsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminListPayinProducts not implemented")
}
func (UnimplementedChannelServer) AdminCreatePayinProduct(context.Context, *AdminCreatePayinProductReq) (*AdminUpsertPayinProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminCreatePayinProduct not implemented")
}
func (UnimplementedChannelServer) AdminUpdatePayinProduct(context.Context, *AdminUpdatePayinProductReq) (*AdminUpsertPayinProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUpdatePayinProduct not implemented")
}
func (UnimplementedChannelServer) AdminListPayinProductBindings(context.Context, *AdminListPayinProductBindingsReq) (*AdminListPayinProductBindingsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminListPayinProductBindings not implemented")
}
func (UnimplementedChannelServer) AdminUpsertPayinProductBinding(context.Context, *AdminUpsertPayinProductBindingReq) (*AdminUpsertPayinProductBindingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUpsertPayinProductBinding not implemented")
}
func (UnimplementedChannelServer) AdminUpdatePayinProductBinding(context.Context, *AdminUpdatePayinProductBindingReq) (*AdminUpdatePayinProductBindingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUpdatePayinProductBinding not implemented")
}
func (UnimplementedChannelServer) AdminDeletePayinProductBinding(context.Context, *AdminDeletePayinProductBindingReq) (*AdminDeletePayinProductBindingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminDeletePayinProductBinding not implemented")
}
func (UnimplementedChannelServer) AdminListPayoutProducts(context.Context, *AdminListPayoutProductsReq) (*AdminListPayoutProductsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminListPayoutProducts not implemented")
}
func (UnimplementedChannelServer) AdminCreatePayoutProduct(context.Context, *AdminCreatePayoutProductReq) (*AdminUpsertPayoutProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminCreatePayoutProduct not implemented")
}
func (UnimplementedChannelServer) AdminUpdatePayoutProduct(context.Context, *AdminUpdatePayoutProductReq) (*AdminUpsertPayoutProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUpdatePayoutProduct not implemented")
}
func (UnimplementedChannelServer) AdminListPayoutProductBindings(context.Context, *AdminListPayoutProductBindingsReq) (*AdminListPayoutProductBindingsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminListPayoutProductBindings not implemented")
}
func (UnimplementedChannelServer) AdminUpsertPayoutProductBinding(context.Context, *AdminUpsertPayoutProductBindingReq) (*AdminUpsertPayoutProductBindingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUpsertPayoutProductBinding not implemented")
}
func (UnimplementedChannelServer) AdminUpdatePayoutProductBinding(context.Context, *AdminUpdatePayoutProductBindingReq) (*AdminUpdatePayoutProductBindingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUpdatePayoutProductBinding not implemented")
}
func (UnimplementedChannelServer) AdminDeletePayoutProductBinding(context.Context, *AdminDeletePayoutProductBindingReq) (*AdminDeletePayoutProductBindingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminDeletePayoutProductBinding not implemented")
}
func (UnimplementedChannelServer) mustEmbedUnimplementedChannelServer() {}
func (UnimplementedChannelServer) testEmbeddedByValue()                 {}

// UnsafeChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelServer will
// result in compilation errors.
type UnsafeChannelServer interface {
	mustEmbedUnimplementedChannelServer()
}

func RegisterChannelServer(s grpc.ServiceRegistrar, srv ChannelServer) {
	// If the following call pancis, it indicates UnimplementedChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Channel_ServiceDesc, srv)
}

func _Channel_Route_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).Route(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_Route_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).Route(ctx, req.(*RouteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_GetSignSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignSecretReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).GetSignSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_GetSignSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).GetSignSecret(ctx, req.(*GetSignSecretReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_GetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).GetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_GetChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).GetChannel(ctx, req.(*GetChannelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_ListChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).ListChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_ListChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).ListChannels(ctx, req.(*ListChannelsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_CreateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertChannelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).CreateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_CreateChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).CreateChannel(ctx, req.(*UpsertChannelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_UpdateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertChannelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).UpdateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_UpdateChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).UpdateChannel(ctx, req.(*UpsertChannelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_GetRoutingSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingSummaryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).GetRoutingSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_GetRoutingSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).GetRoutingSummary(ctx, req.(*GetRoutingSummaryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_ListTerminalPayinProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTerminalPayinProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).ListTerminalPayinProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_ListTerminalPayinProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).ListTerminalPayinProducts(ctx, req.(*ListTerminalPayinProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_MerchantHasPayinProductCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantHasPayinProductCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).MerchantHasPayinProductCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_MerchantHasPayinProductCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).MerchantHasPayinProductCode(ctx, req.(*MerchantHasPayinProductCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_ResolveLockedChannelForMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveLockedChannelForMerchantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).ResolveLockedChannelForMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_ResolveLockedChannelForMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).ResolveLockedChannelForMerchant(ctx, req.(*ResolveLockedChannelForMerchantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_GetPayinProductDisplayName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayinProductDisplayNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).GetPayinProductDisplayName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_GetPayinProductDisplayName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).GetPayinProductDisplayName(ctx, req.(*GetPayinProductDisplayNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_AdminListPayinProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListPayinProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).AdminListPayinProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_AdminListPayinProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).AdminListPayinProducts(ctx, req.(*AdminListPayinProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_AdminCreatePayinProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreatePayinProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).AdminCreatePayinProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_AdminCreatePayinProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).AdminCreatePayinProduct(ctx, req.(*AdminCreatePayinProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_AdminUpdatePayinProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdatePayinProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).AdminUpdatePayinProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_AdminUpdatePayinProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).AdminUpdatePayinProduct(ctx, req.(*AdminUpdatePayinProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_AdminListPayinProductBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListPayinProductBindingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).AdminListPayinProductBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_AdminListPayinProductBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).AdminListPayinProductBindings(ctx, req.(*AdminListPayinProductBindingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_AdminUpsertPayinProductBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpsertPayinProductBindingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).AdminUpsertPayinProductBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_AdminUpsertPayinProductBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).AdminUpsertPayinProductBinding(ctx, req.(*AdminUpsertPayinProductBindingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_AdminUpdatePayinProductBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdatePayinProductBindingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).AdminUpdatePayinProductBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_AdminUpdatePayinProductBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).AdminUpdatePayinProductBinding(ctx, req.(*AdminUpdatePayinProductBindingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_AdminDeletePayinProductBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeletePayinProductBindingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).AdminDeletePayinProductBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_AdminDeletePayinProductBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).AdminDeletePayinProductBinding(ctx, req.(*AdminDeletePayinProductBindingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_AdminListPayoutProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListPayoutProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).AdminListPayoutProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_AdminListPayoutProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).AdminListPayoutProducts(ctx, req.(*AdminListPayoutProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_AdminCreatePayoutProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreatePayoutProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).AdminCreatePayoutProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_AdminCreatePayoutProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).AdminCreatePayoutProduct(ctx, req.(*AdminCreatePayoutProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_AdminUpdatePayoutProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdatePayoutProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).AdminUpdatePayoutProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_AdminUpdatePayoutProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).AdminUpdatePayoutProduct(ctx, req.(*AdminUpdatePayoutProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_AdminListPayoutProductBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListPayoutProductBindingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).AdminListPayoutProductBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_AdminListPayoutProductBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).AdminListPayoutProductBindings(ctx, req.(*AdminListPayoutProductBindingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_AdminUpsertPayoutProductBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpsertPayoutProductBindingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).AdminUpsertPayoutProductBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_AdminUpsertPayoutProductBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).AdminUpsertPayoutProductBinding(ctx, req.(*AdminUpsertPayoutProductBindingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_AdminUpdatePayoutProductBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdatePayoutProductBindingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).AdminUpdatePayoutProductBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_AdminUpdatePayoutProductBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).AdminUpdatePayoutProductBinding(ctx, req.(*AdminUpdatePayoutProductBindingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_AdminDeletePayoutProductBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeletePayoutProductBindingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).AdminDeletePayoutProductBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_AdminDeletePayoutProductBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).AdminDeletePayoutProductBinding(ctx, req.(*AdminDeletePayoutProductBindingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Channel_ServiceDesc is the grpc.ServiceDesc for Channel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Channel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "channel.Channel",
	HandlerType: (*ChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Route",
			Handler:    _Channel_Route_Handler,
		},
		{
			MethodName: "GetSignSecret",
			Handler:    _Channel_GetSignSecret_Handler,
		},
		{
			MethodName: "GetChannel",
			Handler:    _Channel_GetChannel_Handler,
		},
		{
			MethodName: "ListChannels",
			Handler:    _Channel_ListChannels_Handler,
		},
		{
			MethodName: "CreateChannel",
			Handler:    _Channel_CreateChannel_Handler,
		},
		{
			MethodName: "UpdateChannel",
			Handler:    _Channel_UpdateChannel_Handler,
		},
		{
			MethodName: "GetRoutingSummary",
			Handler:    _Channel_GetRoutingSummary_Handler,
		},
		{
			MethodName: "ListTerminalPayinProducts",
			Handler:    _Channel_ListTerminalPayinProducts_Handler,
		},
		{
			MethodName: "MerchantHasPayinProductCode",
			Handler:    _Channel_MerchantHasPayinProductCode_Handler,
		},
		{
			MethodName: "ResolveLockedChannelForMerchant",
			Handler:    _Channel_ResolveLockedChannelForMerchant_Handler,
		},
		{
			MethodName: "GetPayinProductDisplayName",
			Handler:    _Channel_GetPayinProductDisplayName_Handler,
		},
		{
			MethodName: "AdminListPayinProducts",
			Handler:    _Channel_AdminListPayinProducts_Handler,
		},
		{
			MethodName: "AdminCreatePayinProduct",
			Handler:    _Channel_AdminCreatePayinProduct_Handler,
		},
		{
			MethodName: "AdminUpdatePayinProduct",
			Handler:    _Channel_AdminUpdatePayinProduct_Handler,
		},
		{
			MethodName: "AdminListPayinProductBindings",
			Handler:    _Channel_AdminListPayinProductBindings_Handler,
		},
		{
			MethodName: "AdminUpsertPayinProductBinding",
			Handler:    _Channel_AdminUpsertPayinProductBinding_Handler,
		},
		{
			MethodName: "AdminUpdatePayinProductBinding",
			Handler:    _Channel_AdminUpdatePayinProductBinding_Handler,
		},
		{
			MethodName: "AdminDeletePayinProductBinding",
			Handler:    _Channel_AdminDeletePayinProductBinding_Handler,
		},
		{
			MethodName: "AdminListPayoutProducts",
			Handler:    _Channel_AdminListPayoutProducts_Handler,
		},
		{
			MethodName: "AdminCreatePayoutProduct",
			Handler:    _Channel_AdminCreatePayoutProduct_Handler,
		},
		{
			MethodName: "AdminUpdatePayoutProduct",
			Handler:    _Channel_AdminUpdatePayoutProduct_Handler,
		},
		{
			MethodName: "AdminListPayoutProductBindings",
			Handler:    _Channel_AdminListPayoutProductBindings_Handler,
		},
		{
			MethodName: "AdminUpsertPayoutProductBinding",
			Handler:    _Channel_AdminUpsertPayoutProductBinding_Handler,
		},
		{
			MethodName: "AdminUpdatePayoutProductBinding",
			Handler:    _Channel_AdminUpdatePayoutProductBinding_Handler,
		},
		{
			MethodName: "AdminDeletePayoutProductBinding",
			Handler:    _Channel_AdminDeletePayoutProductBinding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "channel.proto",
}
