// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: servicehub.proto

package servicehub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAdminUserByUsernameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAdminUserByUsernameReq) Reset() {
	*x = FindAdminUserByUsernameReq{}
	mi := &file_servicehub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAdminUserByUsernameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAdminUserByUsernameReq) ProtoMessage() {}

func (x *FindAdminUserByUsernameReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAdminUserByUsernameReq.ProtoReflect.Descriptor instead.
func (*FindAdminUserByUsernameReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{0}
}

func (x *FindAdminUserByUsernameReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type FindAdminUserByUsernameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *AdminUser             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAdminUserByUsernameResp) Reset() {
	*x = FindAdminUserByUsernameResp{}
	mi := &file_servicehub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAdminUserByUsernameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAdminUserByUsernameResp) ProtoMessage() {}

func (x *FindAdminUserByUsernameResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAdminUserByUsernameResp.ProtoReflect.Descriptor instead.
func (*FindAdminUserByUsernameResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{1}
}

func (x *FindAdminUserByUsernameResp) GetUser() *AdminUser {
	if x != nil {
		return x.User
	}
	return nil
}

type AdminUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_servicehub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{2}
}

func (x *AdminUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUser) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *AdminUser) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AdminUserPublic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Status        int64                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserPublic) Reset() {
	*x = AdminUserPublic{}
	mi := &file_servicehub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserPublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserPublic) ProtoMessage() {}

func (x *AdminUserPublic) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserPublic.ProtoReflect.Descriptor instead.
func (*AdminUserPublic) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{3}
}

func (x *AdminUserPublic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUserPublic) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUserPublic) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListAdminUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminUsersReq) Reset() {
	*x = ListAdminUsersReq{}
	mi := &file_servicehub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminUsersReq) ProtoMessage() {}

func (x *ListAdminUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminUsersReq.ProtoReflect.Descriptor instead.
func (*ListAdminUsersReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{4}
}

type ListAdminUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*AdminUserPublic     `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminUsersResp) Reset() {
	*x = ListAdminUsersResp{}
	mi := &file_servicehub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminUsersResp) ProtoMessage() {}

func (x *ListAdminUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminUsersResp.ProtoReflect.Descriptor instead.
func (*ListAdminUsersResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{5}
}

func (x *ListAdminUsersResp) GetUsers() []*AdminUserPublic {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetDisplaySettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisplaySettingsReq) Reset() {
	*x = GetDisplaySettingsReq{}
	mi := &file_servicehub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisplaySettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisplaySettingsReq) ProtoMessage() {}

func (x *GetDisplaySettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisplaySettingsReq.ProtoReflect.Descriptor instead.
func (*GetDisplaySettingsReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{6}
}

type GetDisplaySettingsResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CountryCode    string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CurrencyCode   string                 `protobuf:"bytes,2,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	CurrencySymbol string                 `protobuf:"bytes,3,opt,name=currency_symbol,json=currencySymbol,proto3" json:"currency_symbol,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDisplaySettingsResp) Reset() {
	*x = GetDisplaySettingsResp{}
	mi := &file_servicehub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisplaySettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisplaySettingsResp) ProtoMessage() {}

func (x *GetDisplaySettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisplaySettingsResp.ProtoReflect.Descriptor instead.
func (*GetDisplaySettingsResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{7}
}

func (x *GetDisplaySettingsResp) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GetDisplaySettingsResp) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *GetDisplaySettingsResp) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

type UpsertDisplaySettingsReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CountryCode    string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CurrencyCode   string                 `protobuf:"bytes,2,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	CurrencySymbol string                 `protobuf:"bytes,3,opt,name=currency_symbol,json=currencySymbol,proto3" json:"currency_symbol,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertDisplaySettingsReq) Reset() {
	*x = UpsertDisplaySettingsReq{}
	mi := &file_servicehub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDisplaySettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDisplaySettingsReq) ProtoMessage() {}

func (x *UpsertDisplaySettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDisplaySettingsReq.ProtoReflect.Descriptor instead.
func (*UpsertDisplaySettingsReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertDisplaySettingsReq) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *UpsertDisplaySettingsReq) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *UpsertDisplaySettingsReq) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

type MarkPayoutSuccessReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderNo         string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UpstreamTradeNo string                 `protobuf:"bytes,2,opt,name=upstream_trade_no,json=upstreamTradeNo,proto3" json:"upstream_trade_no,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkPayoutSuccessReq) Reset() {
	*x = MarkPayoutSuccessReq{}
	mi := &file_servicehub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPayoutSuccessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPayoutSuccessReq) ProtoMessage() {}

func (x *MarkPayoutSuccessReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPayoutSuccessReq.ProtoReflect.Descriptor instead.
func (*MarkPayoutSuccessReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{9}
}

func (x *MarkPayoutSuccessReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *MarkPayoutSuccessReq) GetUpstreamTradeNo() string {
	if x != nil {
		return x.UpstreamTradeNo
	}
	return ""
}

type MarkPayoutFailedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPayoutFailedReq) Reset() {
	*x = MarkPayoutFailedReq{}
	mi := &file_servicehub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPayoutFailedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPayoutFailedReq) ProtoMessage() {}

func (x *MarkPayoutFailedReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPayoutFailedReq.ProtoReflect.Descriptor instead.
func (*MarkPayoutFailedReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{10}
}

func (x *MarkPayoutFailedReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type MarkPayoutResultResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPayoutResultResp) Reset() {
	*x = MarkPayoutResultResp{}
	mi := &file_servicehub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPayoutResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPayoutResultResp) ProtoMessage() {}

func (x *MarkPayoutResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPayoutResultResp.ProtoReflect.Descriptor instead.
func (*MarkPayoutResultResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{11}
}

func (x *MarkPayoutResultResp) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

type GetAdminRbacMyMenusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUserId   int64                  `protobuf:"varint,1,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminRbacMyMenusReq) Reset() {
	*x = GetAdminRbacMyMenusReq{}
	mi := &file_servicehub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminRbacMyMenusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminRbacMyMenusReq) ProtoMessage() {}

func (x *GetAdminRbacMyMenusReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminRbacMyMenusReq.ProtoReflect.Descriptor instead.
func (*GetAdminRbacMyMenusReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{12}
}

func (x *GetAdminRbacMyMenusReq) GetAdminUserId() int64 {
	if x != nil {
		return x.AdminUserId
	}
	return 0
}

type AdminMenu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	MenuKey       string                 `protobuf:"bytes,3,opt,name=menu_key,json=menuKey,proto3" json:"menu_key,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Kind          int64                  `protobuf:"varint,6,opt,name=kind,proto3" json:"kind,omitempty"` // 1=leaf 2=group
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`  // leaf only; vue-router path like "/stats"
	SortOrder     int64                  `protobuf:"varint,8,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminMenu) Reset() {
	*x = AdminMenu{}
	mi := &file_servicehub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminMenu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminMenu) ProtoMessage() {}

func (x *AdminMenu) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminMenu.ProtoReflect.Descriptor instead.
func (*AdminMenu) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{13}
}

func (x *AdminMenu) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminMenu) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *AdminMenu) GetMenuKey() string {
	if x != nil {
		return x.MenuKey
	}
	return ""
}

func (x *AdminMenu) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AdminMenu) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AdminMenu) GetKind() int64 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *AdminMenu) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AdminMenu) GetSortOrder() int64 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type GetAdminRbacMyMenusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menus         []*AdminMenu           `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminRbacMyMenusResp) Reset() {
	*x = GetAdminRbacMyMenusResp{}
	mi := &file_servicehub_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminRbacMyMenusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminRbacMyMenusResp) ProtoMessage() {}

func (x *GetAdminRbacMyMenusResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminRbacMyMenusResp.ProtoReflect.Descriptor instead.
func (*GetAdminRbacMyMenusResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{14}
}

func (x *GetAdminRbacMyMenusResp) GetMenus() []*AdminMenu {
	if x != nil {
		return x.Menus
	}
	return nil
}

type ListAdminRolesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminRolesReq) Reset() {
	*x = ListAdminRolesReq{}
	mi := &file_servicehub_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminRolesReq) ProtoMessage() {}

func (x *ListAdminRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminRolesReq.ProtoReflect.Descriptor instead.
func (*ListAdminRolesReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{15}
}

type AdminRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRole) Reset() {
	*x = AdminRole{}
	mi := &file_servicehub_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRole) ProtoMessage() {}

func (x *AdminRole) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRole.ProtoReflect.Descriptor instead.
func (*AdminRole) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{16}
}

func (x *AdminRole) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminRole) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AdminRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminRole) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListAdminRolesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*AdminRole           `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminRolesResp) Reset() {
	*x = ListAdminRolesResp{}
	mi := &file_servicehub_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminRolesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminRolesResp) ProtoMessage() {}

func (x *ListAdminRolesResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminRolesResp.ProtoReflect.Descriptor instead.
func (*ListAdminRolesResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{17}
}

func (x *ListAdminRolesResp) GetRoles() []*AdminRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

type CreateAdminRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        int64                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminRoleReq) Reset() {
	*x = CreateAdminRoleReq{}
	mi := &file_servicehub_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminRoleReq) ProtoMessage() {}

func (x *CreateAdminRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminRoleReq.ProtoReflect.Descriptor instead.
func (*CreateAdminRoleReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{18}
}

func (x *CreateAdminRoleReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateAdminRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAdminRoleReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateAdminRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *AdminRole             `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminRoleResp) Reset() {
	*x = CreateAdminRoleResp{}
	mi := &file_servicehub_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminRoleResp) ProtoMessage() {}

func (x *CreateAdminRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminRoleResp.ProtoReflect.Descriptor instead.
func (*CreateAdminRoleResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{19}
}

func (x *CreateAdminRoleResp) GetRole() *AdminRole {
	if x != nil {
		return x.Role
	}
	return nil
}

type UpdateAdminRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        int64                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminRoleReq) Reset() {
	*x = UpdateAdminRoleReq{}
	mi := &file_servicehub_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminRoleReq) ProtoMessage() {}

func (x *UpdateAdminRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateAdminRoleReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateAdminRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAdminRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAdminRoleReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateAdminRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *AdminRole             `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminRoleResp) Reset() {
	*x = UpdateAdminRoleResp{}
	mi := &file_servicehub_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminRoleResp) ProtoMessage() {}

func (x *UpdateAdminRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminRoleResp.ProtoReflect.Descriptor instead.
func (*UpdateAdminRoleResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateAdminRoleResp) GetRole() *AdminRole {
	if x != nil {
		return x.Role
	}
	return nil
}

type DeleteAdminRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminRoleReq) Reset() {
	*x = DeleteAdminRoleReq{}
	mi := &file_servicehub_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminRoleReq) ProtoMessage() {}

func (x *DeleteAdminRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminRoleReq.ProtoReflect.Descriptor instead.
func (*DeleteAdminRoleReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteAdminRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAdminRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminRoleResp) Reset() {
	*x = DeleteAdminRoleResp{}
	mi := &file_servicehub_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminRoleResp) ProtoMessage() {}

func (x *DeleteAdminRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminRoleResp.ProtoReflect.Descriptor instead.
func (*DeleteAdminRoleResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteAdminRoleResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListAdminMenusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminMenusReq) Reset() {
	*x = ListAdminMenusReq{}
	mi := &file_servicehub_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminMenusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminMenusReq) ProtoMessage() {}

func (x *ListAdminMenusReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminMenusReq.ProtoReflect.Descriptor instead.
func (*ListAdminMenusReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{24}
}

type ListAdminMenusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menus         []*AdminMenu           `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminMenusResp) Reset() {
	*x = ListAdminMenusResp{}
	mi := &file_servicehub_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminMenusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminMenusResp) ProtoMessage() {}

func (x *ListAdminMenusResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminMenusResp.ProtoReflect.Descriptor instead.
func (*ListAdminMenusResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{25}
}

func (x *ListAdminMenusResp) GetMenus() []*AdminMenu {
	if x != nil {
		return x.Menus
	}
	return nil
}

type GetAdminRoleMenusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminRoleMenusReq) Reset() {
	*x = GetAdminRoleMenusReq{}
	mi := &file_servicehub_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminRoleMenusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminRoleMenusReq) ProtoMessage() {}

func (x *GetAdminRoleMenusReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminRoleMenusReq.ProtoReflect.Descriptor instead.
func (*GetAdminRoleMenusReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{26}
}

func (x *GetAdminRoleMenusReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type GetAdminRoleMenusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuIds       []int64                `protobuf:"varint,1,rep,packed,name=menu_ids,json=menuIds,proto3" json:"menu_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminRoleMenusResp) Reset() {
	*x = GetAdminRoleMenusResp{}
	mi := &file_servicehub_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminRoleMenusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminRoleMenusResp) ProtoMessage() {}

func (x *GetAdminRoleMenusResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminRoleMenusResp.ProtoReflect.Descriptor instead.
func (*GetAdminRoleMenusResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{27}
}

func (x *GetAdminRoleMenusResp) GetMenuIds() []int64 {
	if x != nil {
		return x.MenuIds
	}
	return nil
}

type SetAdminRoleMenusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	MenuIds       []int64                `protobuf:"varint,2,rep,packed,name=menu_ids,json=menuIds,proto3" json:"menu_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAdminRoleMenusReq) Reset() {
	*x = SetAdminRoleMenusReq{}
	mi := &file_servicehub_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAdminRoleMenusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminRoleMenusReq) ProtoMessage() {}

func (x *SetAdminRoleMenusReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminRoleMenusReq.ProtoReflect.Descriptor instead.
func (*SetAdminRoleMenusReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{28}
}

func (x *SetAdminRoleMenusReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *SetAdminRoleMenusReq) GetMenuIds() []int64 {
	if x != nil {
		return x.MenuIds
	}
	return nil
}

type SetAdminRoleMenusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAdminRoleMenusResp) Reset() {
	*x = SetAdminRoleMenusResp{}
	mi := &file_servicehub_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAdminRoleMenusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminRoleMenusResp) ProtoMessage() {}

func (x *SetAdminRoleMenusResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminRoleMenusResp.ProtoReflect.Descriptor instead.
func (*SetAdminRoleMenusResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{29}
}

func (x *SetAdminRoleMenusResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetAdminUserRolesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUserId   int64                  `protobuf:"varint,1,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminUserRolesReq) Reset() {
	*x = GetAdminUserRolesReq{}
	mi := &file_servicehub_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminUserRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminUserRolesReq) ProtoMessage() {}

func (x *GetAdminUserRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminUserRolesReq.ProtoReflect.Descriptor instead.
func (*GetAdminUserRolesReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{30}
}

func (x *GetAdminUserRolesReq) GetAdminUserId() int64 {
	if x != nil {
		return x.AdminUserId
	}
	return 0
}

type GetAdminUserRolesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleIds       []int64                `protobuf:"varint,1,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminUserRolesResp) Reset() {
	*x = GetAdminUserRolesResp{}
	mi := &file_servicehub_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminUserRolesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminUserRolesResp) ProtoMessage() {}

func (x *GetAdminUserRolesResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminUserRolesResp.ProtoReflect.Descriptor instead.
func (*GetAdminUserRolesResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{31}
}

func (x *GetAdminUserRolesResp) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type SetAdminUserRolesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUserId   int64                  `protobuf:"varint,1,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`
	RoleIds       []int64                `protobuf:"varint,2,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAdminUserRolesReq) Reset() {
	*x = SetAdminUserRolesReq{}
	mi := &file_servicehub_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAdminUserRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminUserRolesReq) ProtoMessage() {}

func (x *SetAdminUserRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminUserRolesReq.ProtoReflect.Descriptor instead.
func (*SetAdminUserRolesReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{32}
}

func (x *SetAdminUserRolesReq) GetAdminUserId() int64 {
	if x != nil {
		return x.AdminUserId
	}
	return 0
}

func (x *SetAdminUserRolesReq) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type SetAdminUserRolesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAdminUserRolesResp) Reset() {
	*x = SetAdminUserRolesResp{}
	mi := &file_servicehub_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAdminUserRolesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminUserRolesResp) ProtoMessage() {}

func (x *SetAdminUserRolesResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminUserRolesResp.ProtoReflect.Descriptor instead.
func (*SetAdminUserRolesResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{33}
}

func (x *SetAdminUserRolesResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_servicehub_proto protoreflect.FileDescriptor

const file_servicehub_proto_rawDesc = "" +
	"\n" +
	"\x10servicehub.proto\x12\n" +
	"servicehub\"8\n" +
	"\x1aFindAdminUserByUsernameReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"H\n" +
	"\x1bFindAdminUserByUsernameResp\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.servicehub.AdminUserR\x04user\"t\n" +
	"\tAdminUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\"U\n" +
	"\x0fAdminUserPublic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\"\x13\n" +
	"\x11ListAdminUsersReq\"G\n" +
	"\x12ListAdminUsersResp\x121\n" +
	"\x05users\x18\x01 \x03(\v2\x1b.servicehub.AdminUserPublicR\x05users\"\x17\n" +
	"\x15GetDisplaySettingsReq\"\x89\x01\n" +
	"\x16GetDisplaySettingsResp\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12#\n" +
	"\rcurrency_code\x18\x02 \x01(\tR\fcurrencyCode\x12'\n" +
	"\x0fcurrency_symbol\x18\x03 \x01(\tR\x0ecurrencySymbol\"\x8b\x01\n" +
	"\x18UpsertDisplaySettingsReq\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12#\n" +
	"\rcurrency_code\x18\x02 \x01(\tR\fcurrencyCode\x12'\n" +
	"\x0fcurrency_symbol\x18\x03 \x01(\tR\x0ecurrencySymbol\"]\n" +
	"\x14MarkPayoutSuccessReq\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12*\n" +
	"\x11upstream_trade_no\x18\x02 \x01(\tR\x0fupstreamTradeNo\"0\n" +
	"\x13MarkPayoutFailedReq\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"0\n" +
	"\x14MarkPayoutResultResp\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\"<\n" +
	"\x16GetAdminRbacMyMenusReq\x12\"\n" +
	"\radmin_user_id\x18\x01 \x01(\x03R\vadminUserId\"\xc4\x01\n" +
	"\tAdminMenu\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x19\n" +
	"\bmenu_key\x18\x03 \x01(\tR\amenuKey\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x12\n" +
	"\x04kind\x18\x06 \x01(\x03R\x04kind\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"sort_order\x18\b \x01(\x03R\tsortOrder\"F\n" +
	"\x17GetAdminRbacMyMenusResp\x12+\n" +
	"\x05menus\x18\x01 \x03(\v2\x15.servicehub.AdminMenuR\x05menus\"\x13\n" +
	"\x11ListAdminRolesReq\"[\n" +
	"\tAdminRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\"A\n" +
	"\x12ListAdminRolesResp\x12+\n" +
	"\x05roles\x18\x01 \x03(\v2\x15.servicehub.AdminRoleR\x05roles\"T\n" +
	"\x12CreateAdminRoleReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\"@\n" +
	"\x13CreateAdminRoleResp\x12)\n" +
	"\x04role\x18\x01 \x01(\v2\x15.servicehub.AdminRoleR\x04role\"P\n" +
	"\x12UpdateAdminRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\"@\n" +
	"\x13UpdateAdminRoleResp\x12)\n" +
	"\x04role\x18\x01 \x01(\v2\x15.servicehub.AdminRoleR\x04role\"$\n" +
	"\x12DeleteAdminRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"%\n" +
	"\x13DeleteAdminRoleResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x13\n" +
	"\x11ListAdminMenusReq\"A\n" +
	"\x12ListAdminMenusResp\x12+\n" +
	"\x05menus\x18\x01 \x03(\v2\x15.servicehub.AdminMenuR\x05menus\"/\n" +
	"\x14GetAdminRoleMenusReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\"2\n" +
	"\x15GetAdminRoleMenusResp\x12\x19\n" +
	"\bmenu_ids\x18\x01 \x03(\x03R\amenuIds\"J\n" +
	"\x14SetAdminRoleMenusReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x19\n" +
	"\bmenu_ids\x18\x02 \x03(\x03R\amenuIds\"'\n" +
	"\x15SetAdminRoleMenusResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\":\n" +
	"\x14GetAdminUserRolesReq\x12\"\n" +
	"\radmin_user_id\x18\x01 \x01(\x03R\vadminUserId\"2\n" +
	"\x15GetAdminUserRolesResp\x12\x19\n" +
	"\brole_ids\x18\x01 \x03(\x03R\aroleIds\"U\n" +
	"\x14SetAdminUserRolesReq\x12\"\n" +
	"\radmin_user_id\x18\x01 \x01(\x03R\vadminUserId\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\x03R\aroleIds\"'\n" +
	"\x15SetAdminUserRolesResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x9f\v\n" +
	"\n" +
	"ServiceHub\x12j\n" +
	"\x17FindAdminUserByUsername\x12&.servicehub.FindAdminUserByUsernameReq\x1a'.servicehub.FindAdminUserByUsernameResp\x12O\n" +
	"\x0eListAdminUsers\x12\x1d.servicehub.ListAdminUsersReq\x1a\x1e.servicehub.ListAdminUsersResp\x12[\n" +
	"\x12GetDisplaySettings\x12!.servicehub.GetDisplaySettingsReq\x1a\".servicehub.GetDisplaySettingsResp\x12a\n" +
	"\x15UpsertDisplaySettings\x12$.servicehub.UpsertDisplaySettingsReq\x1a\".servicehub.GetDisplaySettingsResp\x12W\n" +
	"\x11MarkPayoutSuccess\x12 .servicehub.MarkPayoutSuccessReq\x1a .servicehub.MarkPayoutResultResp\x12U\n" +
	"\x10MarkPayoutFailed\x12\x1f.servicehub.MarkPayoutFailedReq\x1a .servicehub.MarkPayoutResultResp\x12^\n" +
	"\x13GetAdminRbacMyMenus\x12\".servicehub.GetAdminRbacMyMenusReq\x1a#.servicehub.GetAdminRbacMyMenusResp\x12O\n" +
	"\x0eListAdminRoles\x12\x1d.servicehub.ListAdminRolesReq\x1a\x1e.servicehub.ListAdminRolesResp\x12R\n" +
	"\x0fCreateAdminRole\x12\x1e.servicehub.CreateAdminRoleReq\x1a\x1f.servicehub.CreateAdminRoleResp\x12R\n" +
	"\x0fUpdateAdminRole\x12\x1e.servicehub.UpdateAdminRoleReq\x1a\x1f.servicehub.UpdateAdminRoleResp\x12R\n" +
	"\x0fDeleteAdminRole\x12\x1e.servicehub.DeleteAdminRoleReq\x1a\x1f.servicehub.DeleteAdminRoleResp\x12O\n" +
	"\x0eListAdminMenus\x12\x1d.servicehub.ListAdminMenusReq\x1a\x1e.servicehub.ListAdminMenusResp\x12X\n" +
	"\x11GetAdminRoleMenus\x12 .servicehub.GetAdminRoleMenusReq\x1a!.servicehub.GetAdminRoleMenusResp\x12X\n" +
	"\x11SetAdminRoleMenus\x12 .servicehub.SetAdminRoleMenusReq\x1a!.servicehub.SetAdminRoleMenusResp\x12X\n" +
	"\x11GetAdminUserRoles\x12 .servicehub.GetAdminUserRolesReq\x1a!.servicehub.GetAdminUserRolesResp\x12X\n" +
	"\x11SetAdminUserRoles\x12 .servicehub.SetAdminUserRolesReq\x1a!.servicehub.SetAdminUserRolesRespB8Z6github.com/gloopai/pay/common/pb/servicehub;servicehubb\x06proto3"

var (
	file_servicehub_proto_rawDescOnce sync.Once
	file_servicehub_proto_rawDescData []byte
)

func file_servicehub_proto_rawDescGZIP() []byte {
	file_servicehub_proto_rawDescOnce.Do(func() {
		file_servicehub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servicehub_proto_rawDesc), len(file_servicehub_proto_rawDesc)))
	})
	return file_servicehub_proto_rawDescData
}

var file_servicehub_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_servicehub_proto_goTypes = []any{
	(*FindAdminUserByUsernameReq)(nil),  // 0: servicehub.FindAdminUserByUsernameReq
	(*FindAdminUserByUsernameResp)(nil), // 1: servicehub.FindAdminUserByUsernameResp
	(*AdminUser)(nil),                   // 2: servicehub.AdminUser
	(*AdminUserPublic)(nil),             // 3: servicehub.AdminUserPublic
	(*ListAdminUsersReq)(nil),           // 4: servicehub.ListAdminUsersReq
	(*ListAdminUsersResp)(nil),          // 5: servicehub.ListAdminUsersResp
	(*GetDisplaySettingsReq)(nil),       // 6: servicehub.GetDisplaySettingsReq
	(*GetDisplaySettingsResp)(nil),      // 7: servicehub.GetDisplaySettingsResp
	(*UpsertDisplaySettingsReq)(nil),    // 8: servicehub.UpsertDisplaySettingsReq
	(*MarkPayoutSuccessReq)(nil),        // 9: servicehub.MarkPayoutSuccessReq
	(*MarkPayoutFailedReq)(nil),         // 10: servicehub.MarkPayoutFailedReq
	(*MarkPayoutResultResp)(nil),        // 11: servicehub.MarkPayoutResultResp
	(*GetAdminRbacMyMenusReq)(nil),      // 12: servicehub.GetAdminRbacMyMenusReq
	(*AdminMenu)(nil),                   // 13: servicehub.AdminMenu
	(*GetAdminRbacMyMenusResp)(nil),     // 14: servicehub.GetAdminRbacMyMenusResp
	(*ListAdminRolesReq)(nil),           // 15: servicehub.ListAdminRolesReq
	(*AdminRole)(nil),                   // 16: servicehub.AdminRole
	(*ListAdminRolesResp)(nil),          // 17: servicehub.ListAdminRolesResp
	(*CreateAdminRoleReq)(nil),          // 18: servicehub.CreateAdminRoleReq
	(*CreateAdminRoleResp)(nil),         // 19: servicehub.CreateAdminRoleResp
	(*UpdateAdminRoleReq)(nil),          // 20: servicehub.UpdateAdminRoleReq
	(*UpdateAdminRoleResp)(nil),         // 21: servicehub.UpdateAdminRoleResp
	(*DeleteAdminRoleReq)(nil),          // 22: servicehub.DeleteAdminRoleReq
	(*DeleteAdminRoleResp)(nil),         // 23: servicehub.DeleteAdminRoleResp
	(*ListAdminMenusReq)(nil),           // 24: servicehub.ListAdminMenusReq
	(*ListAdminMenusResp)(nil),          // 25: servicehub.ListAdminMenusResp
	(*GetAdminRoleMenusReq)(nil),        // 26: servicehub.GetAdminRoleMenusReq
	(*GetAdminRoleMenusResp)(nil),       // 27: servicehub.GetAdminRoleMenusResp
	(*SetAdminRoleMenusReq)(nil),        // 28: servicehub.SetAdminRoleMenusReq
	(*SetAdminRoleMenusResp)(nil),       // 29: servicehub.SetAdminRoleMenusResp
	(*GetAdminUserRolesReq)(nil),        // 30: servicehub.GetAdminUserRolesReq
	(*GetAdminUserRolesResp)(nil),       // 31: servicehub.GetAdminUserRolesResp
	(*SetAdminUserRolesReq)(nil),        // 32: servicehub.SetAdminUserRolesReq
	(*SetAdminUserRolesResp)(nil),       // 33: servicehub.SetAdminUserRolesResp
}
var file_servicehub_proto_depIdxs = []int32{
	2,  // 0: servicehub.FindAdminUserByUsernameResp.user:type_name -> servicehub.AdminUser
	3,  // 1: servicehub.ListAdminUsersResp.users:type_name -> servicehub.AdminUserPublic
	13, // 2: servicehub.GetAdminRbacMyMenusResp.menus:type_name -> servicehub.AdminMenu
	16, // 3: servicehub.ListAdminRolesResp.roles:type_name -> servicehub.AdminRole
	16, // 4: servicehub.CreateAdminRoleResp.role:type_name -> servicehub.AdminRole
	16, // 5: servicehub.UpdateAdminRoleResp.role:type_name -> servicehub.AdminRole
	13, // 6: servicehub.ListAdminMenusResp.menus:type_name -> servicehub.AdminMenu
	0,  // 7: servicehub.ServiceHub.FindAdminUserByUsername:input_type -> servicehub.FindAdminUserByUsernameReq
	4,  // 8: servicehub.ServiceHub.ListAdminUsers:input_type -> servicehub.ListAdminUsersReq
	6,  // 9: servicehub.ServiceHub.GetDisplaySettings:input_type -> servicehub.GetDisplaySettingsReq
	8,  // 10: servicehub.ServiceHub.UpsertDisplaySettings:input_type -> servicehub.UpsertDisplaySettingsReq
	9,  // 11: servicehub.ServiceHub.MarkPayoutSuccess:input_type -> servicehub.MarkPayoutSuccessReq
	10, // 12: servicehub.ServiceHub.MarkPayoutFailed:input_type -> servicehub.MarkPayoutFailedReq
	12, // 13: servicehub.ServiceHub.GetAdminRbacMyMenus:input_type -> servicehub.GetAdminRbacMyMenusReq
	15, // 14: servicehub.ServiceHub.ListAdminRoles:input_type -> servicehub.ListAdminRolesReq
	18, // 15: servicehub.ServiceHub.CreateAdminRole:input_type -> servicehub.CreateAdminRoleReq
	20, // 16: servicehub.ServiceHub.UpdateAdminRole:input_type -> servicehub.UpdateAdminRoleReq
	22, // 17: servicehub.ServiceHub.DeleteAdminRole:input_type -> servicehub.DeleteAdminRoleReq
	24, // 18: servicehub.ServiceHub.ListAdminMenus:input_type -> servicehub.ListAdminMenusReq
	26, // 19: servicehub.ServiceHub.GetAdminRoleMenus:input_type -> servicehub.GetAdminRoleMenusReq
	28, // 20: servicehub.ServiceHub.SetAdminRoleMenus:input_type -> servicehub.SetAdminRoleMenusReq
	30, // 21: servicehub.ServiceHub.GetAdminUserRoles:input_type -> servicehub.GetAdminUserRolesReq
	32, // 22: servicehub.ServiceHub.SetAdminUserRoles:input_type -> servicehub.SetAdminUserRolesReq
	1,  // 23: servicehub.ServiceHub.FindAdminUserByUsername:output_type -> servicehub.FindAdminUserByUsernameResp
	5,  // 24: servicehub.ServiceHub.ListAdminUsers:output_type -> servicehub.ListAdminUsersResp
	7,  // 25: servicehub.ServiceHub.GetDisplaySettings:output_type -> servicehub.GetDisplaySettingsResp
	7,  // 26: servicehub.ServiceHub.UpsertDisplaySettings:output_type -> servicehub.GetDisplaySettingsResp
	11, // 27: servicehub.ServiceHub.MarkPayoutSuccess:output_type -> servicehub.MarkPayoutResultResp
	11, // 28: servicehub.ServiceHub.MarkPayoutFailed:output_type -> servicehub.MarkPayoutResultResp
	14, // 29: servicehub.ServiceHub.GetAdminRbacMyMenus:output_type -> servicehub.GetAdminRbacMyMenusResp
	17, // 30: servicehub.ServiceHub.ListAdminRoles:output_type -> servicehub.ListAdminRolesResp
	19, // 31: servicehub.ServiceHub.CreateAdminRole:output_type -> servicehub.CreateAdminRoleResp
	21, // 32: servicehub.ServiceHub.UpdateAdminRole:output_type -> servicehub.UpdateAdminRoleResp
	23, // 33: servicehub.ServiceHub.DeleteAdminRole:output_type -> servicehub.DeleteAdminRoleResp
	25, // 34: servicehub.ServiceHub.ListAdminMenus:output_type -> servicehub.ListAdminMenusResp
	27, // 35: servicehub.ServiceHub.GetAdminRoleMenus:output_type -> servicehub.GetAdminRoleMenusResp
	29, // 36: servicehub.ServiceHub.SetAdminRoleMenus:output_type -> servicehub.SetAdminRoleMenusResp
	31, // 37: servicehub.ServiceHub.GetAdminUserRoles:output_type -> servicehub.GetAdminUserRolesResp
	33, // 38: servicehub.ServiceHub.SetAdminUserRoles:output_type -> servicehub.SetAdminUserRolesResp
	23, // [23:39] is the sub-list for method output_type
	7,  // [7:23] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_servicehub_proto_init() }
func file_servicehub_proto_init() {
	if File_servicehub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servicehub_proto_rawDesc), len(file_servicehub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servicehub_proto_goTypes,
		DependencyIndexes: file_servicehub_proto_depIdxs,
		MessageInfos:      file_servicehub_proto_msgTypes,
	}.Build()
	File_servicehub_proto = out.File
	file_servicehub_proto_goTypes = nil
	file_servicehub_proto_depIdxs = nil
}
