// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePayoutOrderReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MerchantId        string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MerchantOrderNo   string                 `protobuf:"bytes,2,opt,name=merchant_order_no,json=merchantOrderNo,proto3" json:"merchant_order_no,omitempty"`
	Amount            int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	NotifyUrl         string                 `protobuf:"bytes,5,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	ChannelId         int64                  `protobuf:"varint,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PayoutProductId   int64                  `protobuf:"varint,7,opt,name=payout_product_id,json=payoutProductId,proto3" json:"payout_product_id,omitempty"`
	PayoutProductCode string                 `protobuf:"bytes,8,opt,name=payout_product_code,json=payoutProductCode,proto3" json:"payout_product_code,omitempty"`
	FeeMode           int64                  `protobuf:"varint,9,opt,name=fee_mode,json=feeMode,proto3" json:"fee_mode,omitempty"`
	FeeRateBps        int64                  `protobuf:"varint,10,opt,name=fee_rate_bps,json=feeRateBps,proto3" json:"fee_rate_bps,omitempty"`
	FeeFixedAmount    int64                  `protobuf:"varint,11,opt,name=fee_fixed_amount,json=feeFixedAmount,proto3" json:"fee_fixed_amount,omitempty"`
	FeeAmount         int64                  `protobuf:"varint,12,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	NetAmount         int64                  `protobuf:"varint,13,opt,name=net_amount,json=netAmount,proto3" json:"net_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePayoutOrderReq) Reset() {
	*x = CreatePayoutOrderReq{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePayoutOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePayoutOrderReq) ProtoMessage() {}

func (x *CreatePayoutOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePayoutOrderReq.ProtoReflect.Descriptor instead.
func (*CreatePayoutOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePayoutOrderReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreatePayoutOrderReq) GetMerchantOrderNo() string {
	if x != nil {
		return x.MerchantOrderNo
	}
	return ""
}

func (x *CreatePayoutOrderReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePayoutOrderReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePayoutOrderReq) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *CreatePayoutOrderReq) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *CreatePayoutOrderReq) GetPayoutProductId() int64 {
	if x != nil {
		return x.PayoutProductId
	}
	return 0
}

func (x *CreatePayoutOrderReq) GetPayoutProductCode() string {
	if x != nil {
		return x.PayoutProductCode
	}
	return ""
}

func (x *CreatePayoutOrderReq) GetFeeMode() int64 {
	if x != nil {
		return x.FeeMode
	}
	return 0
}

func (x *CreatePayoutOrderReq) GetFeeRateBps() int64 {
	if x != nil {
		return x.FeeRateBps
	}
	return 0
}

func (x *CreatePayoutOrderReq) GetFeeFixedAmount() int64 {
	if x != nil {
		return x.FeeFixedAmount
	}
	return 0
}

func (x *CreatePayoutOrderReq) GetFeeAmount() int64 {
	if x != nil {
		return x.FeeAmount
	}
	return 0
}

func (x *CreatePayoutOrderReq) GetNetAmount() int64 {
	if x != nil {
		return x.NetAmount
	}
	return 0
}

type CreateOrderReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MerchantId       string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MerchantOrderNo  string                 `protobuf:"bytes,2,opt,name=merchant_order_no,json=merchantOrderNo,proto3" json:"merchant_order_no,omitempty"`
	Amount           int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Subject          string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	ReturnUrl        string                 `protobuf:"bytes,6,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	NotifyUrl        string                 `protobuf:"bytes,7,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	PayinType        string                 `protobuf:"bytes,8,opt,name=payin_type,json=payinType,proto3" json:"payin_type,omitempty"`
	ChannelId        int64                  `protobuf:"varint,9,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PayinProductId   int64                  `protobuf:"varint,10,opt,name=payin_product_id,json=payinProductId,proto3" json:"payin_product_id,omitempty"`
	PayinProductCode string                 `protobuf:"bytes,11,opt,name=payin_product_code,json=payinProductCode,proto3" json:"payin_product_code,omitempty"`
	// 下单时由网关/交易写入：商户 API 指定通道时为 1
	ChannelLocked  int32 `protobuf:"varint,12,opt,name=channel_locked,json=channelLocked,proto3" json:"channel_locked,omitempty"`
	FeeMode        int64 `protobuf:"varint,13,opt,name=fee_mode,json=feeMode,proto3" json:"fee_mode,omitempty"`
	FeeRateBps     int64 `protobuf:"varint,14,opt,name=fee_rate_bps,json=feeRateBps,proto3" json:"fee_rate_bps,omitempty"`
	FeeFixedAmount int64 `protobuf:"varint,15,opt,name=fee_fixed_amount,json=feeFixedAmount,proto3" json:"fee_fixed_amount,omitempty"`
	FeeAmount      int64 `protobuf:"varint,16,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	NetAmount      int64 `protobuf:"varint,17,opt,name=net_amount,json=netAmount,proto3" json:"net_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateOrderReq) GetMerchantOrderNo() string {
	if x != nil {
		return x.MerchantOrderNo
	}
	return ""
}

func (x *CreateOrderReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateOrderReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreateOrderReq) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *CreateOrderReq) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *CreateOrderReq) GetPayinType() string {
	if x != nil {
		return x.PayinType
	}
	return ""
}

func (x *CreateOrderReq) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *CreateOrderReq) GetPayinProductId() int64 {
	if x != nil {
		return x.PayinProductId
	}
	return 0
}

func (x *CreateOrderReq) GetPayinProductCode() string {
	if x != nil {
		return x.PayinProductCode
	}
	return ""
}

func (x *CreateOrderReq) GetChannelLocked() int32 {
	if x != nil {
		return x.ChannelLocked
	}
	return 0
}

func (x *CreateOrderReq) GetFeeMode() int64 {
	if x != nil {
		return x.FeeMode
	}
	return 0
}

func (x *CreateOrderReq) GetFeeRateBps() int64 {
	if x != nil {
		return x.FeeRateBps
	}
	return 0
}

func (x *CreateOrderReq) GetFeeFixedAmount() int64 {
	if x != nil {
		return x.FeeFixedAmount
	}
	return 0
}

func (x *CreateOrderReq) GetFeeAmount() int64 {
	if x != nil {
		return x.FeeAmount
	}
	return 0
}

func (x *CreateOrderReq) GetNetAmount() int64 {
	if x != nil {
		return x.NetAmount
	}
	return 0
}

type CreateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Existed       bool                   `protobuf:"varint,2,opt,name=existed,proto3" json:"existed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResp) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateOrderResp) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

type GetOrderReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MerchantId      string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	OrderNo         string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	MerchantOrderNo string                 `protobuf:"bytes,3,opt,name=merchant_order_no,json=merchantOrderNo,proto3" json:"merchant_order_no,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetOrderReq) Reset() {
	*x = GetOrderReq{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReq) ProtoMessage() {}

func (x *GetOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReq.ProtoReflect.Descriptor instead.
func (*GetOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetOrderReq) GetMerchantOrderNo() string {
	if x != nil {
		return x.MerchantOrderNo
	}
	return ""
}

type GetOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResp) Reset() {
	*x = GetOrderResp{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResp) ProtoMessage() {}

func (x *GetOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResp.ProtoReflect.Descriptor instead.
func (*GetOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderResp) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

type MarkPaidReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderNo         string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PaidAmount      int64                  `protobuf:"varint,2,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	UpstreamTradeNo string                 `protobuf:"bytes,3,opt,name=upstream_trade_no,json=upstreamTradeNo,proto3" json:"upstream_trade_no,omitempty"`
	ChannelId       int64                  `protobuf:"varint,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkPaidReq) Reset() {
	*x = MarkPaidReq{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPaidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPaidReq) ProtoMessage() {}

func (x *MarkPaidReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPaidReq.ProtoReflect.Descriptor instead.
func (*MarkPaidReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *MarkPaidReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *MarkPaidReq) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *MarkPaidReq) GetUpstreamTradeNo() string {
	if x != nil {
		return x.UpstreamTradeNo
	}
	return ""
}

func (x *MarkPaidReq) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type MarkPaidResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPaidResp) Reset() {
	*x = MarkPaidResp{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPaidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPaidResp) ProtoMessage() {}

func (x *MarkPaidResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPaidResp.ProtoReflect.Descriptor instead.
func (*MarkPaidResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *MarkPaidResp) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

type OrderInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderNo          string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	MerchantId       string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MerchantOrderNo  string                 `protobuf:"bytes,3,opt,name=merchant_order_no,json=merchantOrderNo,proto3" json:"merchant_order_no,omitempty"`
	Amount           int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency         string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	ChannelId        int64                  `protobuf:"varint,7,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ReturnUrl        string                 `protobuf:"bytes,10,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	NotifyUrl        string                 `protobuf:"bytes,11,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	UpstreamTradeNo  string                 `protobuf:"bytes,12,opt,name=upstream_trade_no,json=upstreamTradeNo,proto3" json:"upstream_trade_no,omitempty"`
	PaidAmount       int64                  `protobuf:"varint,13,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	PayinProductId   int64                  `protobuf:"varint,14,opt,name=payin_product_id,json=payinProductId,proto3" json:"payin_product_id,omitempty"`
	PayinProductCode string                 `protobuf:"bytes,15,opt,name=payin_product_code,json=payinProductCode,proto3" json:"payin_product_code,omitempty"`
	ChannelLocked    int32                  `protobuf:"varint,16,opt,name=channel_locked,json=channelLocked,proto3" json:"channel_locked,omitempty"`
	FeeMode          int64                  `protobuf:"varint,17,opt,name=fee_mode,json=feeMode,proto3" json:"fee_mode,omitempty"`
	FeeRateBps       int64                  `protobuf:"varint,18,opt,name=fee_rate_bps,json=feeRateBps,proto3" json:"fee_rate_bps,omitempty"`
	FeeFixedAmount   int64                  `protobuf:"varint,19,opt,name=fee_fixed_amount,json=feeFixedAmount,proto3" json:"fee_fixed_amount,omitempty"`
	FeeAmount        int64                  `protobuf:"varint,20,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	NetAmount        int64                  `protobuf:"varint,21,opt,name=net_amount,json=netAmount,proto3" json:"net_amount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *OrderInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderInfo) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *OrderInfo) GetMerchantOrderNo() string {
	if x != nil {
		return x.MerchantOrderNo
	}
	return ""
}

func (x *OrderInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *OrderInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderInfo) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *OrderInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *OrderInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *OrderInfo) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *OrderInfo) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *OrderInfo) GetUpstreamTradeNo() string {
	if x != nil {
		return x.UpstreamTradeNo
	}
	return ""
}

func (x *OrderInfo) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *OrderInfo) GetPayinProductId() int64 {
	if x != nil {
		return x.PayinProductId
	}
	return 0
}

func (x *OrderInfo) GetPayinProductCode() string {
	if x != nil {
		return x.PayinProductCode
	}
	return ""
}

func (x *OrderInfo) GetChannelLocked() int32 {
	if x != nil {
		return x.ChannelLocked
	}
	return 0
}

func (x *OrderInfo) GetFeeMode() int64 {
	if x != nil {
		return x.FeeMode
	}
	return 0
}

func (x *OrderInfo) GetFeeRateBps() int64 {
	if x != nil {
		return x.FeeRateBps
	}
	return 0
}

func (x *OrderInfo) GetFeeFixedAmount() int64 {
	if x != nil {
		return x.FeeFixedAmount
	}
	return 0
}

func (x *OrderInfo) GetFeeAmount() int64 {
	if x != nil {
		return x.FeeAmount
	}
	return 0
}

func (x *OrderInfo) GetNetAmount() int64 {
	if x != nil {
		return x.NetAmount
	}
	return 0
}

type ListOrdersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersReq) Reset() {
	*x = ListOrdersReq{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersReq) ProtoMessage() {}

func (x *ListOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersReq.ProtoReflect.Descriptor instead.
func (*ListOrdersReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrdersReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListOrdersReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListOrdersReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListOrdersReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListOrdersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderInfo           `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResp) Reset() {
	*x = ListOrdersResp{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResp) ProtoMessage() {}

func (x *ListOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResp.ProtoReflect.Descriptor instead.
func (*ListOrdersResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *ListOrdersResp) GetOrders() []*OrderInfo {
	if x != nil {
		return x.Orders
	}
	return nil
}

type TodaySummaryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodaySummaryReq) Reset() {
	*x = TodaySummaryReq{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodaySummaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodaySummaryReq) ProtoMessage() {}

func (x *TodaySummaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodaySummaryReq.ProtoReflect.Descriptor instead.
func (*TodaySummaryReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *TodaySummaryReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type TodaySummaryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalAmount   int64                  `protobuf:"varint,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	SuccessCount  int64                  `protobuf:"varint,3,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodaySummaryResp) Reset() {
	*x = TodaySummaryResp{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodaySummaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodaySummaryResp) ProtoMessage() {}

func (x *TodaySummaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodaySummaryResp.ProtoReflect.Descriptor instead.
func (*TodaySummaryResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *TodaySummaryResp) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *TodaySummaryResp) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *TodaySummaryResp) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

type PrepareTerminalPayReq struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OrderNo string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	// 用户在收银台选择的支付产品编码；为空则沿用订单已有编码
	PayinProductCode string `protobuf:"bytes,2,opt,name=payin_product_code,json=payinProductCode,proto3" json:"payin_product_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrepareTerminalPayReq) Reset() {
	*x = PrepareTerminalPayReq{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareTerminalPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareTerminalPayReq) ProtoMessage() {}

func (x *PrepareTerminalPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareTerminalPayReq.ProtoReflect.Descriptor instead.
func (*PrepareTerminalPayReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *PrepareTerminalPayReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PrepareTerminalPayReq) GetPayinProductCode() string {
	if x != nil {
		return x.PayinProductCode
	}
	return ""
}

type PrepareTerminalPayResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChannelId        int64                  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PayinProductId   int64                  `protobuf:"varint,2,opt,name=payin_product_id,json=payinProductId,proto3" json:"payin_product_id,omitempty"`
	PayinProductCode string                 `protobuf:"bytes,3,opt,name=payin_product_code,json=payinProductCode,proto3" json:"payin_product_code,omitempty"`
	// 跳转或二维码内容（mock 场景可与 pay_url 相同）
	PayUrl    string `protobuf:"bytes,4,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	QrPayload string `protobuf:"bytes,5,opt,name=qr_payload,json=qrPayload,proto3" json:"qr_payload,omitempty"`
	// mock | qr | redirect
	PayMode       string `protobuf:"bytes,6,opt,name=pay_mode,json=payMode,proto3" json:"pay_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareTerminalPayResp) Reset() {
	*x = PrepareTerminalPayResp{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareTerminalPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareTerminalPayResp) ProtoMessage() {}

func (x *PrepareTerminalPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareTerminalPayResp.ProtoReflect.Descriptor instead.
func (*PrepareTerminalPayResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *PrepareTerminalPayResp) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *PrepareTerminalPayResp) GetPayinProductId() int64 {
	if x != nil {
		return x.PayinProductId
	}
	return 0
}

func (x *PrepareTerminalPayResp) GetPayinProductCode() string {
	if x != nil {
		return x.PayinProductCode
	}
	return ""
}

func (x *PrepareTerminalPayResp) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *PrepareTerminalPayResp) GetQrPayload() string {
	if x != nil {
		return x.QrPayload
	}
	return ""
}

func (x *PrepareTerminalPayResp) GetPayMode() string {
	if x != nil {
		return x.PayMode
	}
	return ""
}

type AdminTodayOverviewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminTodayOverviewReq) Reset() {
	*x = AdminTodayOverviewReq{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminTodayOverviewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminTodayOverviewReq) ProtoMessage() {}

func (x *AdminTodayOverviewReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminTodayOverviewReq.ProtoReflect.Descriptor instead.
func (*AdminTodayOverviewReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

type AdminStatsTotals struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	OrderCount             int64                  `protobuf:"varint,1,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	PaidAmount             int64                  `protobuf:"varint,2,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	PaidCount              int64                  `protobuf:"varint,3,opt,name=paid_count,json=paidCount,proto3" json:"paid_count,omitempty"`
	FailedCount            int64                  `protobuf:"varint,4,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	PendingCount           int64                  `protobuf:"varint,5,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	ClosedCount            int64                  `protobuf:"varint,6,opt,name=closed_count,json=closedCount,proto3" json:"closed_count,omitempty"`
	ConversionRatePct      float64                `protobuf:"fixed64,7,opt,name=conversion_rate_pct,json=conversionRatePct,proto3" json:"conversion_rate_pct,omitempty"`
	TerminalSuccessRatePct float64                `protobuf:"fixed64,8,opt,name=terminal_success_rate_pct,json=terminalSuccessRatePct,proto3" json:"terminal_success_rate_pct,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminStatsTotals) Reset() {
	*x = AdminStatsTotals{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStatsTotals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStatsTotals) ProtoMessage() {}

func (x *AdminStatsTotals) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStatsTotals.ProtoReflect.Descriptor instead.
func (*AdminStatsTotals) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *AdminStatsTotals) GetOrderCount() int64 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *AdminStatsTotals) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *AdminStatsTotals) GetPaidCount() int64 {
	if x != nil {
		return x.PaidCount
	}
	return 0
}

func (x *AdminStatsTotals) GetFailedCount() int64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *AdminStatsTotals) GetPendingCount() int64 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

func (x *AdminStatsTotals) GetClosedCount() int64 {
	if x != nil {
		return x.ClosedCount
	}
	return 0
}

func (x *AdminStatsTotals) GetConversionRatePct() float64 {
	if x != nil {
		return x.ConversionRatePct
	}
	return 0
}

func (x *AdminStatsTotals) GetTerminalSuccessRatePct() float64 {
	if x != nil {
		return x.TerminalSuccessRatePct
	}
	return 0
}

type AdminStatsProductRow struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ProductCode            string                 `protobuf:"bytes,1,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	ProductName            string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	OrderCount             int64                  `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	PaidAmount             int64                  `protobuf:"varint,4,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	PaidCount              int64                  `protobuf:"varint,5,opt,name=paid_count,json=paidCount,proto3" json:"paid_count,omitempty"`
	FailedCount            int64                  `protobuf:"varint,6,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	ConversionRatePct      float64                `protobuf:"fixed64,7,opt,name=conversion_rate_pct,json=conversionRatePct,proto3" json:"conversion_rate_pct,omitempty"`
	TerminalSuccessRatePct float64                `protobuf:"fixed64,8,opt,name=terminal_success_rate_pct,json=terminalSuccessRatePct,proto3" json:"terminal_success_rate_pct,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminStatsProductRow) Reset() {
	*x = AdminStatsProductRow{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStatsProductRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStatsProductRow) ProtoMessage() {}

func (x *AdminStatsProductRow) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStatsProductRow.ProtoReflect.Descriptor instead.
func (*AdminStatsProductRow) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{16}
}

func (x *AdminStatsProductRow) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *AdminStatsProductRow) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *AdminStatsProductRow) GetOrderCount() int64 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *AdminStatsProductRow) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *AdminStatsProductRow) GetPaidCount() int64 {
	if x != nil {
		return x.PaidCount
	}
	return 0
}

func (x *AdminStatsProductRow) GetFailedCount() int64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *AdminStatsProductRow) GetConversionRatePct() float64 {
	if x != nil {
		return x.ConversionRatePct
	}
	return 0
}

func (x *AdminStatsProductRow) GetTerminalSuccessRatePct() float64 {
	if x != nil {
		return x.TerminalSuccessRatePct
	}
	return 0
}

type AdminStatsChannelRow struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ChannelId              int64                  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelName            string                 `protobuf:"bytes,2,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	OrderCount             int64                  `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	PaidAmount             int64                  `protobuf:"varint,4,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	PaidCount              int64                  `protobuf:"varint,5,opt,name=paid_count,json=paidCount,proto3" json:"paid_count,omitempty"`
	FailedCount            int64                  `protobuf:"varint,6,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	ConversionRatePct      float64                `protobuf:"fixed64,7,opt,name=conversion_rate_pct,json=conversionRatePct,proto3" json:"conversion_rate_pct,omitempty"`
	TerminalSuccessRatePct float64                `protobuf:"fixed64,8,opt,name=terminal_success_rate_pct,json=terminalSuccessRatePct,proto3" json:"terminal_success_rate_pct,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminStatsChannelRow) Reset() {
	*x = AdminStatsChannelRow{}
	mi := &file_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStatsChannelRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStatsChannelRow) ProtoMessage() {}

func (x *AdminStatsChannelRow) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStatsChannelRow.ProtoReflect.Descriptor instead.
func (*AdminStatsChannelRow) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{17}
}

func (x *AdminStatsChannelRow) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *AdminStatsChannelRow) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *AdminStatsChannelRow) GetOrderCount() int64 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *AdminStatsChannelRow) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *AdminStatsChannelRow) GetPaidCount() int64 {
	if x != nil {
		return x.PaidCount
	}
	return 0
}

func (x *AdminStatsChannelRow) GetFailedCount() int64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *AdminStatsChannelRow) GetConversionRatePct() float64 {
	if x != nil {
		return x.ConversionRatePct
	}
	return 0
}

func (x *AdminStatsChannelRow) GetTerminalSuccessRatePct() float64 {
	if x != nil {
		return x.TerminalSuccessRatePct
	}
	return 0
}

type AdminTodayOverviewResp struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Range           string                  `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	Totals          *AdminStatsTotals       `protobuf:"bytes,2,opt,name=totals,proto3" json:"totals,omitempty"`
	ByPayinProduct  []*AdminStatsProductRow `protobuf:"bytes,3,rep,name=by_payin_product,json=byPayinProduct,proto3" json:"by_payin_product,omitempty"`
	ByChannel       []*AdminStatsChannelRow `protobuf:"bytes,4,rep,name=by_channel,json=byChannel,proto3" json:"by_channel,omitempty"`
	EnabledChannels int64                   `protobuf:"varint,5,opt,name=enabled_channels,json=enabledChannels,proto3" json:"enabled_channels,omitempty"`
	FusedChannels   int64                   `protobuf:"varint,6,opt,name=fused_channels,json=fusedChannels,proto3" json:"fused_channels,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminTodayOverviewResp) Reset() {
	*x = AdminTodayOverviewResp{}
	mi := &file_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminTodayOverviewResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminTodayOverviewResp) ProtoMessage() {}

func (x *AdminTodayOverviewResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminTodayOverviewResp.ProtoReflect.Descriptor instead.
func (*AdminTodayOverviewResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{18}
}

func (x *AdminTodayOverviewResp) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *AdminTodayOverviewResp) GetTotals() *AdminStatsTotals {
	if x != nil {
		return x.Totals
	}
	return nil
}

func (x *AdminTodayOverviewResp) GetByPayinProduct() []*AdminStatsProductRow {
	if x != nil {
		return x.ByPayinProduct
	}
	return nil
}

func (x *AdminTodayOverviewResp) GetByChannel() []*AdminStatsChannelRow {
	if x != nil {
		return x.ByChannel
	}
	return nil
}

func (x *AdminTodayOverviewResp) GetEnabledChannels() int64 {
	if x != nil {
		return x.EnabledChannels
	}
	return 0
}

func (x *AdminTodayOverviewResp) GetFusedChannels() int64 {
	if x != nil {
		return x.FusedChannels
	}
	return 0
}

type ListMerchantNotifyLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantNotifyLogsReq) Reset() {
	*x = ListMerchantNotifyLogsReq{}
	mi := &file_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantNotifyLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantNotifyLogsReq) ProtoMessage() {}

func (x *ListMerchantNotifyLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantNotifyLogsReq.ProtoReflect.Descriptor instead.
func (*ListMerchantNotifyLogsReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{19}
}

func (x *ListMerchantNotifyLogsReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListMerchantNotifyLogsReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ListMerchantNotifyLogsReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MerchantNotifyLogItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NotifyUrl     string                 `protobuf:"bytes,2,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	Attempt       int64                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	HttpStatus    int64                  `protobuf:"varint,4,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	ResponseBody  string                 `protobuf:"bytes,5,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,6,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantNotifyLogItem) Reset() {
	*x = MerchantNotifyLogItem{}
	mi := &file_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantNotifyLogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantNotifyLogItem) ProtoMessage() {}

func (x *MerchantNotifyLogItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantNotifyLogItem.ProtoReflect.Descriptor instead.
func (*MerchantNotifyLogItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{20}
}

func (x *MerchantNotifyLogItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MerchantNotifyLogItem) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *MerchantNotifyLogItem) GetAttempt() int64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *MerchantNotifyLogItem) GetHttpStatus() int64 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *MerchantNotifyLogItem) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *MerchantNotifyLogItem) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *MerchantNotifyLogItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListMerchantNotifyLogsResp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Logs          []*MerchantNotifyLogItem `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantNotifyLogsResp) Reset() {
	*x = ListMerchantNotifyLogsResp{}
	mi := &file_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantNotifyLogsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantNotifyLogsResp) ProtoMessage() {}

func (x *ListMerchantNotifyLogsResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantNotifyLogsResp.ProtoReflect.Descriptor instead.
func (*ListMerchantNotifyLogsResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{21}
}

func (x *ListMerchantNotifyLogsResp) GetLogs() []*MerchantNotifyLogItem {
	if x != nil {
		return x.Logs
	}
	return nil
}

type AdminListOrdersReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	MerchantId string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Keyword    string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	// 未设置或 -1：不按状态筛选；0～3 与订单状态一致
	Status        *int32 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Limit         int64  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListOrdersReq) Reset() {
	*x = AdminListOrdersReq{}
	mi := &file_order_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListOrdersReq) ProtoMessage() {}

func (x *AdminListOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListOrdersReq.ProtoReflect.Descriptor instead.
func (*AdminListOrdersReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{22}
}

func (x *AdminListOrdersReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *AdminListOrdersReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *AdminListOrdersReq) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *AdminListOrdersReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AdminListOrdersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderInfo           `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListOrdersResp) Reset() {
	*x = AdminListOrdersResp{}
	mi := &file_order_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListOrdersResp) ProtoMessage() {}

func (x *AdminListOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListOrdersResp.ProtoReflect.Descriptor instead.
func (*AdminListOrdersResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{23}
}

func (x *AdminListOrdersResp) GetOrders() []*OrderInfo {
	if x != nil {
		return x.Orders
	}
	return nil
}

type AdminDayOverviewReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 自然日 YYYY-MM-DD（服务器本地时区）
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// 为空表示全站；非空仅统计该商户
	MerchantId    string `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDayOverviewReq) Reset() {
	*x = AdminDayOverviewReq{}
	mi := &file_order_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDayOverviewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDayOverviewReq) ProtoMessage() {}

func (x *AdminDayOverviewReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDayOverviewReq.ProtoReflect.Descriptor instead.
func (*AdminDayOverviewReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{24}
}

func (x *AdminDayOverviewReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AdminDayOverviewReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type AdminDayOverviewResp struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Date           string                  `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Totals         *AdminStatsTotals       `protobuf:"bytes,2,opt,name=totals,proto3" json:"totals,omitempty"`
	ByPayinProduct []*AdminStatsProductRow `protobuf:"bytes,3,rep,name=by_payin_product,json=byPayinProduct,proto3" json:"by_payin_product,omitempty"`
	ByChannel      []*AdminStatsChannelRow `protobuf:"bytes,4,rep,name=by_channel,json=byChannel,proto3" json:"by_channel,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminDayOverviewResp) Reset() {
	*x = AdminDayOverviewResp{}
	mi := &file_order_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDayOverviewResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDayOverviewResp) ProtoMessage() {}

func (x *AdminDayOverviewResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDayOverviewResp.ProtoReflect.Descriptor instead.
func (*AdminDayOverviewResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{25}
}

func (x *AdminDayOverviewResp) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AdminDayOverviewResp) GetTotals() *AdminStatsTotals {
	if x != nil {
		return x.Totals
	}
	return nil
}

func (x *AdminDayOverviewResp) GetByPayinProduct() []*AdminStatsProductRow {
	if x != nil {
		return x.ByPayinProduct
	}
	return nil
}

func (x *AdminDayOverviewResp) GetByChannel() []*AdminStatsChannelRow {
	if x != nil {
		return x.ByChannel
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"\xd6\x03\n" +
	"\x14CreatePayoutOrderReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12*\n" +
	"\x11merchant_order_no\x18\x02 \x01(\tR\x0fmerchantOrderNo\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x05 \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x06 \x01(\x03R\tchannelId\x12*\n" +
	"\x11payout_product_id\x18\a \x01(\x03R\x0fpayoutProductId\x12.\n" +
	"\x13payout_product_code\x18\b \x01(\tR\x11payoutProductCode\x12\x19\n" +
	"\bfee_mode\x18\t \x01(\x03R\afeeMode\x12 \n" +
	"\ffee_rate_bps\x18\n" +
	" \x01(\x03R\n" +
	"feeRateBps\x12(\n" +
	"\x10fee_fixed_amount\x18\v \x01(\x03R\x0efeeFixedAmount\x12\x1d\n" +
	"\n" +
	"fee_amount\x18\f \x01(\x03R\tfeeAmount\x12\x1d\n" +
	"\n" +
	"net_amount\x18\r \x01(\x03R\tnetAmount\"\xcb\x04\n" +
	"\x0eCreateOrderReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12*\n" +
	"\x11merchant_order_no\x18\x02 \x01(\tR\x0fmerchantOrderNo\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"return_url\x18\x06 \x01(\tR\treturnUrl\x12\x1d\n" +
	"\n" +
	"notify_url\x18\a \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"payin_type\x18\b \x01(\tR\tpayinType\x12\x1d\n" +
	"\n" +
	"channel_id\x18\t \x01(\x03R\tchannelId\x12(\n" +
	"\x10payin_product_id\x18\n" +
	" \x01(\x03R\x0epayinProductId\x12,\n" +
	"\x12payin_product_code\x18\v \x01(\tR\x10payinProductCode\x12%\n" +
	"\x0echannel_locked\x18\f \x01(\x05R\rchannelLocked\x12\x19\n" +
	"\bfee_mode\x18\r \x01(\x03R\afeeMode\x12 \n" +
	"\ffee_rate_bps\x18\x0e \x01(\x03R\n" +
	"feeRateBps\x12(\n" +
	"\x10fee_fixed_amount\x18\x0f \x01(\x03R\x0efeeFixedAmount\x12\x1d\n" +
	"\n" +
	"fee_amount\x18\x10 \x01(\x03R\tfeeAmount\x12\x1d\n" +
	"\n" +
	"net_amount\x18\x11 \x01(\x03R\tnetAmount\"S\n" +
	"\x0fCreateOrderResp\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.order.OrderInfoR\x05order\x12\x18\n" +
	"\aexisted\x18\x02 \x01(\bR\aexisted\"u\n" +
	"\vGetOrderReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12*\n" +
	"\x11merchant_order_no\x18\x03 \x01(\tR\x0fmerchantOrderNo\"6\n" +
	"\fGetOrderResp\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.order.OrderInfoR\x05order\"\x94\x01\n" +
	"\vMarkPaidReq\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vpaid_amount\x18\x02 \x01(\x03R\n" +
	"paidAmount\x12*\n" +
	"\x11upstream_trade_no\x18\x03 \x01(\tR\x0fupstreamTradeNo\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\x03R\tchannelId\"(\n" +
	"\fMarkPaidResp\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\"\xcb\x05\n" +
	"\tOrderInfo\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12*\n" +
	"\x11merchant_order_no\x18\x03 \x01(\tR\x0fmerchantOrderNo\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"channel_id\x18\a \x01(\x03R\tchannelId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"return_url\x18\n" +
	" \x01(\tR\treturnUrl\x12\x1d\n" +
	"\n" +
	"notify_url\x18\v \x01(\tR\tnotifyUrl\x12*\n" +
	"\x11upstream_trade_no\x18\f \x01(\tR\x0fupstreamTradeNo\x12\x1f\n" +
	"\vpaid_amount\x18\r \x01(\x03R\n" +
	"paidAmount\x12(\n" +
	"\x10payin_product_id\x18\x0e \x01(\x03R\x0epayinProductId\x12,\n" +
	"\x12payin_product_code\x18\x0f \x01(\tR\x10payinProductCode\x12%\n" +
	"\x0echannel_locked\x18\x10 \x01(\x05R\rchannelLocked\x12\x19\n" +
	"\bfee_mode\x18\x11 \x01(\x03R\afeeMode\x12 \n" +
	"\ffee_rate_bps\x18\x12 \x01(\x03R\n" +
	"feeRateBps\x12(\n" +
	"\x10fee_fixed_amount\x18\x13 \x01(\x03R\x0efeeFixedAmount\x12\x1d\n" +
	"\n" +
	"fee_amount\x18\x14 \x01(\x03R\tfeeAmount\x12\x1d\n" +
	"\n" +
	"net_amount\x18\x15 \x01(\x03R\tnetAmount\"x\n" +
	"\rListOrdersReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\":\n" +
	"\x0eListOrdersResp\x12(\n" +
	"\x06orders\x18\x01 \x03(\v2\x10.order.OrderInfoR\x06orders\"2\n" +
	"\x0fTodaySummaryReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"{\n" +
	"\x10TodaySummaryResp\x12!\n" +
	"\ftotal_amount\x18\x01 \x01(\x03R\vtotalAmount\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12#\n" +
	"\rsuccess_count\x18\x03 \x01(\x03R\fsuccessCount\"`\n" +
	"\x15PrepareTerminalPayReq\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12,\n" +
	"\x12payin_product_code\x18\x02 \x01(\tR\x10payinProductCode\"\xe2\x01\n" +
	"\x16PrepareTerminalPayResp\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x03R\tchannelId\x12(\n" +
	"\x10payin_product_id\x18\x02 \x01(\x03R\x0epayinProductId\x12,\n" +
	"\x12payin_product_code\x18\x03 \x01(\tR\x10payinProductCode\x12\x17\n" +
	"\apay_url\x18\x04 \x01(\tR\x06payUrl\x12\x1d\n" +
	"\n" +
	"qr_payload\x18\x05 \x01(\tR\tqrPayload\x12\x19\n" +
	"\bpay_mode\x18\x06 \x01(\tR\apayMode\"\x17\n" +
	"\x15AdminTodayOverviewReq\"\xc9\x02\n" +
	"\x10AdminStatsTotals\x12\x1f\n" +
	"\vorder_count\x18\x01 \x01(\x03R\n" +
	"orderCount\x12\x1f\n" +
	"\vpaid_amount\x18\x02 \x01(\x03R\n" +
	"paidAmount\x12\x1d\n" +
	"\n" +
	"paid_count\x18\x03 \x01(\x03R\tpaidCount\x12!\n" +
	"\ffailed_count\x18\x04 \x01(\x03R\vfailedCount\x12#\n" +
	"\rpending_count\x18\x05 \x01(\x03R\fpendingCount\x12!\n" +
	"\fclosed_count\x18\x06 \x01(\x03R\vclosedCount\x12.\n" +
	"\x13conversion_rate_pct\x18\a \x01(\x01R\x11conversionRatePct\x129\n" +
	"\x19terminal_success_rate_pct\x18\b \x01(\x01R\x16terminalSuccessRatePct\"\xcb\x02\n" +
	"\x14AdminStatsProductRow\x12!\n" +
	"\fproduct_code\x18\x01 \x01(\tR\vproductCode\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1f\n" +
	"\vorder_count\x18\x03 \x01(\x03R\n" +
	"orderCount\x12\x1f\n" +
	"\vpaid_amount\x18\x04 \x01(\x03R\n" +
	"paidAmount\x12\x1d\n" +
	"\n" +
	"paid_count\x18\x05 \x01(\x03R\tpaidCount\x12!\n" +
	"\ffailed_count\x18\x06 \x01(\x03R\vfailedCount\x12.\n" +
	"\x13conversion_rate_pct\x18\a \x01(\x01R\x11conversionRatePct\x129\n" +
	"\x19terminal_success_rate_pct\x18\b \x01(\x01R\x16terminalSuccessRatePct\"\xc7\x02\n" +
	"\x14AdminStatsChannelRow\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x03R\tchannelId\x12!\n" +
	"\fchannel_name\x18\x02 \x01(\tR\vchannelName\x12\x1f\n" +
	"\vorder_count\x18\x03 \x01(\x03R\n" +
	"orderCount\x12\x1f\n" +
	"\vpaid_amount\x18\x04 \x01(\x03R\n" +
	"paidAmount\x12\x1d\n" +
	"\n" +
	"paid_count\x18\x05 \x01(\x03R\tpaidCount\x12!\n" +
	"\ffailed_count\x18\x06 \x01(\x03R\vfailedCount\x12.\n" +
	"\x13conversion_rate_pct\x18\a \x01(\x01R\x11conversionRatePct\x129\n" +
	"\x19terminal_success_rate_pct\x18\b \x01(\x01R\x16terminalSuccessRatePct\"\xb4\x02\n" +
	"\x16AdminTodayOverviewResp\x12\x14\n" +
	"\x05range\x18\x01 \x01(\tR\x05range\x12/\n" +
	"\x06totals\x18\x02 \x01(\v2\x17.order.AdminStatsTotalsR\x06totals\x12E\n" +
	"\x10by_payin_product\x18\x03 \x03(\v2\x1b.order.AdminStatsProductRowR\x0ebyPayinProduct\x12:\n" +
	"\n" +
	"by_channel\x18\x04 \x03(\v2\x1b.order.AdminStatsChannelRowR\tbyChannel\x12)\n" +
	"\x10enabled_channels\x18\x05 \x01(\x03R\x0fenabledChannels\x12%\n" +
	"\x0efused_channels\x18\x06 \x01(\x03R\rfusedChannels\"m\n" +
	"\x19ListMerchantNotifyLogsReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"\xe2\x01\n" +
	"\x15MerchantNotifyLogItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x02 \x01(\tR\tnotifyUrl\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x03R\aattempt\x12\x1f\n" +
	"\vhttp_status\x18\x04 \x01(\x03R\n" +
	"httpStatus\x12#\n" +
	"\rresponse_body\x18\x05 \x01(\tR\fresponseBody\x12\x1b\n" +
	"\terror_msg\x18\x06 \x01(\tR\berrorMsg\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"N\n" +
	"\x1aListMerchantNotifyLogsResp\x120\n" +
	"\x04logs\x18\x01 \x03(\v2\x1c.order.MerchantNotifyLogItemR\x04logs\"\x8d\x01\n" +
	"\x12AdminListOrdersReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x05H\x00R\x06status\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limitB\t\n" +
	"\a_status\"?\n" +
	"\x13AdminListOrdersResp\x12(\n" +
	"\x06orders\x18\x01 \x03(\v2\x10.order.OrderInfoR\x06orders\"J\n" +
	"\x13AdminDayOverviewReq\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\"\xde\x01\n" +
	"\x14AdminDayOverviewResp\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12/\n" +
	"\x06totals\x18\x02 \x01(\v2\x17.order.AdminStatsTotalsR\x06totals\x12E\n" +
	"\x10by_payin_product\x18\x03 \x03(\v2\x1b.order.AdminStatsProductRowR\x0ebyPayinProduct\x12:\n" +
	"\n" +
	"by_channel\x18\x04 \x03(\v2\x1b.order.AdminStatsChannelRowR\tbyChannel2\xe3\a\n" +
	"\x05Order\x12<\n" +
	"\vCreateOrder\x12\x15.order.CreateOrderReq\x1a\x16.order.CreateOrderResp\x123\n" +
	"\bGetOrder\x12\x12.order.GetOrderReq\x1a\x13.order.GetOrderResp\x123\n" +
	"\bMarkPaid\x12\x12.order.MarkPaidReq\x1a\x13.order.MarkPaidResp\x12H\n" +
	"\x11CreatePayoutOrder\x12\x1b.order.CreatePayoutOrderReq\x1a\x16.order.CreateOrderResp\x129\n" +
	"\x0eGetPayoutOrder\x12\x12.order.GetOrderReq\x1a\x13.order.GetOrderResp\x12<\n" +
	"\rListPayOrders\x12\x14.order.ListOrdersReq\x1a\x15.order.ListOrdersResp\x12?\n" +
	"\x10ListPayoutOrders\x12\x14.order.ListOrdersReq\x1a\x15.order.ListOrdersResp\x12?\n" +
	"\fTodaySummary\x12\x16.order.TodaySummaryReq\x1a\x17.order.TodaySummaryResp\x12Q\n" +
	"\x12PrepareTerminalPay\x12\x1c.order.PrepareTerminalPayReq\x1a\x1d.order.PrepareTerminalPayResp\x12Q\n" +
	"\x12AdminTodayOverview\x12\x1c.order.AdminTodayOverviewReq\x1a\x1d.order.AdminTodayOverviewResp\x12]\n" +
	"\x16ListMerchantNotifyLogs\x12 .order.ListMerchantNotifyLogsReq\x1a!.order.ListMerchantNotifyLogsResp\x12K\n" +
	"\x12AdminListPayOrders\x12\x19.order.AdminListOrdersReq\x1a\x1a.order.AdminListOrdersResp\x12N\n" +
	"\x15AdminListPayoutOrders\x12\x19.order.AdminListOrdersReq\x1a\x1a.order.AdminListOrdersResp\x12K\n" +
	"\x10AdminDayOverview\x12\x1a.order.AdminDayOverviewReq\x1a\x1b.order.AdminDayOverviewRespB.Z,github.com/gloopai/pay/common/pb/order;orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_order_proto_goTypes = []any{
	(*CreatePayoutOrderReq)(nil),       // 0: order.CreatePayoutOrderReq
	(*CreateOrderReq)(nil),             // 1: order.CreateOrderReq
	(*CreateOrderResp)(nil),            // 2: order.CreateOrderResp
	(*GetOrderReq)(nil),                // 3: order.GetOrderReq
	(*GetOrderResp)(nil),               // 4: order.GetOrderResp
	(*MarkPaidReq)(nil),                // 5: order.MarkPaidReq
	(*MarkPaidResp)(nil),               // 6: order.MarkPaidResp
	(*OrderInfo)(nil),                  // 7: order.OrderInfo
	(*ListOrdersReq)(nil),              // 8: order.ListOrdersReq
	(*ListOrdersResp)(nil),             // 9: order.ListOrdersResp
	(*TodaySummaryReq)(nil),            // 10: order.TodaySummaryReq
	(*TodaySummaryResp)(nil),           // 11: order.TodaySummaryResp
	(*PrepareTerminalPayReq)(nil),      // 12: order.PrepareTerminalPayReq
	(*PrepareTerminalPayResp)(nil),     // 13: order.PrepareTerminalPayResp
	(*AdminTodayOverviewReq)(nil),      // 14: order.AdminTodayOverviewReq
	(*AdminStatsTotals)(nil),           // 15: order.AdminStatsTotals
	(*AdminStatsProductRow)(nil),       // 16: order.AdminStatsProductRow
	(*AdminStatsChannelRow)(nil),       // 17: order.AdminStatsChannelRow
	(*AdminTodayOverviewResp)(nil),     // 18: order.AdminTodayOverviewResp
	(*ListMerchantNotifyLogsReq)(nil),  // 19: order.ListMerchantNotifyLogsReq
	(*MerchantNotifyLogItem)(nil),      // 20: order.MerchantNotifyLogItem
	(*ListMerchantNotifyLogsResp)(nil), // 21: order.ListMerchantNotifyLogsResp
	(*AdminListOrdersReq)(nil),         // 22: order.AdminListOrdersReq
	(*AdminListOrdersResp)(nil),        // 23: order.AdminListOrdersResp
	(*AdminDayOverviewReq)(nil),        // 24: order.AdminDayOverviewReq
	(*AdminDayOverviewResp)(nil),       // 25: order.AdminDayOverviewResp
}
var file_order_proto_depIdxs = []int32{
	7,  // 0: order.CreateOrderResp.order:type_name -> order.OrderInfo
	7,  // 1: order.GetOrderResp.order:type_name -> order.OrderInfo
	7,  // 2: order.ListOrdersResp.orders:type_name -> order.OrderInfo
	15, // 3: order.AdminTodayOverviewResp.totals:type_name -> order.AdminStatsTotals
	16, // 4: order.AdminTodayOverviewResp.by_payin_product:type_name -> order.AdminStatsProductRow
	17, // 5: order.AdminTodayOverviewResp.by_channel:type_name -> order.AdminStatsChannelRow
	20, // 6: order.ListMerchantNotifyLogsResp.logs:type_name -> order.MerchantNotifyLogItem
	7,  // 7: order.AdminListOrdersResp.orders:type_name -> order.OrderInfo
	15, // 8: order.AdminDayOverviewResp.totals:type_name -> order.AdminStatsTotals
	16, // 9: order.AdminDayOverviewResp.by_payin_product:type_name -> order.AdminStatsProductRow
	17, // 10: order.AdminDayOverviewResp.by_channel:type_name -> order.AdminStatsChannelRow
	1,  // 11: order.Order.CreateOrder:input_type -> order.CreateOrderReq
	3,  // 12: order.Order.GetOrder:input_type -> order.GetOrderReq
	5,  // 13: order.Order.MarkPaid:input_type -> order.MarkPaidReq
	0,  // 14: order.Order.CreatePayoutOrder:input_type -> order.CreatePayoutOrderReq
	3,  // 15: order.Order.GetPayoutOrder:input_type -> order.GetOrderReq
	8,  // 16: order.Order.ListPayOrders:input_type -> order.ListOrdersReq
	8,  // 17: order.Order.ListPayoutOrders:input_type -> order.ListOrdersReq
	10, // 18: order.Order.TodaySummary:input_type -> order.TodaySummaryReq
	12, // 19: order.Order.PrepareTerminalPay:input_type -> order.PrepareTerminalPayReq
	14, // 20: order.Order.AdminTodayOverview:input_type -> order.AdminTodayOverviewReq
	19, // 21: order.Order.ListMerchantNotifyLogs:input_type -> order.ListMerchantNotifyLogsReq
	22, // 22: order.Order.AdminListPayOrders:input_type -> order.AdminListOrdersReq
	22, // 23: order.Order.AdminListPayoutOrders:input_type -> order.AdminListOrdersReq
	24, // 24: order.Order.AdminDayOverview:input_type -> order.AdminDayOverviewReq
	2,  // 25: order.Order.CreateOrder:output_type -> order.CreateOrderResp
	4,  // 26: order.Order.GetOrder:output_type -> order.GetOrderResp
	6,  // 27: order.Order.MarkPaid:output_type -> order.MarkPaidResp
	2,  // 28: order.Order.CreatePayoutOrder:output_type -> order.CreateOrderResp
	4,  // 29: order.Order.GetPayoutOrder:output_type -> order.GetOrderResp
	9,  // 30: order.Order.ListPayOrders:output_type -> order.ListOrdersResp
	9,  // 31: order.Order.ListPayoutOrders:output_type -> order.ListOrdersResp
	11, // 32: order.Order.TodaySummary:output_type -> order.TodaySummaryResp
	13, // 33: order.Order.PrepareTerminalPay:output_type -> order.PrepareTerminalPayResp
	18, // 34: order.Order.AdminTodayOverview:output_type -> order.AdminTodayOverviewResp
	21, // 35: order.Order.ListMerchantNotifyLogs:output_type -> order.ListMerchantNotifyLogsResp
	23, // 36: order.Order.AdminListPayOrders:output_type -> order.AdminListOrdersResp
	23, // 37: order.Order.AdminListPayoutOrders:output_type -> order.AdminListOrdersResp
	25, // 38: order.Order.AdminDayOverview:output_type -> order.AdminDayOverviewResp
	25, // [25:39] is the sub-list for method output_type
	11, // [11:25] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	file_order_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
