// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	adminhandler "github.com/gloopai/pay/gateway/internal/handler/admin"
	checkouthandler "github.com/gloopai/pay/gateway/internal/handler/checkout"
	merchanthandler "github.com/gloopai/pay/gateway/internal/handler/merchant"
	"github.com/gloopai/pay/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MerchantSignMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/v1/pay/order",
					Handler: checkouthandler.CreateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/pay/query",
					Handler: checkouthandler.QueryOrderHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MerchantConsoleAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/v1/merchant/summary",
					Handler: merchanthandler.MerchantSummaryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/merchant/stats/by_product",
					Handler: merchanthandler.MerchantProductStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/merchant/orders",
					Handler: merchanthandler.MerchantOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/merchant/fund_logs",
					Handler: merchanthandler.MerchantFundLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/merchant/order/detail",
					Handler: merchanthandler.MerchantOrderDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/v1/merchant/order/retry_notify",
					Handler: merchanthandler.MerchantRetryNotifyHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/v1/merchant/logout",
					Handler: merchanthandler.MerchantLogoutHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/v1/merchant/login",
				Handler: merchanthandler.MerchantLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/admin/login",
				Handler: adminhandler.AdminLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/v1/callback/notify",
				Handler: checkouthandler.UpstreamNotifyHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/v1/terminal/order",
				Handler: checkouthandler.TerminalOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/terminal/pay",
				Handler: checkouthandler.TerminalPayHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/v1/admin/logout",
					Handler: adminhandler.AdminLogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/admin/channels",
					Handler: adminhandler.AdminListChannelsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/v1/admin/channels",
					Handler: adminhandler.AdminCreateChannelHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/v1/admin/channels/:id",
					Handler: adminhandler.AdminUpdateChannelHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/admin/merchants",
					Handler: adminhandler.AdminListMerchantsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/v1/admin/merchants",
					Handler: adminhandler.AdminCreateMerchantHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/v1/admin/merchants/:merchant_id",
					Handler: adminhandler.AdminUpdateMerchantHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/admin/pay_products",
					Handler: adminhandler.AdminListPayProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/v1/admin/pay_products",
					Handler: adminhandler.AdminCreatePayProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/v1/admin/pay_products/:id",
					Handler: adminhandler.AdminUpdatePayProductHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/admin/pay_products/:id/bindings",
					Handler: adminhandler.AdminListPayProductBindingsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/v1/admin/pay_products/:id/bindings",
					Handler: adminhandler.AdminUpsertPayProductBindingHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/v1/admin/pay_product_bindings/:id",
					Handler: adminhandler.AdminUpdatePayProductBindingHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/v1/admin/pay_product_bindings/:id",
					Handler: adminhandler.AdminDeletePayProductBindingHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/admin/payout_products",
					Handler: adminhandler.AdminListPayoutProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/v1/admin/payout_products",
					Handler: adminhandler.AdminCreatePayoutProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/v1/admin/payout_products/:id",
					Handler: adminhandler.AdminUpdatePayoutProductHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/admin/payout_products/:id/bindings",
					Handler: adminhandler.AdminListPayoutProductBindingsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/v1/admin/payout_products/:id/bindings",
					Handler: adminhandler.AdminUpsertPayoutProductBindingHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/v1/admin/payout_product_bindings/:id",
					Handler: adminhandler.AdminUpdatePayoutProductBindingHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/v1/admin/payout_product_bindings/:id",
					Handler: adminhandler.AdminDeletePayoutProductBindingHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/admin/routing/summary",
					Handler: adminhandler.AdminRoutingSummaryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/admin/stats/overview",
					Handler: adminhandler.AdminStatsOverviewHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/admin/orders",
					Handler: adminhandler.AdminListOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/admin/refunds",
					Handler: adminhandler.AdminRefundsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/admin/reconcile/day",
					Handler: adminhandler.AdminReconcileDayHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/admin/admin_users",
					Handler: adminhandler.AdminListUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/admin/settlement/logs",
					Handler: adminhandler.AdminSettlementLogsHandler(serverCtx),
				},
			}...,
		),
	)
}
