// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: servicehub.proto

package servicehub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceHub_FindAdminUserByUsername_FullMethodName = "/servicehub.ServiceHub/FindAdminUserByUsername"
	ServiceHub_ListAdminUsers_FullMethodName          = "/servicehub.ServiceHub/ListAdminUsers"
	ServiceHub_GetDisplaySettings_FullMethodName      = "/servicehub.ServiceHub/GetDisplaySettings"
	ServiceHub_UpsertDisplaySettings_FullMethodName   = "/servicehub.ServiceHub/UpsertDisplaySettings"
	ServiceHub_MarkPayoutSuccess_FullMethodName       = "/servicehub.ServiceHub/MarkPayoutSuccess"
	ServiceHub_MarkPayoutFailed_FullMethodName        = "/servicehub.ServiceHub/MarkPayoutFailed"
)

// ServiceHubClient is the client API for ServiceHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 平台支撑数据（admin_users / global_settings / payout_orders 辅助更新）
type ServiceHubClient interface {
	FindAdminUserByUsername(ctx context.Context, in *FindAdminUserByUsernameReq, opts ...grpc.CallOption) (*FindAdminUserByUsernameResp, error)
	ListAdminUsers(ctx context.Context, in *ListAdminUsersReq, opts ...grpc.CallOption) (*ListAdminUsersResp, error)
	GetDisplaySettings(ctx context.Context, in *GetDisplaySettingsReq, opts ...grpc.CallOption) (*GetDisplaySettingsResp, error)
	UpsertDisplaySettings(ctx context.Context, in *UpsertDisplaySettingsReq, opts ...grpc.CallOption) (*GetDisplaySettingsResp, error)
	MarkPayoutSuccess(ctx context.Context, in *MarkPayoutSuccessReq, opts ...grpc.CallOption) (*MarkPayoutResultResp, error)
	MarkPayoutFailed(ctx context.Context, in *MarkPayoutFailedReq, opts ...grpc.CallOption) (*MarkPayoutResultResp, error)
}

type serviceHubClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceHubClient(cc grpc.ClientConnInterface) ServiceHubClient {
	return &serviceHubClient{cc}
}

func (c *serviceHubClient) FindAdminUserByUsername(ctx context.Context, in *FindAdminUserByUsernameReq, opts ...grpc.CallOption) (*FindAdminUserByUsernameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindAdminUserByUsernameResp)
	err := c.cc.Invoke(ctx, ServiceHub_FindAdminUserByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHubClient) ListAdminUsers(ctx context.Context, in *ListAdminUsersReq, opts ...grpc.CallOption) (*ListAdminUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminUsersResp)
	err := c.cc.Invoke(ctx, ServiceHub_ListAdminUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHubClient) GetDisplaySettings(ctx context.Context, in *GetDisplaySettingsReq, opts ...grpc.CallOption) (*GetDisplaySettingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDisplaySettingsResp)
	err := c.cc.Invoke(ctx, ServiceHub_GetDisplaySettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHubClient) UpsertDisplaySettings(ctx context.Context, in *UpsertDisplaySettingsReq, opts ...grpc.CallOption) (*GetDisplaySettingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDisplaySettingsResp)
	err := c.cc.Invoke(ctx, ServiceHub_UpsertDisplaySettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHubClient) MarkPayoutSuccess(ctx context.Context, in *MarkPayoutSuccessReq, opts ...grpc.CallOption) (*MarkPayoutResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkPayoutResultResp)
	err := c.cc.Invoke(ctx, ServiceHub_MarkPayoutSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHubClient) MarkPayoutFailed(ctx context.Context, in *MarkPayoutFailedReq, opts ...grpc.CallOption) (*MarkPayoutResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkPayoutResultResp)
	err := c.cc.Invoke(ctx, ServiceHub_MarkPayoutFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceHubServer is the server API for ServiceHub service.
// All implementations must embed UnimplementedServiceHubServer
// for forward compatibility.
//
// 平台支撑数据（admin_users / global_settings / payout_orders 辅助更新）
type ServiceHubServer interface {
	FindAdminUserByUsername(context.Context, *FindAdminUserByUsernameReq) (*FindAdminUserByUsernameResp, error)
	ListAdminUsers(context.Context, *ListAdminUsersReq) (*ListAdminUsersResp, error)
	GetDisplaySettings(context.Context, *GetDisplaySettingsReq) (*GetDisplaySettingsResp, error)
	UpsertDisplaySettings(context.Context, *UpsertDisplaySettingsReq) (*GetDisplaySettingsResp, error)
	MarkPayoutSuccess(context.Context, *MarkPayoutSuccessReq) (*MarkPayoutResultResp, error)
	MarkPayoutFailed(context.Context, *MarkPayoutFailedReq) (*MarkPayoutResultResp, error)
	mustEmbedUnimplementedServiceHubServer()
}

// UnimplementedServiceHubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceHubServer struct{}

func (UnimplementedServiceHubServer) FindAdminUserByUsername(context.Context, *FindAdminUserByUsernameReq) (*FindAdminUserByUsernameResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAdminUserByUsername not implemented")
}
func (UnimplementedServiceHubServer) ListAdminUsers(context.Context, *ListAdminUsersReq) (*ListAdminUsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdminUsers not implemented")
}
func (UnimplementedServiceHubServer) GetDisplaySettings(context.Context, *GetDisplaySettingsReq) (*GetDisplaySettingsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDisplaySettings not implemented")
}
func (UnimplementedServiceHubServer) UpsertDisplaySettings(context.Context, *UpsertDisplaySettingsReq) (*GetDisplaySettingsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertDisplaySettings not implemented")
}
func (UnimplementedServiceHubServer) MarkPayoutSuccess(context.Context, *MarkPayoutSuccessReq) (*MarkPayoutResultResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkPayoutSuccess not implemented")
}
func (UnimplementedServiceHubServer) MarkPayoutFailed(context.Context, *MarkPayoutFailedReq) (*MarkPayoutResultResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkPayoutFailed not implemented")
}
func (UnimplementedServiceHubServer) mustEmbedUnimplementedServiceHubServer() {}
func (UnimplementedServiceHubServer) testEmbeddedByValue()                    {}

// UnsafeServiceHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceHubServer will
// result in compilation errors.
type UnsafeServiceHubServer interface {
	mustEmbedUnimplementedServiceHubServer()
}

func RegisterServiceHubServer(s grpc.ServiceRegistrar, srv ServiceHubServer) {
	// If the following call pancis, it indicates UnimplementedServiceHubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceHub_ServiceDesc, srv)
}

func _ServiceHub_FindAdminUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAdminUserByUsernameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHubServer).FindAdminUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceHub_FindAdminUserByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHubServer).FindAdminUserByUsername(ctx, req.(*FindAdminUserByUsernameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHub_ListAdminUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHubServer).ListAdminUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceHub_ListAdminUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHubServer).ListAdminUsers(ctx, req.(*ListAdminUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHub_GetDisplaySettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDisplaySettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHubServer).GetDisplaySettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceHub_GetDisplaySettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHubServer).GetDisplaySettings(ctx, req.(*GetDisplaySettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHub_UpsertDisplaySettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertDisplaySettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHubServer).UpsertDisplaySettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceHub_UpsertDisplaySettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHubServer).UpsertDisplaySettings(ctx, req.(*UpsertDisplaySettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHub_MarkPayoutSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkPayoutSuccessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHubServer).MarkPayoutSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceHub_MarkPayoutSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHubServer).MarkPayoutSuccess(ctx, req.(*MarkPayoutSuccessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHub_MarkPayoutFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkPayoutFailedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHubServer).MarkPayoutFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceHub_MarkPayoutFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHubServer).MarkPayoutFailed(ctx, req.(*MarkPayoutFailedReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceHub_ServiceDesc is the grpc.ServiceDesc for ServiceHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicehub.ServiceHub",
	HandlerType: (*ServiceHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAdminUserByUsername",
			Handler:    _ServiceHub_FindAdminUserByUsername_Handler,
		},
		{
			MethodName: "ListAdminUsers",
			Handler:    _ServiceHub_ListAdminUsers_Handler,
		},
		{
			MethodName: "GetDisplaySettings",
			Handler:    _ServiceHub_GetDisplaySettings_Handler,
		},
		{
			MethodName: "UpsertDisplaySettings",
			Handler:    _ServiceHub_UpsertDisplaySettings_Handler,
		},
		{
			MethodName: "MarkPayoutSuccess",
			Handler:    _ServiceHub_MarkPayoutSuccess_Handler,
		},
		{
			MethodName: "MarkPayoutFailed",
			Handler:    _ServiceHub_MarkPayoutFailed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "servicehub.proto",
}
