// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: servicehub.proto

package servicehub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAdminUserByUsernameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAdminUserByUsernameReq) Reset() {
	*x = FindAdminUserByUsernameReq{}
	mi := &file_servicehub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAdminUserByUsernameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAdminUserByUsernameReq) ProtoMessage() {}

func (x *FindAdminUserByUsernameReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAdminUserByUsernameReq.ProtoReflect.Descriptor instead.
func (*FindAdminUserByUsernameReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{0}
}

func (x *FindAdminUserByUsernameReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type FindAdminUserByUsernameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *AdminUser             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAdminUserByUsernameResp) Reset() {
	*x = FindAdminUserByUsernameResp{}
	mi := &file_servicehub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAdminUserByUsernameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAdminUserByUsernameResp) ProtoMessage() {}

func (x *FindAdminUserByUsernameResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAdminUserByUsernameResp.ProtoReflect.Descriptor instead.
func (*FindAdminUserByUsernameResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{1}
}

func (x *FindAdminUserByUsernameResp) GetUser() *AdminUser {
	if x != nil {
		return x.User
	}
	return nil
}

type AdminUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_servicehub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{2}
}

func (x *AdminUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUser) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *AdminUser) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AdminUserPublic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Status        int64                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserPublic) Reset() {
	*x = AdminUserPublic{}
	mi := &file_servicehub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserPublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserPublic) ProtoMessage() {}

func (x *AdminUserPublic) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserPublic.ProtoReflect.Descriptor instead.
func (*AdminUserPublic) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{3}
}

func (x *AdminUserPublic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUserPublic) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUserPublic) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListAdminUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminUsersReq) Reset() {
	*x = ListAdminUsersReq{}
	mi := &file_servicehub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminUsersReq) ProtoMessage() {}

func (x *ListAdminUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminUsersReq.ProtoReflect.Descriptor instead.
func (*ListAdminUsersReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{4}
}

type ListAdminUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*AdminUserPublic     `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminUsersResp) Reset() {
	*x = ListAdminUsersResp{}
	mi := &file_servicehub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminUsersResp) ProtoMessage() {}

func (x *ListAdminUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminUsersResp.ProtoReflect.Descriptor instead.
func (*ListAdminUsersResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{5}
}

func (x *ListAdminUsersResp) GetUsers() []*AdminUserPublic {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetDisplaySettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisplaySettingsReq) Reset() {
	*x = GetDisplaySettingsReq{}
	mi := &file_servicehub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisplaySettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisplaySettingsReq) ProtoMessage() {}

func (x *GetDisplaySettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisplaySettingsReq.ProtoReflect.Descriptor instead.
func (*GetDisplaySettingsReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{6}
}

type GetDisplaySettingsResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CountryCode    string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CurrencyCode   string                 `protobuf:"bytes,2,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	CurrencySymbol string                 `protobuf:"bytes,3,opt,name=currency_symbol,json=currencySymbol,proto3" json:"currency_symbol,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDisplaySettingsResp) Reset() {
	*x = GetDisplaySettingsResp{}
	mi := &file_servicehub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisplaySettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisplaySettingsResp) ProtoMessage() {}

func (x *GetDisplaySettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisplaySettingsResp.ProtoReflect.Descriptor instead.
func (*GetDisplaySettingsResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{7}
}

func (x *GetDisplaySettingsResp) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GetDisplaySettingsResp) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *GetDisplaySettingsResp) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

type UpsertDisplaySettingsReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CountryCode    string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CurrencyCode   string                 `protobuf:"bytes,2,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	CurrencySymbol string                 `protobuf:"bytes,3,opt,name=currency_symbol,json=currencySymbol,proto3" json:"currency_symbol,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertDisplaySettingsReq) Reset() {
	*x = UpsertDisplaySettingsReq{}
	mi := &file_servicehub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDisplaySettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDisplaySettingsReq) ProtoMessage() {}

func (x *UpsertDisplaySettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDisplaySettingsReq.ProtoReflect.Descriptor instead.
func (*UpsertDisplaySettingsReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertDisplaySettingsReq) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *UpsertDisplaySettingsReq) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *UpsertDisplaySettingsReq) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

type MarkPayoutSuccessReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderNo         string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UpstreamTradeNo string                 `protobuf:"bytes,2,opt,name=upstream_trade_no,json=upstreamTradeNo,proto3" json:"upstream_trade_no,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkPayoutSuccessReq) Reset() {
	*x = MarkPayoutSuccessReq{}
	mi := &file_servicehub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPayoutSuccessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPayoutSuccessReq) ProtoMessage() {}

func (x *MarkPayoutSuccessReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPayoutSuccessReq.ProtoReflect.Descriptor instead.
func (*MarkPayoutSuccessReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{9}
}

func (x *MarkPayoutSuccessReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *MarkPayoutSuccessReq) GetUpstreamTradeNo() string {
	if x != nil {
		return x.UpstreamTradeNo
	}
	return ""
}

type MarkPayoutFailedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPayoutFailedReq) Reset() {
	*x = MarkPayoutFailedReq{}
	mi := &file_servicehub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPayoutFailedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPayoutFailedReq) ProtoMessage() {}

func (x *MarkPayoutFailedReq) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPayoutFailedReq.ProtoReflect.Descriptor instead.
func (*MarkPayoutFailedReq) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{10}
}

func (x *MarkPayoutFailedReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type MarkPayoutResultResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPayoutResultResp) Reset() {
	*x = MarkPayoutResultResp{}
	mi := &file_servicehub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPayoutResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPayoutResultResp) ProtoMessage() {}

func (x *MarkPayoutResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_servicehub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPayoutResultResp.ProtoReflect.Descriptor instead.
func (*MarkPayoutResultResp) Descriptor() ([]byte, []int) {
	return file_servicehub_proto_rawDescGZIP(), []int{11}
}

func (x *MarkPayoutResultResp) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

var File_servicehub_proto protoreflect.FileDescriptor

const file_servicehub_proto_rawDesc = "" +
	"\n" +
	"\x10servicehub.proto\x12\n" +
	"servicehub\"8\n" +
	"\x1aFindAdminUserByUsernameReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"H\n" +
	"\x1bFindAdminUserByUsernameResp\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.servicehub.AdminUserR\x04user\"t\n" +
	"\tAdminUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\"U\n" +
	"\x0fAdminUserPublic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\"\x13\n" +
	"\x11ListAdminUsersReq\"G\n" +
	"\x12ListAdminUsersResp\x121\n" +
	"\x05users\x18\x01 \x03(\v2\x1b.servicehub.AdminUserPublicR\x05users\"\x17\n" +
	"\x15GetDisplaySettingsReq\"\x89\x01\n" +
	"\x16GetDisplaySettingsResp\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12#\n" +
	"\rcurrency_code\x18\x02 \x01(\tR\fcurrencyCode\x12'\n" +
	"\x0fcurrency_symbol\x18\x03 \x01(\tR\x0ecurrencySymbol\"\x8b\x01\n" +
	"\x18UpsertDisplaySettingsReq\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12#\n" +
	"\rcurrency_code\x18\x02 \x01(\tR\fcurrencyCode\x12'\n" +
	"\x0fcurrency_symbol\x18\x03 \x01(\tR\x0ecurrencySymbol\"]\n" +
	"\x14MarkPayoutSuccessReq\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12*\n" +
	"\x11upstream_trade_no\x18\x02 \x01(\tR\x0fupstreamTradeNo\"0\n" +
	"\x13MarkPayoutFailedReq\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"0\n" +
	"\x14MarkPayoutResultResp\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged2\xb9\x04\n" +
	"\n" +
	"ServiceHub\x12j\n" +
	"\x17FindAdminUserByUsername\x12&.servicehub.FindAdminUserByUsernameReq\x1a'.servicehub.FindAdminUserByUsernameResp\x12O\n" +
	"\x0eListAdminUsers\x12\x1d.servicehub.ListAdminUsersReq\x1a\x1e.servicehub.ListAdminUsersResp\x12[\n" +
	"\x12GetDisplaySettings\x12!.servicehub.GetDisplaySettingsReq\x1a\".servicehub.GetDisplaySettingsResp\x12a\n" +
	"\x15UpsertDisplaySettings\x12$.servicehub.UpsertDisplaySettingsReq\x1a\".servicehub.GetDisplaySettingsResp\x12W\n" +
	"\x11MarkPayoutSuccess\x12 .servicehub.MarkPayoutSuccessReq\x1a .servicehub.MarkPayoutResultResp\x12U\n" +
	"\x10MarkPayoutFailed\x12\x1f.servicehub.MarkPayoutFailedReq\x1a .servicehub.MarkPayoutResultRespB8Z6github.com/gloopai/pay/common/pb/servicehub;servicehubb\x06proto3"

var (
	file_servicehub_proto_rawDescOnce sync.Once
	file_servicehub_proto_rawDescData []byte
)

func file_servicehub_proto_rawDescGZIP() []byte {
	file_servicehub_proto_rawDescOnce.Do(func() {
		file_servicehub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servicehub_proto_rawDesc), len(file_servicehub_proto_rawDesc)))
	})
	return file_servicehub_proto_rawDescData
}

var file_servicehub_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_servicehub_proto_goTypes = []any{
	(*FindAdminUserByUsernameReq)(nil),  // 0: servicehub.FindAdminUserByUsernameReq
	(*FindAdminUserByUsernameResp)(nil), // 1: servicehub.FindAdminUserByUsernameResp
	(*AdminUser)(nil),                   // 2: servicehub.AdminUser
	(*AdminUserPublic)(nil),             // 3: servicehub.AdminUserPublic
	(*ListAdminUsersReq)(nil),           // 4: servicehub.ListAdminUsersReq
	(*ListAdminUsersResp)(nil),          // 5: servicehub.ListAdminUsersResp
	(*GetDisplaySettingsReq)(nil),       // 6: servicehub.GetDisplaySettingsReq
	(*GetDisplaySettingsResp)(nil),      // 7: servicehub.GetDisplaySettingsResp
	(*UpsertDisplaySettingsReq)(nil),    // 8: servicehub.UpsertDisplaySettingsReq
	(*MarkPayoutSuccessReq)(nil),        // 9: servicehub.MarkPayoutSuccessReq
	(*MarkPayoutFailedReq)(nil),         // 10: servicehub.MarkPayoutFailedReq
	(*MarkPayoutResultResp)(nil),        // 11: servicehub.MarkPayoutResultResp
}
var file_servicehub_proto_depIdxs = []int32{
	2,  // 0: servicehub.FindAdminUserByUsernameResp.user:type_name -> servicehub.AdminUser
	3,  // 1: servicehub.ListAdminUsersResp.users:type_name -> servicehub.AdminUserPublic
	0,  // 2: servicehub.ServiceHub.FindAdminUserByUsername:input_type -> servicehub.FindAdminUserByUsernameReq
	4,  // 3: servicehub.ServiceHub.ListAdminUsers:input_type -> servicehub.ListAdminUsersReq
	6,  // 4: servicehub.ServiceHub.GetDisplaySettings:input_type -> servicehub.GetDisplaySettingsReq
	8,  // 5: servicehub.ServiceHub.UpsertDisplaySettings:input_type -> servicehub.UpsertDisplaySettingsReq
	9,  // 6: servicehub.ServiceHub.MarkPayoutSuccess:input_type -> servicehub.MarkPayoutSuccessReq
	10, // 7: servicehub.ServiceHub.MarkPayoutFailed:input_type -> servicehub.MarkPayoutFailedReq
	1,  // 8: servicehub.ServiceHub.FindAdminUserByUsername:output_type -> servicehub.FindAdminUserByUsernameResp
	5,  // 9: servicehub.ServiceHub.ListAdminUsers:output_type -> servicehub.ListAdminUsersResp
	7,  // 10: servicehub.ServiceHub.GetDisplaySettings:output_type -> servicehub.GetDisplaySettingsResp
	7,  // 11: servicehub.ServiceHub.UpsertDisplaySettings:output_type -> servicehub.GetDisplaySettingsResp
	11, // 12: servicehub.ServiceHub.MarkPayoutSuccess:output_type -> servicehub.MarkPayoutResultResp
	11, // 13: servicehub.ServiceHub.MarkPayoutFailed:output_type -> servicehub.MarkPayoutResultResp
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_servicehub_proto_init() }
func file_servicehub_proto_init() {
	if File_servicehub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servicehub_proto_rawDesc), len(file_servicehub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servicehub_proto_goTypes,
		DependencyIndexes: file_servicehub_proto_depIdxs,
		MessageInfos:      file_servicehub_proto_msgTypes,
	}.Build()
	File_servicehub_proto = out.File
	file_servicehub_proto_goTypes = nil
	file_servicehub_proto_depIdxs = nil
}
